import { buildSample } from "./helpers";
import type { GradedSampleLetter } from "./types";

export const ALLIED_HEALTH_SAMPLES: GradedSampleLetter[] = [
  buildSample({
    id: "sample-dent-referral-b",
    scenarioId: "w-dent-003",
    profession: "dentistry",
    title: "Referral — symptomatic lower third molar",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 178,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Walsh,\n\nRe: Mr Chidi Okafor, aged 26 years\n\nI am writing to refer Mr Okafor for assessment of symptomatic lower third molars. I would be grateful if you could review him and advise on surgical management.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Referral purpose and specialist request clear."],
      },
      {
        label: "Findings",
        text: "He presents with recurrent pericoronal pain affecting the lower left eighth tooth for three weeks. Orthopantomogram shows a mesioangular partially erupted LL8 without caries. He has mild asthma controlled with salbutamol as required and smokes five cigarettes per day; he has been counselled to stop before any procedure.",
        sourceNoteIds: ["n2", "n3", "n4", "n5"],
        notes: ["Examination and radiograph findings included.", "Relevant medical history for surgery documented."],
      },
      {
        label: "Request",
        text: "Please assess and provide a treatment plan at your earliest convenience.\n\nYours sincerely,\n[Dentist name]",
        sourceNoteIds: [],
        notes: ["Graphic design occupation omitted as irrelevant."],
      },
    ],
    assessorSummary: "Likely Grade B: surgical referral with selected clinical and medical detail.",
  }),
  buildSample({
    id: "sample-phys-reply-b",
    scenarioId: "w-phys-004",
    profession: "physiotherapy",
    title: "Reply — subacute low back pain",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 188,
    paragraphs: [
      {
        label: "Opening",
        text: "Dear Dr Marsh,\n\nRe: Ms Laura Turner, aged 34 years\n\nThank you for referring Ms Turner with subacute low back pain of six weeks' duration without red flags.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Referral acknowledged; red-flag status stated."],
      },
      {
        label: "Assessment & treatment",
        text: "Assessment showed limited lumbar flexion and negative straight leg raise. She completed six sessions comprising manual therapy and a core stability programme. Pain reduced from 7/10 to 3/10 on the NPRS and she has returned to desk work.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Functional outcome and treatment summarised concisely."],
      },
      {
        label: "Discharge plan",
        text: "Ms Turner has been discharged with a home exercise programme. Please re-refer if symptoms worsen or neurological signs develop.\n\nYours sincerely,\n[Physiotherapist name]",
        sourceNoteIds: ["n5"],
        notes: ["Discharge and safety-netting clear."],
      },
    ],
    assessorSummary: "Likely Grade B: reply answers referrer with assessment, treatment, and discharge plan.",
  }),
  buildSample({
    id: "sample-ot-discharge-b",
    scenarioId: "w-ot-005",
    profession: "occupational_therapy",
    title: "Discharge — stroke home adaptation",
    letterType: "discharge",
    estimatedOverall: "B",
    wordCount: 195,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Ellis,\n\nRe: Mr Minh Nguyen, aged 68 years\n\nI am writing to summarise occupational therapy input following Mr Nguyen's mild stroke and discharge home yesterday.",
        sourceNoteIds: ["n1"],
        notes: ["Discharge summary purpose clear."],
      },
      {
        label: "Functional status & equipment",
        text: "He has right-sided weakness but achieves independent transfers using a grab rail. We installed a shower chair, bathroom grab rails, and a raised toilet seat. His wife received training in safe mobility techniques, and Meals on Wheels has been arranged.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Equipment and community supports documented for GP awareness."],
      },
      {
        label: "Recommendations",
        text: "I recommend you review fatigue and mood within two weeks and contact our service if functional decline occurs.\n\nYours sincerely,\n[Occupational therapist name]",
        sourceNoteIds: ["n5"],
        notes: ["GP follow-up priorities stated."],
      },
    ],
    assessorSummary: "Likely Grade B: OT discharge with functional summary and home supports.",
  }),
  buildSample({
    id: "sample-pod-referral-b",
    scenarioId: "w-pod-006",
    profession: "podiatry",
    title: "Referral — diabetic foot ulcer vascular review",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 182,
    paragraphs: [
      {
        label: "Urgent referral",
        text: "Dear Mr Hale,\n\nRe: Mr Alan Peters, aged 59 years\n\nI am writing to refer Mr Peters for urgent vascular assessment of a non-healing plantar ulcer on his left foot.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Urgent referral purpose explicit."],
      },
      {
        label: "Wound & diabetes status",
        text: "The ulcer measures 1.2 cm with no probing to bone. His HbA1c is 68 mmol/mol on metformin and gliclazide. An offloading boot has been supplied and there are no systemic signs of infection. Dorsalis pedis pulses are weak with delayed capillary refill.",
        sourceNoteIds: ["n2", "n3", "n4", "n5"],
        notes: ["Wound size, glycaemic control, and vascular status included."],
      },
      {
        label: "Request",
        text: "I would appreciate your urgent review and advice on further vascular investigation.\n\nYours sincerely,\n[Podiatrist name]",
        sourceNoteIds: [],
        notes: ["Football hobby omitted as irrelevant."],
      },
    ],
    assessorSummary: "Likely Grade B: vascular referral with selected diabetic foot findings.",
  }),
  buildSample({
    id: "sample-opt-referral-b",
    scenarioId: "w-opt-007",
    profession: "optometry",
    title: "Referral — suspected open-angle glaucoma",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 176,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Lin,\n\nRe: Mrs Diane Collins, aged 62 years\n\nI am writing to refer Mrs Collins for assessment of suspected primary open-angle glaucoma following routine examination on 14 June 2026.",
        sourceNoteIds: ["n1"],
        notes: ["Referral reason and patient identity clear."],
      },
      {
        label: "Findings",
        text: "Intraocular pressure was 24 mmHg right and 26 mmHg left without symptoms. Cup-to-disc ratio is 0.6 bilaterally with RNFL thinning on OCT. There is a family history of glaucoma in her father. I commenced latanoprost nocte to both eyes pending specialist review.",
        sourceNoteIds: ["n2", "n3", "n4", "n5"],
        notes: ["IOP, disc, OCT, and family history included.", "Interim treatment documented."],
      },
      {
        label: "Request",
        text: "Please assess and advise on long-term glaucoma management.\n\nYours sincerely,\n[Optometrist name]",
        sourceNoteIds: [],
        notes: ["Driving distances omitted as not clinically required."],
      },
    ],
    assessorSummary: "Likely Grade B: glaucoma referral with examination findings and interim drops.",
  }),
  buildSample({
    id: "sample-diet-advice-b",
    scenarioId: "w-diet-008",
    profession: "dietetics",
    title: "Advice — type 2 diabetes dietary plan",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 172,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Reid,\n\nRe: Mr Yusuf Hassan, aged 45 years\n\nI am writing to outline the dietary management plan agreed with Mr Hassan following his new diagnosis of type 2 diabetes.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Advice letter purpose clear."],
      },
      {
        label: "Assessment & recommendations",
        text: "His BMI is 31 and HbA1c was 58 mmol/mol per your recent letter. He reported irregular meals, high sugary drink intake, and limited vegetables. We agreed portion control, reduced sugar intake, and increased dietary fibre.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Eating pattern and agreed changes documented."],
      },
      {
        label: "Follow-up",
        text: "Dietetic review is scheduled in four weeks. Please re-refer if he loses more than 5% body weight unintentionally.\n\nYours sincerely,\n[Dietitian name]",
        sourceNoteIds: ["n5"],
        notes: ["Follow-up and re-referral criteria stated."],
      },
    ],
    assessorSummary: "Likely Grade B: dietary plan communicated clearly to GP.",
  }),
  buildSample({
    id: "sample-rad-referral-b",
    scenarioId: "w-rad-009",
    profession: "radiography",
    title: "Referral — incidental pulmonary nodule",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 168,
    paragraphs: [
      {
        label: "Examination summary",
        text: "Dear Dr Clarke,\n\nRe: Mr Peter Boyd, aged 55 years\n\nI am writing regarding a chest X-ray performed on 8 June 2026 for persistent cough.",
        sourceNoteIds: ["n1"],
        notes: ["Examination and indication stated."],
      },
      {
        label: "Findings",
        text: "A 6 mm nodule is present in the right upper lobe without effusion. Heart size is normal and the lungs are otherwise clear. Mr Boyd has a 20 pack-year smoking history and was counselled regarding cessation.",
        sourceNoteIds: ["n2", "n3", "n5"],
        notes: ["Nodule size and location documented.", "Smoking history relevant to follow-up."],
      },
      {
        label: "Recommendation",
        text: "In line with local guidelines, I recommend CT chest for further assessment, which I would be grateful if you could arrange.\n\nYours sincerely,\n[Radiographer name]",
        sourceNoteIds: ["n4"],
        notes: ["Follow-up pathway delegated appropriately to GP."],
      },
    ],
    assessorSummary: "Likely Grade B: incidental finding communicated with clear follow-up recommendation.",
  }),
  buildSample({
    id: "sample-sp-referral-b",
    scenarioId: "w-sp-010",
    profession: "speech_pathology",
    title: "Referral — progressive dysphagia",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 184,
    paragraphs: [
      {
        label: "Urgent referral",
        text: "Dear Dr Stone,\n\nRe: Mr Geoff Edwards, aged 70 years\n\nI am writing to refer Mr Edwards for urgent ENT assessment of progressive dysphagia to solids over eight weeks.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Symptom timeline and urgency clear."],
      },
      {
        label: "Swallow assessment",
        text: "He has lost 3 kg in weight. Videofluoroscopy showed residue in the valleculae with cough post-swallow. A modified diet at IDDSI Level 5 is recommended pending ENT review. He is an ex-smoker and a hoarse voice was noted.",
        sourceNoteIds: ["n2", "n3", "n4", "n5"],
        notes: ["Aspiration risk and interim diet documented.", "Red-flag features included."],
      },
      {
        label: "Request",
        text: "Please arrange urgent laryngoscopy and advise on further management.\n\nYours sincerely,\n[Speech pathologist name]",
        sourceNoteIds: [],
        notes: ["Retired teacher status omitted."],
      },
    ],
    assessorSummary: "Likely Grade B: urgent ENT referral with swallow findings and weight loss.",
  }),
  buildSample({
    id: "sample-vet-referral-b",
    scenarioId: "w-vet-011",
    profession: "veterinary_science",
    title: "Referral — comminuted tibial fracture",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 178,
    paragraphs: [
      {
        label: "Referral",
        text: "Dear Dr Morrison,\n\nRe: Bella, 4-year-old female Labrador, owner Mrs Shaw\n\nI am writing to refer Bella for surgical assessment of a comminuted mid-tibial fracture of the right hind limb.",
        sourceNoteIds: ["n1", "n2", "n3"],
        notes: ["Patient, owner, and injury identified."],
      },
      {
        label: "Presentation & stabilisation",
        text: "Bella was hit by a car yesterday and is non-weight-bearing on the right hind limb. Radiographs confirm a comminuted mid-tibial fracture. She received a morphine constant-rate infusion overnight and continues buprenorphine. Chest auscultation is clear and PCV is 38%.",
        sourceNoteIds: ["n2", "n3", "n4", "n5"],
        notes: ["Mechanism, imaging, analgesia, and stability documented."],
      },
      {
        label: "Request",
        text: "Please assess Bella for surgical repair at your earliest convenience.\n\nYours sincerely,\n[Veterinary surgeon name]",
        sourceNoteIds: [],
        notes: ["Insurance detail omitted as irrelevant to clinical handover."],
      },
    ],
    assessorSummary: "Likely Grade B: veterinary surgical referral with stabilisation summary.",
  }),
];
