import { buildSample } from "./helpers";
import type { GradedSampleLetter } from "./types";

/** Grade C weak examples — one per profession (pharmacy C lives in pharmacy.ts). */
export const GRADE_C_SAMPLES: GradedSampleLetter[] = [
  buildSample({
    id: "sample-nurs-discharge-c",
    scenarioId: "w-nurs-012",
    profession: "nursing",
    title: "Weak example — hip discharge handover (Grade C)",
    letterType: "discharge",
    estimatedOverall: "C",
    wordCount: 118,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Hi,\n\nMrs Patel had hip surgery. She is going home.",
        sourceNoteIds: ["n1"],
        notes: ["No named recipient; purpose of handover unclear."],
      },
      {
        label: "Body (weak)",
        text: "Wound OK. Daughter helps. Patient likes morning showers.",
        sourceNoteIds: ["n2", "n4", "n5"],
        notes: ["Telegraphic list; shower preference irrelevant.", "Dressing education not documented."],
      },
      {
        label: "Closing (weak)",
        text: "Thanks,\nNurse",
        sourceNoteIds: [],
        notes: ["Informal tone; no follow-up plan for community nurse."],
      },
    ],
    assessorSummary: "Likely Grade C: handover purpose missing; key nursing actions not communicated.",
  }),
  buildSample({
    id: "sample-med-reply-c",
    scenarioId: "w-med-015",
    profession: "medicine",
    title: "Weak example — fatigue reply (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 125,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nI saw Mrs Lopez about tiredness.",
        sourceNoteIds: ["n1"],
        notes: ["Referrer not named; referral not acknowledged."],
      },
      {
        label: "Body (weak)",
        text: "Tests done. TSH bit high. She works nights. Going on holiday soon.",
        sourceNoteIds: ["n2", "n3", "n5", "n6"],
        notes: ["Results not explained; holiday irrelevant.", "Management plan absent."],
      },
      {
        label: "Closing (weak)",
        text: "Regards",
        sourceNoteIds: [],
        notes: ["No follow-up plan or GP action requested."],
      },
    ],
    assessorSummary: "Likely Grade C: fails to answer referrer with findings and plan.",
  }),
  buildSample({
    id: "sample-dent-referral-c",
    scenarioId: "w-dent-003",
    profession: "dentistry",
    title: "Weak example — third molar referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 108,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Specialist,\n\nMr Okafor has tooth pain.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Not a clear surgical referral; specialist unnamed."],
      },
      {
        label: "Body (weak)",
        text: "X-ray done. Asthma as child. He designs graphics.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Missing tooth position and surgical indication.", "Irrelevant occupation included."],
      },
      {
        label: "Closing (weak)",
        text: "Please help if you can.",
        sourceNoteIds: [],
        notes: ["No request for assessment or treatment plan."],
      },
    ],
    assessorSummary: "Likely Grade C: referral purpose and clinical detail insufficient.",
  }),
  buildSample({
    id: "sample-phys-reply-c",
    scenarioId: "w-phys-004",
    profession: "physiotherapy",
    title: "Weak example — LBP reply (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 112,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Hi Dr Marsh,\n\nLaura came for physio.",
        sourceNoteIds: ["n1"],
        notes: ["Informal; no reply purpose stated."],
      },
      {
        label: "Body (weak)",
        text: "Back pain better. Did exercises. Runs marathons.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Marathon detail irrelevant.", "Assessment findings and discharge plan missing."],
      },
      {
        label: "Closing (weak)",
        text: "Cheers",
        sourceNoteIds: [],
        notes: ["Too informal for professional reply."],
      },
    ],
    assessorSummary: "Likely Grade C: does not summarise treatment or safety-netting for GP.",
  }),
  buildSample({
    id: "sample-ot-discharge-c",
    scenarioId: "w-ot-005",
    profession: "occupational_therapy",
    title: "Weak example — stroke discharge (Grade C)",
    letterType: "discharge",
    estimatedOverall: "C",
    wordCount: 115,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMr Nguyen went home after stroke.",
        sourceNoteIds: ["n1"],
        notes: ["Discharge summary purpose vague."],
      },
      {
        label: "Body (weak)",
        text: "Weak on one side. Got rails. Wife helps. Was accountant.",
        sourceNoteIds: ["n2", "n3", "n4", "n6"],
        notes: ["Equipment list incomplete.", "Irrelevant employment history."],
      },
      {
        label: "Closing (weak)",
        text: "Thanks",
        sourceNoteIds: [],
        notes: ["No GP follow-up recommendations."],
      },
    ],
    assessorSummary: "Likely Grade C: OT handover lacks structured functional and equipment detail.",
  }),
  buildSample({
    id: "sample-pod-referral-c",
    scenarioId: "w-pod-006",
    profession: "podiatry",
    title: "Weak example — diabetic foot referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 105,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Surgeon,\n\nPatient has foot ulcer.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Patient unnamed; urgency not stated."],
      },
      {
        label: "Body (weak)",
        text: "Diabetes. Some swelling. Plays football.",
        sourceNoteIds: ["n3", "n6"],
        notes: ["Ulcer size, pulses, and offloading omitted.", "Football irrelevant."],
      },
      {
        label: "Closing (weak)",
        text: "See him when free.",
        sourceNoteIds: [],
        notes: ["No urgent vascular review requested."],
      },
    ],
    assessorSummary: "Likely Grade C: critical vascular and wound details missing.",
  }),
  buildSample({
    id: "sample-opt-referral-c",
    scenarioId: "w-opt-007",
    profession: "optometry",
    title: "Weak example — glaucoma referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 98,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMrs Collins eye test.",
        sourceNoteIds: ["n1"],
        notes: ["Referral reason not stated."],
      },
      {
        label: "Body (weak)",
        text: "Pressures high. Family history maybe. Drives a lot.",
        sourceNoteIds: ["n2", "n4", "n6"],
        notes: ["IOP values and disc findings missing.", "Driving detail irrelevant."],
      },
      {
        label: "Closing (weak)",
        text: "Please check.",
        sourceNoteIds: [],
        notes: ["No request for specialist glaucoma assessment."],
      },
    ],
    assessorSummary: "Likely Grade C: insufficient examination detail for ophthalmology referral.",
  }),
  buildSample({
    id: "sample-diet-advice-c",
    scenarioId: "w-diet-008",
    profession: "dietetics",
    title: "Weak example — diabetes diet advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 102,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Dr Reid,\n\nI met Mr Hassan about food.",
        sourceNoteIds: ["n1"],
        notes: ["Advice letter purpose unclear."],
      },
      {
        label: "Body (weak)",
        text: "He is overweight. Eats badly. Likes cricket.",
        sourceNoteIds: ["n2", "n3", "n6"],
        notes: ["No agreed plan or measurable recommendations.", "Cricket irrelevant."],
      },
      {
        label: "Closing (weak)",
        text: "Hope this helps.",
        sourceNoteIds: [],
        notes: ["No follow-up or re-referral criteria."],
      },
    ],
    assessorSummary: "Likely Grade C: dietary plan not documented for GP continuity.",
  }),
  buildSample({
    id: "sample-rad-referral-c",
    scenarioId: "w-rad-009",
    profession: "radiography",
    title: "Weak example — pulmonary nodule (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 95,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear GP,\n\nCXR done for cough.",
        sourceNoteIds: ["n1"],
        notes: ["Findings not introduced with clinical context."],
      },
      {
        label: "Body (weak)",
        text: "Small spot on lung. Rest OK. Old knee injury.",
        sourceNoteIds: ["n2", "n3", "n6"],
        notes: ["Nodule size and follow-up pathway missing.", "Irrelevant knee history."],
      },
      {
        label: "Closing (weak)",
        text: "Thanks",
        sourceNoteIds: [],
        notes: ["No recommendation for CT or smoking counselling documented."],
      },
    ],
    assessorSummary: "Likely Grade C: incidental finding communicated without actionable follow-up.",
  }),
  buildSample({
    id: "sample-sp-referral-c",
    scenarioId: "w-sp-010",
    profession: "speech_pathology",
    title: "Weak example — dysphagia referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 108,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear ENT,\n\nMr Edwards swallowing problems.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Urgency and timeline not stated."],
      },
      {
        label: "Body (weak)",
        text: "Coughs when eating. Retired teacher. Some weight change.",
        sourceNoteIds: ["n3", "n5", "n6"],
        notes: ["VFSS findings and IDDSI level omitted.", "Occupation irrelevant."],
      },
      {
        label: "Closing (weak)",
        text: "Please see.",
        sourceNoteIds: [],
        notes: ["No request for laryngoscopy."],
      },
    ],
    assessorSummary: "Likely Grade C: aspiration risk and interim diet not communicated.",
  }),
  buildSample({
    id: "sample-vet-referral-c",
    scenarioId: "w-vet-011",
    profession: "veterinary_science",
    title: "Weak example — fracture referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 100,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Colleague,\n\nDog with broken leg.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Patient and owner not identified."],
      },
      {
        label: "Body (weak)",
        text: "Hit by car. X-ray bad. Has insurance.",
        sourceNoteIds: ["n2", "n3", "n6"],
        notes: ["Fracture type and analgesia missing.", "Insurance irrelevant."],
      },
      {
        label: "Closing (weak)",
        text: "Thanks",
        sourceNoteIds: [],
        notes: ["No surgical assessment requested."],
      },
    ],
    assessorSummary: "Likely Grade C: referral lacks stabilisation summary and surgical request.",
  }),
];
