import { buildSample } from "./helpers";
import type { GradedSampleLetter } from "./types";

export const WAVE3_GRADED_SAMPLES: GradedSampleLetter[] = [
  // dentistry — NZ
  buildSample({
    id: "sample-dent-nz-wave3-b",
    scenarioId: "w-dent-nz-wave3",
    profession: "dentistry",
    title: "Reply — post-extraction dry socket management",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 176,
    paragraphs: [
      {
        label: "Opening",
        text: "Dear Dr Williams,\n\nRe: Ms Kate Thompson, aged 38 years\n\nThank you for referring Ms Thompson regarding persistent post-extraction pain following lower molar extraction three days ago.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Referral acknowledged; clinical context clear."],
      },
      {
        label: "Findings & treatment",
        text: "On review on 11 June 2026, the socket was empty with alveolar bone visible and no pus. I irrigated the site with chlorhexidine and placed an Alvogyl dressing.",
        sourceNoteIds: ["n3", "n4"],
        notes: ["Examination findings and irrigation documented."],
      },
      {
        label: "Plan",
        text: "Analgesia with ibuprofen and paracetamol has been charted. She was advised to avoid smoking and maintain oral hygiene. I will review her in 48 hours and would be grateful if you could re-refer if pain worsens or signs of infection develop.\n\nYours sincerely,\n[Dentist name]",
        sourceNoteIds: ["n5"],
        notes: ["Analgesia, hygiene advice, and review interval stated."],
      },
    ],
    assessorSummary: "Likely Grade B: reply documents dry socket management and analgesia plan.",
  }),
  buildSample({
    id: "sample-dent-nz-wave3-c",
    scenarioId: "w-dent-nz-wave3",
    profession: "dentistry",
    title: "Weak example — dry socket reply (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 108,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Hi Dr Williams,\n\nMs Thompson had tooth out. Still sore.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Referral not properly acknowledged; extraction site not specified."],
      },
      {
        label: "Body (weak)",
        text: "Socket looks bad. Put dressing in. She teaches kids.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Irrigation and analgesia omitted.", "Irrelevant occupation included."],
      },
      {
        label: "Closing (weak)",
        text: "See her again soon.\n\nThanks",
        sourceNoteIds: [],
        notes: ["No review interval or re-referral criteria."],
      },
    ],
    assessorSummary: "Likely Grade C: fails to document treatment plan and follow-up for GP.",
  }),
  // dentistry — CA
  buildSample({
    id: "sample-dent-ca-wave3-b",
    scenarioId: "w-dent-ca-wave3",
    profession: "dentistry",
    title: "Referral — paediatric dental avulsion",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 182,
    paragraphs: [
      {
        label: "Urgent referral",
        text: "Dear Dr Tremblay,\n\nRe: Liam Dubois, aged 9 years\n\nI am writing to refer Liam urgently following traumatic avulsion of his maxillary central incisor at hockey practice approximately 45 minutes ago.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Injury mechanism and time since avulsion stated."],
      },
      {
        label: "Emergency management",
        text: "The tooth was stored in Hank's solution en route, reimplanted, and splinted with composite wire. His tetanus status is up to date and a lip laceration was sutured in the emergency department.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Storage medium, splinting, and soft tissue injuries documented."],
      },
      {
        label: "Request",
        text: "I would be grateful if you could review Liam within 24 hours for pulp extirpation planning and splint review.\n\nYours sincerely,\n[Dentist name]",
        sourceNoteIds: ["n5"],
        notes: ["Specialist endodontic review requested within timeframe."],
      },
    ],
    assessorSummary: "Likely Grade B: urgent paediatric referral after avulsion with splinting summary.",
  }),
  buildSample({
    id: "sample-dent-ca-wave3-c",
    scenarioId: "w-dent-ca-wave3",
    profession: "dentistry",
    title: "Weak example — paediatric avulsion referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 102,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Specialist,\n\nBoy knocked tooth out at sport.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Patient unnamed; paediatric dentist not addressed."],
      },
      {
        label: "Body (weak)",
        text: "Tooth put back. Dad is coach. Lip cut fixed.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Storage medium and time since avulsion missing.", "Irrelevant family detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Please see when you can.",
        sourceNoteIds: [],
        notes: ["No urgent endodontic review requested."],
      },
    ],
    assessorSummary: "Likely Grade C: referral lacks splinting detail and specialist request.",
  }),
  // physiotherapy — AU
  buildSample({
    id: "sample-phys-au-wave3-b",
    scenarioId: "w-phys-au-wave3",
    profession: "physiotherapy",
    title: "Reply — total knee replacement prehab plan",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 186,
    paragraphs: [
      {
        label: "Opening",
        text: "Dear Dr Chen,\n\nRe: Mr Harpreet Singh, aged 67 years\n\nThank you for referring Mr Singh for pre-operative physiotherapy ahead of his elective total knee replacement scheduled for 22 July 2026.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Referral and surgical timeline acknowledged."],
      },
      {
        label: "Assessment & programme",
        text: "He has severe medial compartment osteoarthritis. Knee flexion is 105 degrees, quadriceps strength 3+/5, and he walks 200 metres with a stick. A prehab programme of quadriceps sets, heel slides, and stationary cycling for 10 minutes daily has been commenced.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Strength, range, and exercise programme documented."],
      },
      {
        label: "Pathway",
        text: "Post-operative physiotherapy referral has been arranged. I will review him in pre-operative week five.\n\nYours sincerely,\n[Physiotherapist name]",
        sourceNoteIds: ["n5"],
        notes: ["Post-op pathway and review timing stated."],
      },
    ],
    assessorSummary: "Likely Grade B: reply with TKR prehab plan and post-operative pathway.",
  }),
  buildSample({
    id: "sample-phys-au-wave3-c",
    scenarioId: "w-phys-au-wave3",
    profession: "physiotherapy",
    title: "Weak example — TKR prehab reply (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 110,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Hi Dr Chen,\n\nMr Singh came for physio before knee op.",
        sourceNoteIds: ["n1"],
        notes: ["Surgical date not stated; referral not properly acknowledged."],
      },
      {
        label: "Body (weak)",
        text: "Knee stiff. Did some exercises. Retired accountant.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Objective measures missing.", "Irrelevant employment history included."],
      },
      {
        label: "Closing (weak)",
        text: "Cheers",
        sourceNoteIds: [],
        notes: ["Post-operative pathway and review not documented."],
      },
    ],
    assessorSummary: "Likely Grade C: prehab programme and surgical pathway not communicated.",
  }),
  // physiotherapy — CA
  buildSample({
    id: "sample-phys-ca-wave3-b",
    scenarioId: "w-phys-ca-wave3",
    profession: "physiotherapy",
    title: "Advice — vestibular hypofunction rehabilitation",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 191,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Tremblay,\n\nRe: Mrs Marie Lavoie, aged 58 years\n\nI am writing to summarise Mrs Lavoie's progress in vestibular rehabilitation, now in week three, following vestibular neuritis eight weeks ago.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Onset, duration, and current symptom pattern stated."],
      },
      {
        label: "Assessment & treatment",
        text: "She reports ongoing imbalance on head turn. Assessment showed a positive head impulse test on the left and reduced dynamic visual acuity. Her gaze-stability and balance retraining programme has been progressed.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Vestibular findings and exercise programme documented."],
      },
      {
        label: "Recommendation",
        text: "If vertigo continues to limit exercises, I would appreciate your review of betahistine. I will continue weekly rehabilitation.\n\nYours sincerely,\n[Physiotherapist name]",
        sourceNoteIds: ["n5"],
        notes: ["Medication review request stated appropriately."],
      },
    ],
    assessorSummary: "Likely Grade B: advises GP on vestibular rehab progress and medication review.",
  }),
  buildSample({
    id: "sample-phys-ca-wave3-c",
    scenarioId: "w-phys-ca-wave3",
    profession: "physiotherapy",
    title: "Weak example — vestibular rehab advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 105,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMrs Lavoie dizzy after ear infection.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Advice letter purpose unclear; duration not stated."],
      },
      {
        label: "Body (weak)",
        text: "Balance not great. Did exercises. Likes skiing.",
        sourceNoteIds: ["n4", "n6"],
        notes: ["Vestibular assessment findings omitted.", "Irrelevant hobby included."],
      },
      {
        label: "Closing (weak)",
        text: "Hope she improves.",
        sourceNoteIds: [],
        notes: ["No medication review request for persistent nausea."],
      },
    ],
    assessorSummary: "Likely Grade C: vestibular findings and GP action not communicated.",
  }),
  // occupational therapy — UK
  buildSample({
    id: "sample-ot-uk-wave3-b",
    scenarioId: "w-ot-uk-wave3",
    profession: "occupational_therapy",
    title: "Reply — rheumatoid arthritis hand splinting",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 184,
    paragraphs: [
      {
        label: "Opening",
        text: "Dear Dr Patel,\n\nRe: Ms Amara Okonkwo, aged 52 years\n\nThank you for referring Ms Okonkwo for occupational therapy assessment of hand pain and functional limits related to rheumatoid arthritis.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Referral acknowledged; functional concerns stated."],
      },
      {
        label: "Intervention",
        text: "Assessment showed ulnar drift at the metacarpophalangeal joints with painful grip and difficulty opening jars. A resting hand splint has been fitted for night use. Joint protection education was provided and ergonomic kitchen aids were supplied.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Joint assessment, splint, and training documented."],
      },
      {
        label: "Recommendation",
        text: "Please refer to rheumatology if morning stiffness exceeds 60 minutes despite disease-modifying therapy.\n\nYours sincerely,\n[Occupational therapist name]",
        sourceNoteIds: ["n5"],
        notes: ["Rheumatology review criteria stated."],
      },
    ],
    assessorSummary: "Likely Grade B: reply documenting RA hand splinting and functional training.",
  }),
  buildSample({
    id: "sample-ot-uk-wave3-c",
    scenarioId: "w-ot-uk-wave3",
    profession: "occupational_therapy",
    title: "Weak example — RA hand OT reply (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 112,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Dr Patel,\n\nMs Okonkwo has sore hands.",
        sourceNoteIds: ["n1"],
        notes: ["Referral not acknowledged; RA context missing."],
      },
      {
        label: "Body (weak)",
        text: "Gave splint. Kitchen stuff. Works in hospital.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Joint assessment incomplete.", "Irrelevant employment included."],
      },
      {
        label: "Closing (weak)",
        text: "Thanks",
        sourceNoteIds: [],
        notes: ["No rheumatology review recommendation."],
      },
    ],
    assessorSummary: "Likely Grade C: splinting and joint protection not adequately documented.",
  }),
  // occupational therapy — NZ
  buildSample({
    id: "sample-ot-nz-wave3-b",
    scenarioId: "w-ot-nz-wave3",
    profession: "occupational_therapy",
    title: "Advice — traumatic brain injury cognitive rehab",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 194,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Williams,\n\nRe: Mr James Harrison, aged 34 years\n\nI am writing to summarise cognitive rehabilitation for Mr Harrison, eight weeks after a moderate traumatic brain injury sustained in a motor vehicle accident.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Injury context and cognitive complaints stated."],
      },
      {
        label: "Assessment & strategies",
        text: "He reports memory lapses and fatigue. MoCA score is 22/30. Compensatory strategies including a pacing diary and smartphone reminders have been introduced.",
        sourceNoteIds: ["n2", "n3"],
        notes: ["Assessment findings and compensatory strategies documented."],
      },
      {
        label: "Return to activity",
        text: "A graded return to desk work for three hours daily has commenced. Driving remains deferred until occupational therapy clearance. Please review sleep and mood if fatigue persists.\n\nYours sincerely,\n[Occupational therapist name]",
        sourceNoteIds: ["n4", "n5"],
        notes: ["Return-to-work and driving plan clear.", "GP review of mood recommended."],
      },
    ],
    assessorSummary: "Likely Grade B: advises GP on TBI cognitive rehab and return-to-activity plan.",
  }),
  buildSample({
    id: "sample-ot-nz-wave3-c",
    scenarioId: "w-ot-nz-wave3",
    profession: "occupational_therapy",
    title: "Weak example — TBI cognitive rehab advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 115,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMr Harrison had head injury in crash.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Advice purpose vague; week-eight context missing."],
      },
      {
        label: "Body (weak)",
        text: "Memory bad. Uses phone reminders. Partner helps at home.",
        sourceNoteIds: ["n3", "n6"],
        notes: ["MoCA score omitted.", "Irrelevant support person detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Back at work a bit.",
        sourceNoteIds: [],
        notes: ["Driving restrictions and GP mood review not stated."],
      },
    ],
    assessorSummary: "Likely Grade C: cognitive assessment and return-to-activity plan incomplete.",
  }),
  // podiatry — AU
  buildSample({
    id: "sample-pod-au-wave3-b",
    scenarioId: "w-pod-au-wave3",
    profession: "podiatry",
    title: "Reply — Achilles tendinopathy loading plan",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 172,
    paragraphs: [
      {
        label: "Opening",
        text: "Dear Dr Chen,\n\nRe: Mr Sean O'Connor, aged 39 years\n\nThank you for referring Mr O'Connor with mid-portion Achilles tendinopathy of 10 weeks' duration affecting his running training.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Referral acknowledged; symptom duration stated."],
      },
      {
        label: "Examination & programme",
        text: "Examination showed mid-portion tenderness with a painful hop test and no signs of calf tear. An Alfredson eccentric programme has been commenced with modified heel drops. Running is paused and cross-training on a bicycle is permitted.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Examination and loading programme documented."],
      },
      {
        label: "Plan",
        text: "I will review him in six weeks and arrange ultrasound if there is no progress.\n\nYours sincerely,\n[Podiatrist name]",
        sourceNoteIds: ["n5"],
        notes: ["Review timeline and imaging criteria stated."],
      },
    ],
    assessorSummary: "Likely Grade B: reply with Achilles tendinopathy loading programme.",
  }),
  buildSample({
    id: "sample-pod-au-wave3-c",
    scenarioId: "w-pod-au-wave3",
    profession: "podiatry",
    title: "Weak example — Achilles tendinopathy reply (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 100,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Hi,\n\nMr O'Connor has sore Achilles.",
        sourceNoteIds: ["n1"],
        notes: ["Referrer not named; referral not acknowledged."],
      },
      {
        label: "Body (weak)",
        text: "Heel drops started. Training for half-marathon.",
        sourceNoteIds: ["n3", "n6"],
        notes: ["Examination findings missing.", "Irrelevant training goal included."],
      },
      {
        label: "Closing (weak)",
        text: "See him later.",
        sourceNoteIds: [],
        notes: ["Review interval and imaging criteria absent."],
      },
    ],
    assessorSummary: "Likely Grade C: loading capacity and follow-up plan not communicated.",
  }),
  // podiatry — NZ
  buildSample({
    id: "sample-pod-nz-wave3-b",
    scenarioId: "w-pod-nz-wave3",
    profession: "podiatry",
    title: "Advice — refractory onychomycosis treatment",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 174,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Williams,\n\nRe: Ms Hine Rangi, aged 61 years\n\nI am writing regarding podiatric management of Ms Rangi's long-standing toenail fungal infection, unresponsive to topical therapy for two years.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Duration and prior treatment failure stated."],
      },
      {
        label: "Findings & plan",
        text: "Hallux nails are dystrophic. A nail clipping has been sent for PAS stain with KOH results pending. Monthly podiatric debridement is planned.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Nail appearance and mycology documented.", "Debridement plan stated."],
      },
      {
        label: "Request",
        text: "We discussed oral terbinafine and I would be grateful if you could prescribe this should liver function tests be acceptable.\n\nYours sincerely,\n[Podiatrist name]",
        sourceNoteIds: ["n5"],
        notes: ["Systemic therapy discussion and GP prescription request clear."],
      },
    ],
    assessorSummary: "Likely Grade B: advises GP on refractory onychomycosis and systemic therapy request.",
  }),
  buildSample({
    id: "sample-pod-nz-wave3-c",
    scenarioId: "w-pod-nz-wave3",
    profession: "podiatry",
    title: "Weak example — onychomycosis advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 98,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Dr Williams,\n\nPatient has fungal nails.",
        sourceNoteIds: ["n1"],
        notes: ["Patient unnamed; duration and prior treatments not stated."],
      },
      {
        label: "Body (weak)",
        text: "Cream didn't work. Does kapa haka.",
        sourceNoteIds: ["n2", "n6"],
        notes: ["Mycology and debridement plan omitted.", "Irrelevant hobby included."],
      },
      {
        label: "Closing (weak)",
        text: "Maybe needs tablets.",
        sourceNoteIds: [],
        notes: ["No formal prescription request or LFT caveat."],
      },
    ],
    assessorSummary: "Likely Grade C: systemic therapy request not properly documented.",
  }),
  // podiatry — CA
  buildSample({
    id: "sample-pod-ca-wave3-b",
    scenarioId: "w-pod-ca-wave3",
    profession: "podiatry",
    title: "Referral — Charcot foot offloading",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 186,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Tremblay,\n\nRe: Mr Pierre Bouchard, aged 64 years\n\nI am writing to request coordinated management for Mr Bouchard, who has type 2 diabetes and suspected Charcot neuroarthropathy of the midfoot.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Suspicion basis and diabetes context stated."],
      },
      {
        label: "Findings & management",
        text: "Examination shows a warm swollen midfoot with developing rocker-bottom deformity. He has loss of protective sensation and HbA1c was 9.2% last month. A total contact cast has been applied with non-weight-bearing for six weeks.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Temperature, deformity, sensation, and offloading documented."],
      },
      {
        label: "Request",
        text: "I would appreciate urgent glycaemic optimisation and endocrine referral to support offloading.\n\nYours sincerely,\n[Podiatrist name]",
        sourceNoteIds: ["n5"],
        notes: ["GP glycaemic review and endocrine co-management requested."],
      },
    ],
    assessorSummary: "Likely Grade B: referral-style letter requesting GP co-management of Charcot foot.",
  }),
  buildSample({
    id: "sample-pod-ca-wave3-c",
    scenarioId: "w-pod-ca-wave3",
    profession: "podiatry",
    title: "Weak example — Charcot foot referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 104,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear GP,\n\nDiabetic patient foot swollen.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Patient unnamed; Charcot suspicion not stated."],
      },
      {
        label: "Body (weak)",
        text: "Cast on foot. Sugar high. Retired carpenter.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Sensation and deformity findings missing.", "Irrelevant occupation included."],
      },
      {
        label: "Closing (weak)",
        text: "Please help with diabetes.",
        sourceNoteIds: [],
        notes: ["No endocrine referral or glycaemic optimisation request."],
      },
    ],
    assessorSummary: "Likely Grade C: Charcot findings and co-management request incomplete.",
  }),
  // optometry — UK
  buildSample({
    id: "sample-opt-uk-wave3-b",
    scenarioId: "w-opt-uk-wave3",
    profession: "optometry",
    title: "Referral — acute posterior vitreous detachment",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 181,
    paragraphs: [
      {
        label: "Urgent referral",
        text: "Dear Dr Patel,\n\nRe: Mrs Grace Adebayo, aged 58 years\n\nI am writing to refer Mrs Adebayo for same-week ophthalmology review following acute onset of floaters and flashes in the right eye yesterday.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Acute symptom onset and visual disturbance stated."],
      },
      {
        label: "Examination",
        text: "Visual acuity is 6/6 in both eyes. Dilated examination confirmed posterior vitreous detachment with no retinal tear seen today. Peripheral retina examination noted lattice degeneration.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Dilated findings and lattice degeneration documented."],
      },
      {
        label: "Request",
        text: "I would be grateful for urgent retinal assessment within one week. Mrs Adebayo has been warned to attend immediately if she experiences curtain-like vision loss.\n\nYours sincerely,\n[Optometrist name]",
        sourceNoteIds: ["n5"],
        notes: ["Urgent assessment requested with safety-netting advice."],
      },
    ],
    assessorSummary: "Likely Grade B: urgent referral for PVD with lattice degeneration monitoring.",
  }),
  buildSample({
    id: "sample-opt-uk-wave3-c",
    scenarioId: "w-opt-uk-wave3",
    profession: "optometry",
    title: "Weak example — PVD referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 96,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Eye Doctor,\n\nMrs Adebayo sees floaters.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Ophthalmologist not named; urgency not stated."],
      },
      {
        label: "Body (weak)",
        text: "Eye test OK. Drives for nursing visits.",
        sourceNoteIds: ["n3", "n6"],
        notes: ["PVD findings and lattice degeneration omitted.", "Irrelevant driving detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Please check retina.",
        sourceNoteIds: [],
        notes: ["No same-week assessment request or warning signs documented."],
      },
    ],
    assessorSummary: "Likely Grade C: insufficient examination detail for urgent retinal referral.",
  }),
  // optometry — CA
  buildSample({
    id: "sample-opt-ca-wave3-b",
    scenarioId: "w-opt-ca-wave3",
    profession: "optometry",
    title: "Advice — ocular hypertension monitoring plan",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 176,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Tremblay,\n\nRe: Mr Louis Gagnon, aged 55 years\n\nI am writing to outline monitoring and treatment for Mr Gagnon, who has ocular hypertension with a family history of glaucoma.",
        sourceNoteIds: ["n1", "n4"],
        notes: ["Examination context and family history stated."],
      },
      {
        label: "Findings & treatment",
        text: "Intraocular pressure was 26 mmHg in both eyes with average corneal thickness. Optic discs appear healthy and visual fields were full today. Latanoprost to both eyes at night has been commenced.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["IOP, disc, and field status documented.", "Drop initiation stated."],
      },
      {
        label: "Follow-up",
        text: "Review is scheduled in six weeks. Please be aware of potential systemic beta-blocker interactions if prescribing cardiovascular medication. He should contact us for red eye or vision change.\n\nYours sincerely,\n[Optometrist name]",
        sourceNoteIds: ["n5"],
        notes: ["Follow-up interval and GP awareness of interactions stated."],
      },
    ],
    assessorSummary: "Likely Grade B: advises GP on ocular hypertension treatment and monitoring.",
  }),
  buildSample({
    id: "sample-opt-ca-wave3-c",
    scenarioId: "w-opt-ca-wave3",
    profession: "optometry",
    title: "Weak example — ocular hypertension advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 102,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMr Gagnon eye pressure high.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Advice purpose unclear; IOP values not given."],
      },
      {
        label: "Body (weak)",
        text: "Started drops. Works night shifts.",
        sourceNoteIds: ["n4", "n6"],
        notes: ["Optic nerve and visual field status omitted.", "Irrelevant work detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Review later.",
        sourceNoteIds: [],
        notes: ["No follow-up interval or beta-blocker interaction warning."],
      },
    ],
    assessorSummary: "Likely Grade C: monitoring plan and GP awareness not communicated.",
  }),
  // dietetics — NZ
  buildSample({
    id: "sample-diet-nz-wave3-b",
    scenarioId: "w-diet-nz-wave3",
    profession: "dietetics",
    title: "Advice — heart failure sodium restriction plan",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 174,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Williams,\n\nRe: Mr Robert Wallace, aged 71 years\n\nI am writing to summarise dietary counselling for Mr Wallace following admission with newly decompensated heart failure and fluid overload.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Admission context and weight trend stated."],
      },
      {
        label: "Education",
        text: "His weight increased by 3 kg over two weeks. Sodium restriction to 1500 mg per day and fluid limit of 1.5 litres per day were explained. Practical strategies included a low-salt cooking handout and advice to avoid processed meats and soups.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Sodium and fluid restriction education documented.", "Meal strategies included."],
      },
      {
        label: "Follow-up",
        text: "Dietetic review is arranged three weeks post-discharge. A daily weights chart has been supplied.\n\nYours sincerely,\n[Dietitian name]",
        sourceNoteIds: ["n5"],
        notes: ["Review timing and self-monitoring tools stated."],
      },
    ],
    assessorSummary: "Likely Grade B: advice letter on heart failure sodium and fluid restriction.",
  }),
  buildSample({
    id: "sample-diet-nz-wave3-c",
    scenarioId: "w-diet-nz-wave3",
    profession: "dietetics",
    title: "Weak example — heart failure diet advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 100,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Dr Williams,\n\nMr Wallace has heart failure.",
        sourceNoteIds: ["n1"],
        notes: ["Admission context and weight trend not stated."],
      },
      {
        label: "Body (weak)",
        text: "Told him less salt. Wife does shopping.",
        sourceNoteIds: ["n4", "n6"],
        notes: ["Sodium and fluid limits not quantified.", "Irrelevant family detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Hope this helps.",
        sourceNoteIds: [],
        notes: ["No dietetic review arranged post-discharge."],
      },
    ],
    assessorSummary: "Likely Grade C: dietary plan not documented for GP continuity.",
  }),
  // dietetics — CA
  buildSample({
    id: "sample-diet-ca-wave3-b",
    scenarioId: "w-diet-ca-wave3",
    profession: "dietetics",
    title: "Advice — Crohn's disease flare nutrition",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 179,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Tremblay,\n\nRe: Ms Sophie Roy, aged 29 years\n\nI am writing to outline nutritional support for Ms Roy during a moderate Crohn's disease flare with reduced oral intake over the past two weeks.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Disease activity and symptom duration stated."],
      },
      {
        label: "Assessment & plan",
        text: "She reports increased stool frequency and abdominal cramping. Weight is down 2 kg with poor appetite and avoidance of high-fibre foods. A low-residue, high-protein small-meal plan with oral supplement twice daily has been commenced.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Weight change and dietary modifications documented."],
      },
      {
        label: "Recommendation",
        text: "Iron and vitamin D should be monitored. Please review if weight loss exceeds 3% of body weight.\n\nYours sincerely,\n[Dietitian name]",
        sourceNoteIds: ["n5"],
        notes: ["Micronutrient concerns and GP review criteria stated."],
      },
    ],
    assessorSummary: "Likely Grade B: summarises Crohn's flare nutrition support for GP.",
  }),
  buildSample({
    id: "sample-diet-ca-wave3-c",
    scenarioId: "w-diet-ca-wave3",
    profession: "dietetics",
    title: "Weak example — Crohn's flare nutrition advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 105,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMs Roy has Crohn's flare.",
        sourceNoteIds: ["n1"],
        notes: ["Symptom pattern and weight change not stated."],
      },
      {
        label: "Body (weak)",
        text: "Eating less. Supplements given. Graduate student.",
        sourceNoteIds: ["n4", "n6"],
        notes: ["Low-residue plan not described.", "Irrelevant occupation included."],
      },
      {
        label: "Closing (weak)",
        text: "Monitor weight.",
        sourceNoteIds: [],
        notes: ["No micronutrient monitoring or GP review threshold."],
      },
    ],
    assessorSummary: "Likely Grade C: nutritional plan and re-referral criteria incomplete.",
  }),
  // radiography — IE
  buildSample({
    id: "sample-rad-ie-wave3-b",
    scenarioId: "w-rad-ie-wave3",
    profession: "radiography",
    title: "Reply — abdominal ultrasound gallstones report",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 171,
    paragraphs: [
      {
        label: "Examination",
        text: "Dear Dr O'Brien,\n\nRe: Mrs Niamh Keane, aged 47 years\n\nI am writing with abdominal ultrasound findings for Mrs Keane, investigated for recurrent right upper quadrant pain on 9 June 2026.",
        sourceNoteIds: ["n1"],
        notes: ["Examination performed and clinical indication stated."],
      },
      {
        label: "Findings",
        text: "Multiple gallstones are present with normal gallbladder wall thickness. The common bile duct measures 4 mm with no intrahepatic dilatation. Liver echotexture is normal and the pancreas was obscured by bowel gas.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Gallbladder, bile duct, liver, and pancreatic appearances documented."],
      },
      {
        label: "Recommendation",
        text: "Please correlate with liver function tests and consider surgical referral if pain recurs despite dietary modification.\n\nYours sincerely,\n[Radiographer name]",
        sourceNoteIds: ["n5"],
        notes: ["LFT correlation and surgical referral criteria stated."],
      },
    ],
    assessorSummary: "Likely Grade B: communicates gallstone ultrasound findings to GP.",
  }),
  buildSample({
    id: "sample-rad-ie-wave3-c",
    scenarioId: "w-rad-ie-wave3",
    profession: "radiography",
    title: "Weak example — gallstone ultrasound report (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 92,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear GP,\n\nUltrasound done for tummy pain.",
        sourceNoteIds: ["n1"],
        notes: ["Patient unnamed; clinical indication vague."],
      },
      {
        label: "Body (weak)",
        text: "Gallstones seen. Liver OK. Non-smoker.",
        sourceNoteIds: ["n2", "n4", "n6"],
        notes: ["Bile duct measurements omitted.", "Irrelevant smoking status included."],
      },
      {
        label: "Closing (weak)",
        text: "Thanks",
        sourceNoteIds: [],
        notes: ["No LFT correlation or surgical referral recommendation."],
      },
    ],
    assessorSummary: "Likely Grade C: ultrasound findings communicated without actionable follow-up.",
  }),
  // radiography — NZ
  buildSample({
    id: "sample-rad-nz-wave3-b",
    scenarioId: "w-rad-nz-wave3",
    profession: "radiography",
    title: "Reply — CT head stroke exclusion report",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 172,
    paragraphs: [
      {
        label: "Examination",
        text: "Dear Dr Williams,\n\nRe: Mr Hiro Tanaka, aged 68 years\n\nI am writing with non-contrast CT head findings for Mr Tanaka, assessed in the emergency department on 16 June 2026 for sudden left arm weakness two hours ago with a positive FAST screen.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Examination and clinical indication stated."],
      },
      {
        label: "Findings",
        text: "There is no acute intracranial haemorrhage or established infarct. Chronic small vessel ischaemic changes and age-related atrophy are noted.",
        sourceNoteIds: ["n3", "n4"],
        notes: ["Haemorrhage/infarct status and incidental findings documented."],
      },
      {
        label: "Recommendation",
        text: "MRI brain is recommended per the stroke team pathway and neurology has been notified.\n\nYours sincerely,\n[Radiographer name]",
        sourceNoteIds: ["n5"],
        notes: ["Urgent neurology follow-up per stroke pathway stated."],
      },
    ],
    assessorSummary: "Likely Grade B: communicates negative CT head with stroke pathway recommendation.",
  }),
  buildSample({
    id: "sample-rad-nz-wave3-c",
    scenarioId: "w-rad-nz-wave3",
    profession: "radiography",
    title: "Weak example — CT head stroke report (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 95,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nCT head done for stroke.",
        sourceNoteIds: ["n1"],
        notes: ["Patient unnamed; onset and FAST status missing."],
      },
      {
        label: "Body (weak)",
        text: "No bleed. Some old changes. Lives in Christchurch.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Infarct exclusion not clearly stated.", "Irrelevant address detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Follow up locally.",
        sourceNoteIds: [],
        notes: ["No MRI or neurology pathway recommendation."],
      },
    ],
    assessorSummary: "Likely Grade C: stroke pathway recommendation not communicated.",
  }),
  // radiography — CA
  buildSample({
    id: "sample-rad-ca-wave3-b",
    scenarioId: "w-rad-ca-wave3",
    profession: "radiography",
    title: "Reply — screening mammography recall report",
    letterType: "reply",
    estimatedOverall: "B",
    wordCount: 176,
    paragraphs: [
      {
        label: "Examination",
        text: "Dear Dr Tremblay,\n\nRe: Ms Isabelle Fortin, aged 54 years\n\nI am writing regarding screening mammography performed on 12 June 2026 for Ms Fortin.",
        sourceNoteIds: ["n1"],
        notes: ["Examination type and screening context stated."],
      },
      {
        label: "Findings",
        text: "A focal asymmetry is present in the left upper outer quadrant, categorised as BI-RADS 0 — incomplete. Diagnostic mammography and ultrasound are required. No palpable lump was found on clinical correlation today.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Mammographic finding and BI-RADS category documented."],
      },
      {
        label: "Plan",
        text: "A recall appointment has been booked and Ms Fortin was counselled regarding likely benign causes and associated anxiety.\n\nYours sincerely,\n[Radiographer name]",
        sourceNoteIds: ["n5"],
        notes: ["Diagnostic work-up and patient notification documented."],
      },
    ],
    assessorSummary: "Likely Grade B: informs GP of mammography recall and diagnostic work-up.",
  }),
  buildSample({
    id: "sample-rad-ca-wave3-c",
    scenarioId: "w-rad-ca-wave3",
    profession: "radiography",
    title: "Weak example — mammography recall report (Grade C)",
    letterType: "reply",
    estimatedOverall: "C",
    wordCount: 98,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear GP,\n\nMammogram done. Something on left breast.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Patient unnamed; BI-RADS category missing."],
      },
      {
        label: "Body (weak)",
        text: "Mother had breast cancer. Needs more tests maybe.",
        sourceNoteIds: ["n6"],
        notes: ["Family history irrelevant to report.", "Diagnostic work-up not outlined."],
      },
      {
        label: "Closing (weak)",
        text: "Patient worried.",
        sourceNoteIds: [],
        notes: ["Recall appointment and counselling not documented."],
      },
    ],
    assessorSummary: "Likely Grade C: recall findings and follow-up plan insufficient for GP.",
  }),
  // speech pathology — AU
  buildSample({
    id: "sample-sp-au-wave3-b",
    scenarioId: "w-sp-au-wave3",
    profession: "speech_pathology",
    title: "Advice — post-stroke aphasia therapy update",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 184,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Chen,\n\nRe: Mr Nikos Papadopoulos, aged 66 years\n\nI am writing to summarise speech pathology progress for Mr Papadopoulos, four weeks after ischaemic stroke with expressive aphasia.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Stroke timeline and communication deficits stated."],
      },
      {
        label: "Therapy",
        text: "He has non-fluent aphasia with word-finding difficulty and fair comprehension. Script training and semantic feature analysis have been commenced. His wife received training in supported conversation techniques.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Therapy goals and carer training documented."],
      },
      {
        label: "Recommendation",
        text: "Please screen for depression given the communication impact. Speech pathology review is scheduled in six weeks.\n\nYours sincerely,\n[Speech pathologist name]",
        sourceNoteIds: ["n5"],
        notes: ["GP mood review and follow-up interval stated."],
      },
    ],
    assessorSummary: "Likely Grade B: updates GP on post-stroke aphasia rehabilitation progress.",
  }),
  buildSample({
    id: "sample-sp-au-wave3-c",
    scenarioId: "w-sp-au-wave3",
    profession: "speech_pathology",
    title: "Weak example — aphasia therapy advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 108,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMr Papadopoulos had stroke. Speech bad.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Timeline vague; communication profile incomplete."],
      },
      {
        label: "Body (weak)",
        text: "Doing speech exercises. Retired restaurateur.",
        sourceNoteIds: ["n3", "n6"],
        notes: ["Carer training omitted.", "Irrelevant occupation included."],
      },
      {
        label: "Closing (weak)",
        text: "See him again later.",
        sourceNoteIds: [],
        notes: ["No depression screening recommendation."],
      },
    ],
    assessorSummary: "Likely Grade C: therapy strategies and GP recommendations not communicated.",
  }),
  // speech pathology — NZ
  buildSample({
    id: "sample-sp-nz-wave3-b",
    scenarioId: "w-sp-nz-wave3",
    profession: "speech_pathology",
    title: "Advice — Parkinson's hypophonic dysarthria plan",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 181,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Williams,\n\nRe: Mrs Fiona McKenzie, aged 72 years\n\nI am writing regarding speech pathology management of Mrs McKenzie, who has Parkinson's disease of six years' duration with declining speech clarity.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Diagnosis duration and communication concerns stated."],
      },
      {
        label: "Assessment & programme",
        text: "Her family reports soft, mumbling speech. Assessment showed reduced vocal loudness, monotone prosody, and fair intelligibility. An LSVT LOUD programme of four sessions per week for four weeks is planned with home practice.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Voice and speech findings documented.", "LSVT LOUD plan stated."],
      },
      {
        label: "Recommendation",
        text: "Please review levodopa timing if her voice is worse before doses.\n\nYours sincerely,\n[Speech pathologist name]",
        sourceNoteIds: ["n5"],
        notes: ["Medication timing review recommendation clear."],
      },
    ],
    assessorSummary: "Likely Grade B: advises GP on Parkinson's dysarthria therapy and medication timing.",
  }),
  buildSample({
    id: "sample-sp-nz-wave3-c",
    scenarioId: "w-sp-nz-wave3",
    profession: "speech_pathology",
    title: "Weak example — Parkinson's dysarthria advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 102,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Dr Williams,\n\nMrs McKenzie talks quietly.",
        sourceNoteIds: ["n1"],
        notes: ["Parkinson's context and duration not stated."],
      },
      {
        label: "Body (weak)",
        text: "Voice therapy planned. In garden club.",
        sourceNoteIds: ["n4", "n6"],
        notes: ["Assessment findings missing.", "Irrelevant social detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Thanks",
        sourceNoteIds: [],
        notes: ["No levodopa timing review recommendation."],
      },
    ],
    assessorSummary: "Likely Grade C: dysarthria assessment and medication advice incomplete.",
  }),
  // speech pathology — CA
  buildSample({
    id: "sample-sp-ca-wave3-b",
    scenarioId: "w-sp-ca-wave3",
    profession: "speech_pathology",
    title: "Advice — tracheostomy speaking valve trial",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 186,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Tremblay,\n\nRe: Mr Jean Leclerc, aged 58 years\n\nI am writing to summarise speech pathology input for Mr Leclerc, three weeks post tracheostomy following prolonged ventilation for pneumonia.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Tracheostomy indication and respiratory status stated."],
      },
      {
        label: "Assessment & trial",
        text: "The cuff was deflated today. Fibreoptic endoscopic evaluation of swallowing showed silent aspiration with thin fluids; thickened fluids are safe. A Passy-Muir speaking valve was tolerated for two hours with weak voicing achieved. Carer training in valve management was provided.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Swallow and voicing assessment documented.", "Speaking valve trial and carer training stated."],
      },
      {
        label: "Safety flags",
        text: "Please arrange urgent ENT or respiratory review if desaturation, respiratory distress, or inability to clear secretions occurs.\n\nYours sincerely,\n[Speech pathologist name]",
        sourceNoteIds: ["n5"],
        notes: ["Red flags for urgent review specified."],
      },
    ],
    assessorSummary: "Likely Grade B: advises GP on tracheostomy speaking valve trial and safety flags.",
  }),
  buildSample({
    id: "sample-sp-ca-wave3-c",
    scenarioId: "w-sp-ca-wave3",
    profession: "speech_pathology",
    title: "Weak example — tracheostomy valve advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 110,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Doctor,\n\nMr Leclerc has tracheostomy.",
        sourceNoteIds: ["n1"],
        notes: ["Indication and respiratory status not stated."],
      },
      {
        label: "Body (weak)",
        text: "Trying speaking valve. Swallow OK-ish. Daughter visits.",
        sourceNoteIds: ["n4", "n6"],
        notes: ["Aspiration findings omitted.", "Irrelevant family detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Watch him closely.",
        sourceNoteIds: [],
        notes: ["Specific red flags for urgent review not documented."],
      },
    ],
    assessorSummary: "Likely Grade C: swallow assessment and safety flags not communicated.",
  }),
  // veterinary science — NZ
  buildSample({
    id: "sample-vet-nz-wave3-b",
    scenarioId: "w-vet-nz-wave3",
    profession: "veterinary_science",
    title: "Advice — feline hyperthyroid treatment plan",
    letterType: "advice",
    estimatedOverall: "B",
    wordCount: 179,
    paragraphs: [
      {
        label: "Purpose",
        text: "Dear Dr Williams,\n\nRe: Coco, 13-year-old domestic shorthair cat, owner Mrs Patel\n\nI am writing to update you on management of Coco, newly diagnosed with hyperthyroidism.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Patient, age, owner, and diagnosis identified."],
      },
      {
        label: "Findings & treatment",
        text: "Thyroid hormone is elevated with weight loss despite good appetite. Methimazole 2.5 mg twice daily has been commenced. Blood pressure is 170 mmHg.",
        sourceNoteIds: ["n2", "n3"],
        notes: ["Thyroid parameters and treatment initiation documented."],
      },
      {
        label: "Monitoring",
        text: "Renal values were within normal limits today. Recheck of T4 and creatinine is planned in three weeks. Radioiodine therapy may be considered if Coco stabilises on medical management.\n\nYours sincerely,\n[Veterinary surgeon name]",
        sourceNoteIds: ["n4", "n5"],
        notes: ["Monitoring schedule and definitive treatment option stated."],
      },
    ],
    assessorSummary: "Likely Grade B: updates referring vet on feline hyperthyroid medical management.",
  }),
  buildSample({
    id: "sample-vet-nz-wave3-c",
    scenarioId: "w-vet-nz-wave3",
    profession: "veterinary_science",
    title: "Weak example — feline hyperthyroid advice (Grade C)",
    letterType: "advice",
    estimatedOverall: "C",
    wordCount: 98,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Colleague,\n\nCat has overactive thyroid.",
        sourceNoteIds: ["n2"],
        notes: ["Patient, owner, and age not identified."],
      },
      {
        label: "Body (weak)",
        text: "Started tablets. Indoor cat only.",
        sourceNoteIds: ["n3", "n6"],
        notes: ["Thyroid values and BP omitted.", "Irrelevant lifestyle detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Recheck soon.",
        sourceNoteIds: [],
        notes: ["Monitoring schedule and radioiodine option not stated."],
      },
    ],
    assessorSummary: "Likely Grade C: hyperthyroid management plan incomplete for referring vet.",
  }),
  // veterinary science — CA
  buildSample({
    id: "sample-vet-ca-wave3-b",
    scenarioId: "w-vet-ca-wave3",
    profession: "veterinary_science",
    title: "Referral — canine cruciate ligament surgical referral",
    letterType: "referral",
    estimatedOverall: "B",
    wordCount: 176,
    paragraphs: [
      {
        label: "Referral",
        text: "Dear Dr Tremblay,\n\nRe: Max, 5-year-old male Rottweiler, owner Mr Gagnon\n\nI am writing to refer Max for orthopaedic surgical assessment of cranial cruciate ligament rupture in the right hind limb.",
        sourceNoteIds: ["n1", "n2"],
        notes: ["Patient, breed, owner, and lameness context identified."],
      },
      {
        label: "Examination",
        text: "Max developed acute right hind limb lameness after park play and is partially weight-bearing. Examination showed positive cranial drawer in the right stifle with palpable medial buttress. Radiographs confirm stifle effusion with positive tibial thrust.",
        sourceNoteIds: ["n2", "n3", "n4"],
        notes: ["Lameness duration, drawer test, and radiograph findings documented."],
      },
      {
        label: "Request",
        text: "Carprofen has been prescribed for pain management. I would be grateful if you could assess Max for TPLO within two weeks.\n\nYours sincerely,\n[Veterinary surgeon name]",
        sourceNoteIds: ["n5"],
        notes: ["Pain management and surgical assessment request stated."],
      },
    ],
    assessorSummary: "Likely Grade B: refers for surgical repair of canine cruciate ligament rupture.",
  }),
  buildSample({
    id: "sample-vet-ca-wave3-c",
    scenarioId: "w-vet-ca-wave3",
    profession: "veterinary_science",
    title: "Weak example — cruciate ligament referral (Grade C)",
    letterType: "referral",
    estimatedOverall: "C",
    wordCount: 100,
    paragraphs: [
      {
        label: "Opening (weak)",
        text: "Dear Surgeon,\n\nDog limping after play.",
        sourceNoteIds: ["n2"],
        notes: ["Patient, breed, and owner not identified."],
      },
      {
        label: "Body (weak)",
        text: "Knee unstable. X-rays taken. Goes to obedience classes.",
        sourceNoteIds: ["n3", "n4", "n6"],
        notes: ["Drawer and tibial thrust findings missing.", "Irrelevant activity detail included."],
      },
      {
        label: "Closing (weak)",
        text: "Needs surgery maybe.",
        sourceNoteIds: [],
        notes: ["No TPLO assessment or pain management documented."],
      },
    ],
    assessorSummary: "Likely Grade C: referral lacks examination detail and surgical request.",
  }),
];
