import type { DiagnosticItem } from "./types";

export const DIAGNOSTIC_ITEMS: DiagnosticItem[] = [
  // Listening — tier 1
  {
    id: "l-1-1",
    skill: "listening",
    tier: 1,
    tag: "listening:part-a-detail",
    listenScript: "Take two tablets at bedtime.",
    prompt: "How many tablets per day?",
    options: ["One", "Two", "Three", "Four"],
    correctIndex: 1,
  },
  {
    id: "l-1-2",
    skill: "listening",
    tier: 1,
    tag: "listening:spelling",
    listenScript: "The drug name is amlodipine.",
    prompt: "Which spelling is correct?",
    options: ["Amlodipene", "Amlodipine", "Amlodiipine", "Amlodapine"],
    correctIndex: 1,
  },
  // Listening — tier 2
  {
    id: "l-2-1",
    skill: "listening",
    tier: 2,
    tag: "listening:part-b-gist",
    listenScript:
      "During nurse handover: the patient has a fluid restriction of one litre per day because of heart failure.",
    prompt: "What is the main concern with this restriction?",
    options: ["Dehydration risk", "Fluid overload", "Kidney stones", "Low sodium diet"],
    correctIndex: 1,
  },
  {
    id: "l-2-2",
    skill: "listening",
    tier: 2,
    tag: "listening:part-a-detail",
    listenScript:
      "The appointment is rescheduled from Tuesday at ten o'clock to Thursday at half past two in the afternoon.",
    prompt: "When is the new appointment?",
    options: ["Tue 2:30 pm", "Thu 2:30 pm", "Thu 10:00 am", "Wed 2:30 pm"],
    correctIndex: 1,
  },
  {
    id: "l-2-3",
    skill: "listening",
    tier: 2,
    tag: "listening:part-c-inference",
    listenScript: "We'll need to monitor his INR more closely now that the warfarin dose has been increased.",
    prompt: "Why should INR be monitored more closely?",
    options: ["New antibiotic added", "Warfarin dose increased", "Patient discharged", "Allergy noted"],
    correctIndex: 1,
  },
  // Listening — tier 3
  {
    id: "l-3-1",
    skill: "listening",
    tier: 3,
    tag: "listening:part-c-inference",
    listenScript:
      "The patient developed a rash two days after starting penicillin. We should stop the penicillin and document a penicillin allergy.",
    prompt: "What should happen next?",
    options: ["Continue penicillin", "Stop penicillin and document allergy", "Increase dose", "Add antihistamine only"],
    correctIndex: 1,
  },
  {
    id: "l-3-2",
    skill: "listening",
    tier: 3,
    tag: "listening:spelling",
    listenScript: "The diagnosis on the chart is hypertension.",
    prompt: "Which spelling is correct?",
    options: ["Hypertenssion", "Hypertention", "Hypertension", "Hipertension"],
    correctIndex: 2,
  },
  // Reading — tier 1
  {
    id: "r-1-1",
    skill: "reading",
    tier: 1,
    tag: "reading:part-a-speed",
    prompt: "Policy excerpt: 'Staff must wash hands before and after patient contact.' When is hand hygiene required?",
    options: ["Before contact only", "After contact only", "Before and after", "Once per shift"],
    correctIndex: 2,
  },
  {
    id: "r-1-2",
    skill: "reading",
    tier: 1,
    tag: "reading:part-b-gist",
    passage:
      "Within 24 hours of hip replacement, patients began seated exercises and short walks with physiotherapy support. Ward staff noted fewer pressure injuries and earlier discharges when mobility started promptly.",
    prompt: "What is this paragraph mainly about?",
    options: [
      "Pain control after surgery",
      "Starting movement early after hip surgery",
      "Planning hospital discharge paperwork",
      "Changing wound dressings",
    ],
    correctIndex: 1,
  },
  // Reading — tier 2
  {
    id: "r-2-1",
    skill: "reading",
    tier: 2,
    tag: "reading:part-a-speed",
    prompt: "Table row: Paracetamol 1g QDS PRN max 4g/24h. Maximum daily dose?",
    options: ["1 g", "2 g", "4 g", "8 g"],
    correctIndex: 2,
  },
  {
    id: "r-2-2",
    skill: "reading",
    tier: 2,
    tag: "reading:part-c-inference",
    prompt: "Text: 'Despite normal HbA1c, patient reports frequent hypoglycaemia episodes.' Best inference?",
    options: ["Diabetes resolved", "Glucose control may need review", "HbA1c test invalid", "Patient non-compliant"],
    correctIndex: 1,
  },
  {
    id: "r-2-3",
    skill: "reading",
    tier: 2,
    tag: "reading:part-a-speed",
    prompt: "Scan for date: 'Clinic letter 14/03/26 — follow-up in 6 weeks.' Follow-up date?",
    options: ["14/03/26", "14/04/26", "26/04/26", "14/09/26"],
    correctIndex: 2,
  },
  // Reading — tier 3
  {
    id: "r-3-1",
    skill: "reading",
    tier: 3,
    tag: "reading:part-c-inference",
    prompt: "Research summary compares two antibiotics; conclusion favours Drug A for fewer side effects. Author's view?",
    options: ["Drugs equal", "Drug A preferred for tolerability", "Drug B safer", "No recommendation"],
    correctIndex: 1,
  },
  {
    id: "r-3-2",
    skill: "reading",
    tier: 3,
    tag: "reading:part-a-speed",
    prompt: "Multiple guidelines listed; only item marked 'mandatory' is incident reporting within 24 hours. Requirement?",
    options: ["Optional", "Mandatory within 24h", "Weekly report", "Verbal only"],
    correctIndex: 1,
  },
  // Writing diagnostic
  {
    id: "w-d-1",
    skill: "writing",
    tier: 2,
    tag: "writing:purpose",
    prompt: "Task: refer patient to GP for BP review. Best opening sentence?",
    options: [
      "I am writing to refer Mr Holt for blood pressure review.",
      "Mr Holt came to the pharmacy yesterday.",
      "Blood pressure is important for health.",
      "Please see the attached notes.",
    ],
    correctIndex: 0,
  },
  {
    id: "w-d-2",
    skill: "writing",
    tier: 2,
    tag: "writing:content-selection",
    prompt: "Case note: 'Childhood asthma — resolved'. Referral for ankle swelling on amlodipine. Include this note?",
    options: ["Yes — always include full history", "No — not relevant to referral purpose", "Yes — in closing paragraph", "Yes — as main focus"],
    correctIndex: 1,
  },
  {
    id: "w-d-3",
    skill: "writing",
    tier: 2,
    tag: "writing:genre",
    prompt: "Formal GP referral letter. Which phrase is appropriate?",
    options: ["The guy feels fine", "The patient reports improvement", "Kids shouldn't smoke", "BP is kinda high"],
    correctIndex: 1,
  },
  {
    id: "w-d-4",
    skill: "writing",
    tier: 2,
    tag: "writing:organisation",
    prompt: "Where should the clear request for action appear?",
    options: ["Only in the subject line", "Early in the letter, after purpose", "Never — implied only", "Only in P.S."],
    correctIndex: 1,
  },
  // Speaking diagnostic
  {
    id: "s-d-1",
    skill: "speaking",
    tier: 2,
    tag: "speaking:ice-expectations",
    prompt: "Patient anxious about new insulin. First step in consultation?",
    options: ["Prescribe immediately", "Elicit ideas and concerns", "End consultation", "Refer to surgeon"],
    correctIndex: 1,
  },
  {
    id: "s-d-2",
    skill: "speaking",
    tier: 2,
    tag: "speaking:structure",
    prompt: "Best structure for explaining a medication change?",
    options: ["Random facts", "Signpost: reason → change → check understanding", "Read package insert", "Avoid questions"],
    correctIndex: 1,
  },
  {
    id: "s-d-3",
    skill: "speaking",
    tier: 2,
    tag: "speaking:clinical-comm",
    prompt: "Patient says 'I won't take it — my friend had side effects.' Response?",
    options: ["Ignore concern", "Acknowledge concern and explain individually", "Argue with patient", "Change topic"],
    correctIndex: 1,
  },
  {
    id: "s-d-4",
    skill: "speaking",
    tier: 2,
    tag: "speaking:language",
    prompt: "Which question checks understanding?",
    options: ["Do you understand?", "Can you tell me how you'll take this each day?", "Are you listening?", "OK?"],
    correctIndex: 1,
  },
];

export function itemsForSkill(skill: DiagnosticItem["skill"]): DiagnosticItem[] {
  return DIAGNOSTIC_ITEMS.filter((item) => item.skill === skill);
}
