import type { QuizQuestion } from "./types";

/** Standalone adaptive quiz pool — complements passage-embedded questions. */
export const QUIZ_BANK: QuizQuestion[] = [
  {
    id: "quiz-r-001",
    skill: "reading",
    part: "B",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["reading:part-b", "reading:skim"],
    prompt: "A memo states ward rounds start 30 minutes earlier. What is the gist?",
    options: [
      "Rounds are cancelled",
      "Morning rounds begin earlier",
      "Only consultants may attend",
      "Patients must leave the ward",
    ],
    correctAnswer: "Morning rounds begin earlier",
    explanation: "Earlier start time is the main point.",
  },
  {
    id: "quiz-r-002",
    skill: "reading",
    part: "A",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["reading:part-a", "reading:scan"],
    prompt: "Which strategy best suits Part A matching tasks?",
    options: [
      "Read every word of each text in order",
      "Scan for keywords from the question",
      "Memorise the first text only",
      "Skip the questions until the end",
    ],
    correctAnswer: "Scan for keywords from the question",
    explanation: "Part A rewards fast scanning across short texts.",
  },
  {
    id: "quiz-r-003",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-c", "reading:inference"],
    prompt: "A report says uptake was ' modest but encouraging'. The writer suggests uptake was…",
    options: [
      "Higher than hoped",
      "Lower than ideal but positive",
      "A complete failure",
      "Unmeasurable",
    ],
    correctAnswer: "Lower than ideal but positive",
    explanation: "'Modest' limits expectation; 'encouraging' is positive.",
  },
  {
    id: "quiz-r-004",
    skill: "reading",
    part: "B",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["reading:part-b", "reading:vocabulary"],
    prompt: "Complete: The policy will be ___ until further notice.",
    options: ["suspended", "celebrated", "exported", "ignored"],
    correctAnswer: "suspended",
    explanation: "Policies are suspended pending review.",
  },
  {
    id: "quiz-r-005",
    skill: "reading",
    part: "A",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-a-speed", "reading:scan"],
    prompt: "You have 15 minutes for Part A. Best approach?",
    options: [
      "Answer questions as you read each matching text",
      "Read all texts fully before looking at questions",
      "Leave Part A blank",
      "Copy one text for every answer",
    ],
    correctAnswer: "Answer questions as you read each matching text",
    explanation: "Work question-by-question to save time.",
  },
  {
    id: "quiz-r-006",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "mcq",
    difficulty: 3,
    tags: ["reading:part-c-inference", "reading:inference"],
    prompt: "The phrase 'not without drawbacks' implies the change…",
    options: [
      "Has no disadvantages",
      "Has some disadvantages",
      "Is illegal",
      "Was rejected",
    ],
    correctAnswer: "Has some disadvantages",
    explanation: "Double negative: drawbacks exist.",
  },
  {
    id: "quiz-r-007",
    skill: "reading",
    part: "B",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-b-gist", "reading:skim"],
    prompt: "Email subject: 'Mandatory training deadline extended'. Main message?",
    options: [
      "Training is optional",
      "Staff have more time to complete training",
      "Training is cancelled",
      "Only managers must train",
    ],
    correctAnswer: "Staff have more time to complete training",
    explanation: "Deadline extension gives more time.",
  },
  {
    id: "quiz-r-008",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-c-inference"],
    prompt: "An author writes 'whether this scales remains to be seen'. They are…",
    options: [
      "Certain of success",
      "Uncertain about wider success",
      "Refusing to evaluate",
      "Reporting proven failure",
    ],
    correctAnswer: "Uncertain about wider success",
    explanation: "'Remains to be seen' signals open outcome.",
  },
  {
    id: "quiz-r-009",
    skill: "reading",
    part: "A",
    profession: "nursing",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-a", "reading:scan"],
    prompt: "Handover note: 'NEWS2 score 7 — medical review requested.' Priority action?",
    options: [
      "Discharge immediately",
      "Escalate for medical review",
      "Cancel observations",
      "Archive the note",
    ],
    correctAnswer: "Escalate for medical review",
    explanation: "Elevated NEWS2 requires medical review.",
  },
  {
    id: "quiz-r-010",
    skill: "reading",
    part: "B",
    profession: "pharmacy",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-b", "reading:scan"],
    prompt: "Pharmacy bulletin: cold-chain breach on ward fridge 2B. First step?",
    options: [
      "Ignore until Monday",
      "Quarantine affected stock and notify lead pharmacist",
      "Move stock to freezer",
      "Dispense as normal",
    ],
    correctAnswer: "Quarantine affected stock and notify lead pharmacist",
    explanation: "Cold-chain breach requires quarantine and escalation.",
  },
  {
    id: "quiz-r-011",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-c-inference", "reading:inference"],
    prompt: "'The benefits, while real, may not justify the cost' — the author believes benefits are…",
    options: [
      "Non-existent",
      "Real but possibly insufficient for the price",
      "Greater than cost in all cases",
      "Illegal",
    ],
    correctAnswer: "Real but possibly insufficient for the price",
    explanation: "'While real' concedes benefits; 'may not justify' questions value for money.",
  },
  {
    id: "quiz-r-012",
    skill: "reading",
    part: "B",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["reading:part-b-gist", "reading:skim"],
    prompt: "Notice headline: 'Fire drill Wednesday 10:00 — expect delays'. Key point?",
    options: [
      "Real fire emergency",
      "Planned drill may cause disruption",
      "Ward closed permanently",
      "Staff must leave the trust",
    ],
    correctAnswer: "Planned drill may cause disruption",
    explanation: "A scheduled drill may cause delays.",
  },
  {
    id: "quiz-r-013",
    skill: "reading",
    part: "A",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["reading:part-a-speed", "reading:scan"],
    prompt: "Part A texts are best described as…",
    options: [
      "Long academic essays",
      "Short workplace extracts",
      "Patient letters",
      "Audio transcripts",
    ],
    correctAnswer: "Short workplace extracts",
    explanation: "Part A uses four brief workplace texts.",
  },
  {
    id: "quiz-r-014",
    skill: "reading",
    part: "B",
    profession: "medicine",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-b", "reading:scan"],
    prompt: "Referral triage memo: 'Two-week wait breaches must be escalated same day.' Action?",
    options: [
      "Ignore until month end",
      "Escalate same-day breaches immediately",
      "Cancel all referrals",
      "Archive the memo",
    ],
    correctAnswer: "Escalate same-day breaches immediately",
    explanation: "Same-day escalation is required for two-week wait breaches.",
  },
  {
    id: "quiz-r-015",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "mcq",
    difficulty: 3,
    tags: ["reading:part-c", "reading:inference"],
    prompt: "An evaluation 'stops short of recommending rollout' suggests authors…",
    options: [
      "Fully endorse expansion now",
      "Do not yet support wider implementation",
      "Reject the pilot entirely",
      "Have no data",
    ],
    correctAnswer: "Do not yet support wider implementation",
    explanation: "Stopping short of rollout means they withhold full recommendation.",
  },
  {
    id: "quiz-r-016",
    skill: "reading",
    part: "B",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["reading:part-b", "reading:vocabulary"],
    prompt: "Staff must ___ the updated policy on the intranet by Friday.",
    options: ["acknowledge", "celebrate", "ignore", "delete"],
    correctAnswer: "acknowledge",
    explanation: "Policies typically require staff acknowledgement.",
  },
  {
    id: "quiz-r-017",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "true_false",
    difficulty: 2,
    tags: ["reading:part-c-inference", "reading:inference"],
    prompt: "True or false: 'The pilot was largely successful, albeit costly' means the pilot failed completely.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "'Largely successful' contradicts complete failure; 'albeit costly' adds a caveat.",
  },
  {
    id: "quiz-r-018",
    skill: "reading",
    part: "B",
    profession: "nursing",
    type: "true_false",
    difficulty: 2,
    tags: ["reading:part-b-gist", "reading:skim"],
    prompt: "True or false: An email titled 'Shift swap approved — check rota' mainly confirms a schedule change.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Approval + rota check = confirmed schedule change.",
  },
  {
    id: "quiz-r-019",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "ordering",
    difficulty: 3,
    tags: ["reading:part-c", "reading:inference"],
    prompt: "A report lists steps: (1) audit stock (2) notify lead (3) quarantine items (4) document breach. Correct escalation order?",
    options: [
      "Quarantine → notify lead → document → audit",
      "Audit → quarantine → notify lead → document",
      "Notify lead → audit → document → quarantine",
      "Document → audit → quarantine → notify",
    ],
    correctAnswer: "Quarantine → notify lead → document → audit",
    explanation: "Safety first: isolate affected stock, escalate, record, then reconcile inventory.",
  },
  {
    id: "quiz-r-020",
    skill: "reading",
    part: "A",
    profession: "all",
    type: "matching",
    difficulty: 2,
    tags: ["reading:part-a", "reading:scan"],
    prompt: "Memo line: 'Do not restart warfarin until INR reviewed.' Best match?",
    options: [
      "Resume anticoagulation immediately",
      "Hold warfarin pending INR review",
      "Discharge without blood tests",
      "Switch to paracetamol only",
    ],
    correctAnswer: "Hold warfarin pending INR review",
    explanation: "'Do not restart until reviewed' = hold pending review.",
  },
  {
    id: "quiz-r-021",
    skill: "reading",
    part: "B",
    profession: "dentistry",
    type: "gap_fill",
    difficulty: 2,
    tags: ["reading:part-b", "reading:vocabulary"],
    prompt: "Complete: The patient must ___ fasting for six hours before sedation.",
    options: ["maintain", "abandon", "extend", "ignore"],
    correctAnswer: "maintain",
    explanation: "Pre-sedation instructions require maintaining the fast.",
  },
  {
    id: "quiz-r-022",
    skill: "reading",
    part: "C",
    profession: "all",
    type: "true_false",
    difficulty: 3,
    tags: ["reading:part-c-inference", "reading:inference"],
    prompt: "True or false: 'Uptake fell short of expectations, though clinicians remained enthusiastic' — clinicians were disappointed.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "Enthusiasm contradicts disappointment; uptake was low, not clinician attitude.",
  },
  {
    id: "quiz-r-023",
    skill: "reading",
    part: "B",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["reading:part-b-gist", "reading:skim"],
    prompt: "Safety email order: read alert → stop procedure → inform team → complete incident form. First action?",
    options: [
      "Complete incident form",
      "Stop procedure",
      "Inform team only",
      "Archive the email",
    ],
    correctAnswer: "Stop procedure",
    explanation: "Immediate safety: stop the procedure before paperwork.",
  },
  {
    id: "quiz-r-024",
    skill: "reading",
    part: "A",
    profession: "physiotherapy",
    type: "mcq",
    difficulty: 2,
    tags: ["reading:part-a-speed", "reading:scan"],
    prompt: "Discharge summary note: 'Non-weight-bearing x 6 weeks.' Community physio priority?",
    options: [
      "High-load plyometrics today",
      "Mobility and adherence to weight-bearing restrictions",
      "Ignore orthopaedic advice",
      "Cancel all follow-up",
    ],
    correctAnswer: "Mobility and adherence to weight-bearing restrictions",
    explanation: "Non-weight-bearing status drives safe mobility planning.",
  },
];

export function allQuizQuestions(): QuizQuestion[] {
  return QUIZ_BANK;
}
