import type { QuizQuestion } from "@/content/reading/types";

export const LISTENING_QUIZ_BANK: QuizQuestion[] = [
  {
    id: "lq-001",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["listening:part-a-detail"],
    prompt: "Script: 'Take two tablets at bedtime.' How many tablets at bedtime?",
    options: ["One", "Two", "Three", "Four"],
    correctAnswer: "Two",
    explanation: "Bedtime dose is two tablets.",
  },
  {
    id: "lq-002",
    skill: "listening",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["listening:spelling"],
    prompt: "True or false: The correct spelling is 'amlodipine'.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Common antihypertensive — spelling matters in Part A.",
  },
  {
    id: "lq-003",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["listening:part-b-gist"],
    prompt: "Handover: 1L fluid restriction for heart failure. Main clinical concern?",
    options: ["Dehydration", "Fluid overload", "Hypoglycaemia", "Fever"],
    correctAnswer: "Fluid overload",
    explanation: "Restriction prevents fluid overload in heart failure.",
  },
  {
    id: "lq-004",
    skill: "listening",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["listening:part-a-detail"],
    prompt: "Appointment moved to Thursday at ___ (2:30 pm).",
    options: ["half past two", "ten o'clock", "midnight", "noon"],
    correctAnswer: "half past two",
    explanation: "Listen for exact time change.",
  },
  {
    id: "lq-005",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 3,
    tags: ["listening:part-c-inference"],
    prompt: "Warfarin dose increased → INR monitoring should be…",
    options: ["Less frequent", "More frequent", "Stopped", "Unchanged"],
    correctAnswer: "More frequent",
    explanation: "Dose change requires closer INR monitoring.",
  },
];

export const WRITING_QUIZ_BANK: QuizQuestion[] = [
  {
    id: "wq-001",
    skill: "writing",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["writing:purpose"],
    prompt: "Which sentence best establishes Purpose in a referral?",
    options: [
      "I am writing to refer Mr Smith for cardiology review.",
      "The weather was poor yesterday.",
      "I enjoy cardiology.",
      "Please call me anytime.",
    ],
    correctAnswer: "I am writing to refer Mr Smith for cardiology review.",
    explanation: "Purpose = clear reason for writing in opening lines.",
  },
  {
    id: "wq-002",
    skill: "writing",
    profession: "all",
    type: "true_false",
    difficulty: 2,
    tags: ["writing:conciseness"],
    prompt: "True or false: Copying all case notes improves Conciseness marks.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "Select only relevant details.",
  },
  {
    id: "wq-003",
    skill: "writing",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["writing:genre"],
    prompt: "A discharge letter should use…",
    options: [
      "Formal clinical register",
      "Casual chat language",
      "Slang and emojis",
      "Poetry",
    ],
    correctAnswer: "Formal clinical register",
    explanation: "Genre criterion — professional healthcare tone.",
  },
  {
    id: "wq-004",
    skill: "writing",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["writing:organisation"],
    prompt: "Order a standard referral structure (first → last):",
    options: [
      "State purpose and patient details",
      "Present relevant history",
      "Request action or follow-up",
      "Close formally",
    ],
    correctAnswer: [
      "State purpose and patient details",
      "Present relevant history",
      "Request action or follow-up",
      "Close formally",
    ],
    explanation: "Purpose → content → request → close.",
  },
  {
    id: "wq-005",
    skill: "writing",
    profession: "all",
    type: "gap_fill",
    difficulty: 1,
    tags: ["writing:language"],
    prompt: "Complete: I would be grateful if you could ___ an appointment.",
    options: ["arrange", "ignore", "cancel", "forget"],
    correctAnswer: "arrange",
    explanation: "Standard polite request phrasing in OET letters.",
  },
];

export const SPEAKING_QUIZ_BANK: QuizQuestion[] = [
  {
    id: "sq-001",
    skill: "speaking",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["speaking:ice-expectations"],
    prompt: "In ICE, 'C' stands for…",
    options: ["Concerns", "Consultation", "Consent", "Criteria"],
    correctAnswer: "Concerns",
    explanation: "Ideas, Concerns, and Expectations.",
  },
  {
    id: "sq-002",
    skill: "speaking",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["speaking:structure"],
    prompt: "True or false: You should introduce yourself and your role at the start of a role-play.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Professional opening is expected in OET Speaking.",
  },
  {
    id: "sq-003",
    skill: "speaking",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["speaking:clinical-communication"],
    prompt: "When a patient is anxious, you should first…",
    options: [
      "Acknowledge feelings and explore concerns",
      "End the consultation",
      "Change the topic",
      "Speak louder",
    ],
    correctAnswer: "Acknowledge feelings and explore concerns",
    explanation: "Empathy and ICE support clinical communication marks.",
  },
  {
    id: "sq-004",
    skill: "speaking",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["speaking:structure"],
    prompt: "Order role-play opening (first → last):",
    options: [
      "Greet and introduce yourself",
      "Confirm who you are speaking with",
      "Explain what you will cover",
      "Jump to treatment without context",
    ],
    correctAnswer: [
      "Greet and introduce yourself",
      "Confirm who you are speaking with",
      "Explain what you will cover",
      "Jump to treatment without context",
    ],
    explanation: "Last option is a trap — never skip rapport.",
  },
  {
    id: "sq-005",
    skill: "speaking",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["speaking:ice-expectations"],
    prompt: "Complete: 'What were you ___ to happen after the procedure?'",
    options: ["expecting", "hoping", "fearing", "planning"],
    correctAnswer: "expecting",
    explanation: "Elicits Expectations in ICE.",
  },
];
