import type { QuizQuestion } from "@/content/reading/types";

export const LISTENING_QUIZ_BANK: QuizQuestion[] = [
  {
    id: "lq-001",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["listening:part-a-detail"],
    prompt: "Script: 'Take two tablets at bedtime.' How many tablets at bedtime?",
    options: ["One", "Two", "Three", "Four"],
    correctAnswer: "Two",
    explanation: "Bedtime dose is two tablets.",
  },
  {
    id: "lq-002",
    skill: "listening",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["listening:spelling"],
    prompt: "True or false: The correct spelling is 'amlodipine'.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Common antihypertensive — spelling matters in Part A.",
  },
  {
    id: "lq-003",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["listening:part-b-gist"],
    prompt: "Handover: 1L fluid restriction for heart failure. Main clinical concern?",
    options: ["Dehydration", "Fluid overload", "Hypoglycaemia", "Fever"],
    correctAnswer: "Fluid overload",
    explanation: "Restriction prevents fluid overload in heart failure.",
  },
  {
    id: "lq-004",
    skill: "listening",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["listening:part-a-detail"],
    prompt: "Appointment moved to Thursday at ___ (2:30 pm).",
    options: ["half past two", "ten o'clock", "midnight", "noon"],
    correctAnswer: "half past two",
    explanation: "Listen for exact time change.",
  },
  {
    id: "lq-005",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 3,
    tags: ["listening:part-c-inference"],
    prompt: "Warfarin dose increased → INR monitoring should be…",
    options: ["Less frequent", "More frequent", "Stopped", "Unchanged"],
    correctAnswer: "More frequent",
    explanation: "Dose change requires closer INR monitoring.",
  },
  {
    id: "lq-006",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["listening:part-a-detail"],
    prompt: "Notes: 'Allergic to penicillin.' Which allergy must be recorded?",
    options: ["Penicillin", "Aspirin", "Latex", "None"],
    correctAnswer: "Penicillin",
    explanation: "Drug allergies must be spelled correctly in Part A notes.",
  },
  {
    id: "lq-007",
    skill: "listening",
    profession: "all",
    type: "gap_fill",
    difficulty: 1,
    tags: ["listening:spelling"],
    prompt: "Medication: ___ 5 mg once daily (blood pressure tablet).",
    options: ["amlodipine", "amoxicillin", "aspirin", "atenolol"],
    correctAnswer: "amlodipine",
    explanation: "Common antihypertensive — spelling matters.",
  },
  {
    id: "lq-008",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["listening:part-b-gist"],
    prompt: "Email: 'Please confirm theatre list by 4 pm.' Main purpose?",
    options: ["Request confirmation", "Cancel surgery", "Discharge patient", "Order imaging"],
    correctAnswer: "Request confirmation",
    explanation: "Part B tests gist and next action.",
  },
  {
    id: "lq-009",
    skill: "listening",
    profession: "all",
    type: "true_false",
    difficulty: 2,
    tags: ["listening:part-c-inference"],
    prompt: "True or false: 'The speaker remains cautious about long-term outcomes.' suggests limited optimism.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Attitude language in Part C presentations.",
  },
  {
    id: "lq-010",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["listening:part-a-detail"],
    prompt: "'Nil by mouth from midnight.' Patient may eat/drink after midnight?",
    options: ["No", "Yes", "Only water", "Only if hungry"],
    correctAnswer: "No",
    explanation: "NBM means nothing orally from the stated time.",
  },
  {
    id: "lq-011",
    skill: "listening",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["listening:part-a-detail"],
    prompt: "Follow-up appointment in ___ weeks.",
    options: ["two", "ten", "twenty", "twelve"],
    correctAnswer: "two",
    explanation: "Listen for number words under accent.",
  },
  {
    id: "lq-012",
    skill: "listening",
    profession: "all",
    type: "mcq",
    difficulty: 3,
    tags: ["listening:part-c-inference"],
    prompt: "Presentation: trial results 'promising but preliminary'. Best inference?",
    options: ["More evidence needed", "Treatment is proven", "Study was cancelled", "No side effects"],
    correctAnswer: "More evidence needed",
    explanation: "Hedging language signals cautious stance.",
  },
];

export const WRITING_QUIZ_BANK: QuizQuestion[] = [
  {
    id: "wq-001",
    skill: "writing",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["writing:purpose"],
    prompt: "Which sentence best establishes Purpose in a referral?",
    options: [
      "I am writing to refer Mr Smith for cardiology review.",
      "The weather was poor yesterday.",
      "I enjoy cardiology.",
      "Please call me anytime.",
    ],
    correctAnswer: "I am writing to refer Mr Smith for cardiology review.",
    explanation: "Purpose = clear reason for writing in opening lines.",
  },
  {
    id: "wq-002",
    skill: "writing",
    profession: "all",
    type: "true_false",
    difficulty: 2,
    tags: ["writing:conciseness"],
    prompt: "True or false: Copying all case notes improves Conciseness marks.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "Select only relevant details.",
  },
  {
    id: "wq-003",
    skill: "writing",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["writing:genre"],
    prompt: "A discharge letter should use…",
    options: [
      "Formal clinical register",
      "Casual chat language",
      "Slang and emojis",
      "Poetry",
    ],
    correctAnswer: "Formal clinical register",
    explanation: "Genre criterion — professional healthcare tone.",
  },
  {
    id: "wq-004",
    skill: "writing",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["writing:organisation"],
    prompt: "Order a standard referral structure (first → last):",
    options: [
      "State purpose and patient details",
      "Present relevant history",
      "Request action or follow-up",
      "Close formally",
    ],
    correctAnswer: [
      "State purpose and patient details",
      "Present relevant history",
      "Request action or follow-up",
      "Close formally",
    ],
    explanation: "Purpose → content → request → close.",
  },
  {
    id: "wq-005",
    skill: "writing",
    profession: "all",
    type: "gap_fill",
    difficulty: 1,
    tags: ["writing:language"],
    prompt: "Complete: I would be grateful if you could ___ an appointment.",
    options: ["arrange", "ignore", "cancel", "forget"],
    correctAnswer: "arrange",
    explanation: "Standard polite request phrasing in OET letters.",
  },
  {
    id: "wq-006",
    skill: "writing",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["writing:content"],
    prompt: "Which detail is essential Content in a discharge letter?",
    options: ["Current medications and follow-up plan", "Hospital cafeteria menu", "Weather forecast", "Staff shift times"],
    correctAnswer: "Current medications and follow-up plan",
    explanation: "Content = clinically relevant information for the reader.",
  },
  {
    id: "wq-007",
    skill: "writing",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["writing:language"],
    prompt: "True or false: Contractions like 'don't' are acceptable in formal OET letters.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "Genre expects formal clinical register.",
  },
  {
    id: "wq-008",
    skill: "writing",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["writing:purpose"],
    prompt: "Opening: I am writing to ___ Mrs Lee to your dietetic clinic.",
    options: ["refer", "invite", "discharge", "thank"],
    correctAnswer: "refer",
    explanation: "Purpose must be clear in the first lines.",
  },
  {
    id: "wq-009",
    skill: "writing",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["writing:conciseness"],
    prompt: "Which sentence is most concise?",
    options: [
      "HbA1c 64 mmol/mol; metformin continued.",
      "The patient has diabetes and many other things happened.",
      "It is important to note that various events occurred.",
      "In my personal opinion the situation is complex.",
    ],
    correctAnswer: "HbA1c 64 mmol/mol; metformin continued.",
    explanation: "Conciseness = relevant facts without padding.",
  },
  {
    id: "wq-010",
    skill: "writing",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["writing:organisation"],
    prompt: "Discharge letter sections (first → last):",
    options: ["Purpose & patient ID", "Hospital course", "Discharge plan & meds", "Professional close"],
    correctAnswer: ["Purpose & patient ID", "Hospital course", "Discharge plan & meds", "Professional close"],
    explanation: "Logical Organisation helps the reader act quickly.",
  },
  {
    id: "wq-011",
    skill: "writing",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["writing:genre"],
    prompt: "A letter to a patient's GP should avoid…",
    options: ["Informal slang", "Past medical history", "Medication list", "Follow-up request"],
    correctAnswer: "Informal slang",
    explanation: "Genre & Style = professional healthcare tone.",
  },
  {
    id: "wq-012",
    skill: "writing",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["writing:language"],
    prompt: "Please ___ me should his symptoms worsen.",
    options: ["contact", "ignore", "forget", "delay"],
    correctAnswer: "contact",
    explanation: "Standard safety-netting language.",
  },
];

export const SPEAKING_QUIZ_BANK: QuizQuestion[] = [
  {
    id: "sq-001",
    skill: "speaking",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["speaking:ice-expectations"],
    prompt: "In ICE, 'C' stands for…",
    options: ["Concerns", "Consultation", "Consent", "Criteria"],
    correctAnswer: "Concerns",
    explanation: "Ideas, Concerns, and Expectations.",
  },
  {
    id: "sq-002",
    skill: "speaking",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["speaking:structure"],
    prompt: "True or false: You should introduce yourself and your role at the start of a role-play.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Professional opening is expected in OET Speaking.",
  },
  {
    id: "sq-003",
    skill: "speaking",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["speaking:clinical-communication"],
    prompt: "When a patient is anxious, you should first…",
    options: [
      "Acknowledge feelings and explore concerns",
      "End the consultation",
      "Change the topic",
      "Speak louder",
    ],
    correctAnswer: "Acknowledge feelings and explore concerns",
    explanation: "Empathy and ICE support clinical communication marks.",
  },
  {
    id: "sq-004",
    skill: "speaking",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["speaking:structure"],
    prompt: "Order role-play opening (first → last):",
    options: [
      "Greet and introduce yourself",
      "Confirm who you are speaking with",
      "Explain what you will cover",
      "Jump to treatment without context",
    ],
    correctAnswer: [
      "Greet and introduce yourself",
      "Confirm who you are speaking with",
      "Explain what you will cover",
      "Jump to treatment without context",
    ],
    explanation: "Last option is a trap — never skip rapport.",
  },
  {
    id: "sq-005",
    skill: "speaking",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["speaking:ice-expectations"],
    prompt: "Complete: 'What were you ___ to happen after the procedure?'",
    options: ["expecting", "hoping", "fearing", "planning"],
    correctAnswer: "expecting",
    explanation: "Elicits Expectations in ICE.",
  },
  {
    id: "sq-006",
    skill: "speaking",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["speaking:ice-expectations"],
    prompt: "To elicit Ideas, ask…",
    options: ["What do you think is causing this?", "Sign here please.", "The ward is on level 3.", "Your blood pressure is fine."],
    correctAnswer: "What do you think is causing this?",
    explanation: "Ideas = patient's own understanding.",
  },
  {
    id: "sq-007",
    skill: "speaking",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["speaking:clinical-communication"],
    prompt: "True or false: 'Do you understand?' alone is weaker than teach-back.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Teach-back checks understanding more reliably.",
  },
  {
    id: "sq-008",
    skill: "speaking",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["speaking:structure"],
    prompt: "Professional opening: Good morning, I'm ___ , the physiotherapist.",
    options: ["Sarah", "busy", "late", "worried"],
    correctAnswer: "Sarah",
    explanation: "Introduce name and role at the start.",
  },
  {
    id: "sq-009",
    skill: "speaking",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["speaking:clinical-communication"],
    prompt: "Patient says 'I'm scared of the side effects.' Best first response?",
    options: ["I hear that you're worried about side effects.", "Take the tablet anyway.", "Side effects are rare.", "Read the leaflet."],
    correctAnswer: "I hear that you're worried about side effects.",
    explanation: "Acknowledge concerns before explaining.",
  },
  {
    id: "sq-010",
    skill: "speaking",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["speaking:structure"],
    prompt: "Consultation flow (first → last):",
    options: ["Greet & introduce", "Gather information (ICE)", "Give information in chunks", "Check understanding & close"],
    correctAnswer: ["Greet & introduce", "Gather information (ICE)", "Give information in chunks", "Check understanding & close"],
    explanation: "Structure supports clinical communication marks.",
  },
  {
    id: "sq-011",
    skill: "speaking",
    profession: "all",
    type: "mcq",
    difficulty: 3,
    tags: ["speaking:clinical-communication"],
    prompt: "Leading question to avoid:",
    options: ["You're not in pain, are you?", "Can you describe the pain?", "When did it start?", "What makes it better?"],
    correctAnswer: "You're not in pain, are you?",
    explanation: "Leading questions bias the patient's answer.",
  },
  {
    id: "sq-012",
    skill: "speaking",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["speaking:ice-expectations"],
    prompt: "What is your main ___ about starting this treatment?",
    options: ["concern", "appointment", "ward", "breakfast"],
    correctAnswer: "concern",
    explanation: "Elicits Concerns in ICE.",
  },
];
