import type { QuizQuestion } from "@/content/reading/types";

import { ALL_SKILL_PHRASES } from "./skill-vocab-phrases";

/** OET healthcare vocabulary — phrases and words with explanations. */
export const VOCAB_BANK: QuizQuestion[] = [
  {
    id: "vocab-001",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["vocab:abbreviations"],
    prompt: "What does PRN mean on a medication chart?",
    options: ["As needed", "Every morning", "Before meals", "Do not administer"],
    correctAnswer: "As needed",
    explanation: "Pro re nata — give when required.",
  },
  {
    id: "vocab-002",
    skill: "vocab",
    profession: "all",
    type: "gap_fill",
    difficulty: 1,
    tags: ["vocab:clinical"],
    prompt: "The patient felt general ___ (unwellness) after the infusion.",
    options: ["malaise", "euphoria", "apathy", "vitality"],
    correctAnswer: "malaise",
    explanation: "Malaise = vague feeling of illness or discomfort.",
  },
  {
    id: "vocab-003",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:medications"],
    prompt: "'Stat' in a clinical order means…",
    options: ["Immediately", "Weekly", "With food", "At bedtime"],
    correctAnswer: "Immediately",
    explanation: "From Latin statim — do now.",
  },
  {
    id: "vocab-004",
    skill: "vocab",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["vocab:communication"],
    prompt: "True or false: 'Nil by mouth' means the patient must not eat or drink.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "NBM / NPO — nothing orally.",
  },
  {
    id: "vocab-005",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:clinical"],
    prompt: "A 'differential diagnosis' is…",
    options: [
      "List of possible conditions",
      "Final confirmed diagnosis",
      "Patient's own theory",
      "Insurance code",
    ],
    correctAnswer: "List of possible conditions",
    explanation: "Working list while ruling conditions in or out.",
  },
  {
    id: "vocab-006",
    skill: "vocab",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["vocab:writing"],
    prompt: "Complete: Please ___ the patient to cardiology within two weeks.",
    options: ["refer", "defer", "discharge", "ignore"],
    correctAnswer: "refer",
    explanation: "Refer = send to another specialist — common in OET letters.",
  },
  {
    id: "vocab-007",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["vocab:listening"],
    prompt: "'Bilateral' means affecting…",
    options: ["Both sides", "One side only", "The heart", "The brain"],
    correctAnswer: "Both sides",
    explanation: "Bi- = two; lateral = side.",
  },
  {
    id: "vocab-008",
    skill: "vocab",
    profession: "all",
    type: "ordering",
    difficulty: 2,
    tags: ["vocab:handover"],
    prompt: "Order a safe handover (first → last):",
    options: [
      "Confirm patient identity",
      "State current problem",
      "List pending actions",
      "Sign off with name",
    ],
    correctAnswer: [
      "Confirm patient identity",
      "State current problem",
      "List pending actions",
      "Sign off with name",
    ],
    explanation: "Identity → situation → plan → accountability.",
  },
  {
    id: "vocab-009",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:abbreviations", "vocab:renal"],
    prompt: "In 'eGFR 58 mL/min', what does eGFR measure?",
    options: [
      "Kidney filtration rate",
      "Heart rate",
      "Blood pressure",
      "Liver enzymes",
    ],
    correctAnswer: "Kidney filtration rate",
    explanation: "eGFR = estimated glomerular filtration rate — how well kidneys filter blood.",
  },
  {
    id: "vocab-010",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["vocab:abbreviations"],
    prompt: "What does ICE stand for in OET Speaking?",
    options: [
      "Ideas, Concerns, Expectations",
      "Immediate Clinical Examination",
      "Internal Care Escalation",
      "Infection Control Entry",
    ],
    correctAnswer: "Ideas, Concerns, Expectations",
    explanation: "ICE is the patient-centred communication framework for Speaking.",
  },
  {
    id: "vocab-011",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:reading", "reading:part-c"],
    prompt: "In Part C, 'the author remains sceptical' means the writer is…",
    options: ["Not fully convinced", "Very enthusiastic", "Unaware", "Angry"],
    correctAnswer: "Not fully convinced",
    explanation: "Attitude questions test nuanced stance language.",
  },
  {
    id: "vocab-012",
    skill: "vocab",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["vocab:listening", "listening:part-a"],
    prompt: "Notes: patient is ___ by mouth (NBM).",
    options: ["nil", "full", "partial", "free"],
    correctAnswer: "nil",
    explanation: "Nil by mouth = nothing orally.",
  },
  {
    id: "vocab-013",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["vocab:writing", "writing:purpose"],
    prompt: "'I am writing to update you regarding…' establishes…",
    options: ["Purpose", "Weather", "Word count", "Signature"],
    correctAnswer: "Purpose",
    explanation: "Opening lines must state why you are writing.",
  },
  {
    id: "vocab-014",
    skill: "vocab",
    profession: "all",
    type: "true_false",
    difficulty: 2,
    tags: ["vocab:speaking"],
    prompt: "True or false: Teach-back means asking the patient to explain back in their own words.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Teach-back checks understanding in Speaking.",
  },
  {
    id: "vocab-015",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:clinical"],
    prompt: "Hypertension means…",
    options: ["High blood pressure", "Low blood sugar", "Fast heart rate", "Lung infection"],
    correctAnswer: "High blood pressure",
    explanation: "Common term in case notes and letters.",
  },
  {
    id: "vocab-016",
    skill: "vocab",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["vocab:abbreviations"],
    prompt: "Rx on a chart usually means…",
    options: ["prescription", "reaction", "referral", "recovery"],
    correctAnswer: "prescription",
    explanation: "Rx = prescription — common abbreviation.",
  },
  {
    id: "vocab-017",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:reading", "reading:part-b"],
    prompt: "Part B 'purpose' questions often ask about the…",
    options: ["Main aim of the text", "Author's birthday", "Font size", "Paper colour"],
    correctAnswer: "Main aim of the text",
    explanation: "Gist and purpose are core Part B skills.",
  },
  {
    id: "vocab-018",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 1,
    tags: ["vocab:listening"],
    prompt: "TDS on a drug chart means…",
    options: ["Three times daily", "Twice daily", "At bedtime", "As needed"],
    correctAnswer: "Three times daily",
    explanation: "Ter die sumendum — three times a day.",
  },
  {
    id: "vocab-019",
    skill: "vocab",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["vocab:writing"],
    prompt: "Discharge letter: please ___ an outpatient appointment.",
    options: ["arrange", "cancel", "ignore", "delete"],
    correctAnswer: "arrange",
    explanation: "Standard request phrasing in OET writing.",
  },
  {
    id: "vocab-020",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:speaking", "speaking:structure"],
    prompt: "A closed question typically…",
    options: ["Can be answered yes/no", "Always takes 10 minutes", "Is never used in OET", "Replaces ICE"],
    correctAnswer: "Can be answered yes/no",
    explanation: "Use open questions first, closed to confirm.",
  },
  {
    id: "vocab-021",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:clinical"],
    prompt: "Exacerbation means…",
    options: ["Worsening of a condition", "Complete cure", "New allergy", "Discharge home"],
    correctAnswer: "Worsening of a condition",
    explanation: "Common in respiratory and cardiac notes.",
  },
  {
    id: "vocab-022",
    skill: "vocab",
    profession: "all",
    type: "true_false",
    difficulty: 1,
    tags: ["vocab:reading"],
    prompt: "True or false: Part A matching uses four texts labelled A–D.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Standard Part A format.",
  },
  {
    id: "vocab-023",
    skill: "vocab",
    profession: "all",
    type: "gap_fill",
    difficulty: 2,
    tags: ["vocab:listening", "listening:spelling"],
    prompt: "Condition: type 2 ___ (blood sugar disorder).",
    options: ["diabetes", "dermatitis", "diarrhoea", "depression"],
    correctAnswer: "diabetes",
    explanation: "Spelling clinical conditions matters in Listening Part A.",
  },
  {
    id: "vocab-024",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:writing", "writing:conciseness"],
    prompt: "Which phrase is padding (not Concise)?",
    options: ["It is important to note that", "HbA1c 58 mmol/mol", "On metformin 500 mg bd", "Follow-up in 2 weeks"],
    correctAnswer: "It is important to note that",
    explanation: "Remove filler phrases in OET letters.",
  },
  {
    id: "vocab-025",
    skill: "vocab",
    profession: "all",
    type: "mcq",
    difficulty: 2,
    tags: ["vocab:speaking"],
    prompt: "Empathy in role-play means…",
    options: ["Acknowledging the patient's feelings", "Speaking as fast as possible", "Using medical jargon only", "Ending early"],
    correctAnswer: "Acknowledging the patient's feelings",
    explanation: "Clinical communication criterion in Speaking.",
  },
];

export interface VocabPhrase {
  id: string;
  phrase: string;
  meaning: string;
  example: string;
  tags: string[];
}

export const VOCAB_PHRASES: VocabPhrase[] = [
  {
    id: "phr-001",
    phrase: "Presenting complaint",
    meaning: "Main reason the patient came for care",
    example: "Her presenting complaint was chest pain on exertion.",
    tags: ["vocab:clinical"],
  },
  {
    id: "phr-002",
    phrase: "On admission",
    meaning: "When the patient entered hospital or care",
    example: "On admission, observations were within normal limits.",
    tags: ["vocab:writing"],
  },
  {
    id: "phr-003",
    phrase: "For your information",
    meaning: "FYI — sharing without requiring action",
    example: "For your information, the patient declined the flu vaccine.",
    tags: ["vocab:writing"],
  },
  {
    id: "phr-004",
    phrase: "As discussed",
    meaning: "Referring to a prior conversation",
    example: "As discussed, I am writing to confirm the referral.",
    tags: ["vocab:writing"],
  },
  {
    id: "phr-005",
    phrase: "Nil by mouth",
    meaning: "Patient must not eat or drink",
    example: "The patient is nil by mouth from midnight.",
    tags: ["vocab:clinical"],
  },
  {
    id: "phr-006",
    phrase: "eGFR",
    meaning: "Estimated glomerular filtration rate — kidney function in mL/min",
    example: "His eGFR is 58 mL/min; review renally cleared medicines.",
    tags: ["vocab:abbreviations", "vocab:renal"],
  },
  {
    id: "phr-007",
    phrase: "HbA1c",
    meaning: "Average blood glucose over ~3 months",
    example: "HbA1c is 64 mmol/mol, above the agreed target.",
    tags: ["vocab:abbreviations", "vocab:diabetes"],
  },
  {
    id: "phr-008",
    phrase: "ICE",
    meaning: "Ideas, Concerns, Expectations — patient-centred speaking framework",
    example: "I explored her ideas, concerns, and expectations about insulin.",
    tags: ["vocab:speaking"],
  },
  ...ALL_SKILL_PHRASES,
];
