import type { RolePlayCard } from "./types";

/**
 * Accent-diversity speaking cards — patient/carer accents differ from setting.
 * OET interlocutors use varied English; practise intelligibility + clinical comm.
 */
export const ACCENT_SPEAKING_CARDS: RolePlayCard[] = [
  {
    id: "s-accent-med-001",
    profession: "medicine",
    difficulty: 2,
    countryCode: "UK",
    setting: "London GP — multicultural practice",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "General Practitioner",
    interlocutorRole: "Patient",
    patientAccent: "IE",
    accentContext: "Patient born in Cork, lived in UK 15 years — clear English with Irish rhythm. Focus on ICE, not accent.",
    cardText: {
      overview: "Patient with persistent reflux worried about cancer after reading online forums.",
      patientDetails: "Mr Doyle, 48, Irish-background, heartburn 6 weeks on omeprazole",
      yourTasks: [
        "Elicit ideas, concerns and expectations",
        "Address cancer fear without dismissing",
        "Explain next steps including possible referral",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Certain it is oesophageal cancer", "Cannot afford private scan"],
      patientKnowledge: "Knows omeprazole helps partially",
    },
    coaching: {
      iceQuestions: ["What have you read that worried you?", "What do you think might be happening?"],
      structure: ["ICE", "Validate concern", "Explain plan", "Check understanding"],
      phrasesToAvoid: ["Don't worry", "It's just stress"],
      usefulPhrases: ["Many people with your symptoms do not have cancer — let me explain what we look for."],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Doyle, what have you been reading that concerned you?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Online forums say heartburn means cancer. I'm terrified." },
      { speaker: "candidate", line: "That fear is understandable. What would you like from today's appointment?", annotation: "ICE — Expectations" },
      { speaker: "candidate", line: "We'll review your symptoms and whether referral is needed. What questions do you have?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-accent-nurs-001",
    profession: "nursing",
    difficulty: 2,
    countryCode: "AU",
    setting: "Sydney ward — post-op",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Registered Nurse",
    interlocutorRole: "Patient",
    patientAccent: "NZ",
    accentContext: "Māori-New Zealand patient in Australian hospital — NZ vowel sounds.",
    cardText: {
      overview: "Teach breathing exercises after abdominal surgery to anxious patient.",
      patientDetails: "Ms Hemi, 55, day 1 post laparotomy",
      yourTasks: ["Assess pain and anxiety", "Demonstrate incentive spirometry", "Explain when to call nurse", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Pain when coughing", "Whānau not allowed overnight"],
      patientKnowledge: "Had surgery yesterday, unclear about tubes",
    },
    coaching: {
      iceQuestions: ["How is the pain when you breathe?", "What concerns you most tonight?"],
      structure: ["Assess", "Demonstrate", "Safety net", "Check"],
      phrasesToAvoid: ["Just do it", "It won't hurt"],
      usefulPhrases: ["We'll splint your abdomen with a pillow when you cough."],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Hemi, how does it feel when you take a deep breath?", annotation: "Open question" },
      { speaker: "patient", line: "It stings. I'm scared of bursting something." },
      { speaker: "candidate", line: "Let's practise gentle breaths with the spirometer — I'll show you first.", annotation: "Demonstration" },
    ],
  },
  {
    id: "s-accent-pharm-001",
    profession: "pharmacy",
    difficulty: 2,
    countryCode: "CA",
    setting: "Toronto community pharmacy",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Pharmacist",
    interlocutorRole: "Patient",
    patientAccent: "US",
    accentContext: "Caribbean-Canadian patient — North American cadence. Counselling on warfarin.",
    cardText: {
      overview: "Counsel patient on warfarin and dietary vitamin K consistency.",
      patientDetails: "Mr Sinclair, 67, new warfarin prescription",
      yourTasks: ["Elicit diet habits", "Explain vitamin K consistency", "Safety signs", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Loves leafy greens daily", "Friend stopped warfarin due to bleeding"],
      patientKnowledge: "Knows it thins blood",
    },
    coaching: {
      iceQuestions: ["What do you eat regularly?", "What concerns you about warfarin?"],
      structure: ["Diet history", "Explain consistency", "Safety", "Check"],
      phrasesToAvoid: ["Stop all greens"],
      usefulPhrases: ["Keep vitamin K intake consistent rather than stopping vegetables."],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "What vegetables do you eat most days?", annotation: "Information gathering" },
      { speaker: "patient", line: "Spinach and callaloo — I won't give them up." },
      { speaker: "candidate", line: "Consistency matters more than avoidance. Let me explain.", annotation: "Information giving" },
    ],
  },
  {
    id: "s-accent-dent-001",
    profession: "dentistry",
    difficulty: 2,
    countryCode: "US",
    setting: "Chicago dental practice",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dentist",
    interlocutorRole: "Patient",
    patientAccent: "mixed",
    accentContext: "Filipino-American patient — clear English, different stress on dental terms.",
    cardText: {
      overview: "Explain need for root canal to anxious patient.",
      patientDetails: "Mrs Santos, 40, severe UL6 pain",
      yourTasks: ["Acknowledge anxiety", "Explain RCT simply", "Discuss alternatives", "Check consent for language practice"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Had bad experience in Philippines", "Cost of treatment"],
      patientKnowledge: "Thinks extraction is only option",
    },
    coaching: {
      iceQuestions: ["What worries you about dental treatment?", "What do you know about this tooth?"],
      structure: ["Empathy", "Explain", "Options", "Check"],
      phrasesToAvoid: ["It won't hurt"],
      usefulPhrases: ["We'll use local anaesthetic so you stay comfortable throughout."],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Santos, tell me about your previous dental experiences.", annotation: "Patient perspective" },
      { speaker: "patient", line: "In the Philippines it was very painful. I'm scared." },
      { speaker: "candidate", line: "A root canal removes infection inside the tooth — we can save the tooth.", annotation: "Information giving" },
    ],
  },
  {
    id: "s-accent-phys-001",
    profession: "physiotherapy",
    difficulty: 2,
    countryCode: "IE",
    setting: "Dublin outpatient gym",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physiotherapist",
    interlocutorRole: "Patient",
    patientAccent: "UK",
    accentContext: "British patient in Irish clinic — RP-influenced English.",
    cardText: {
      overview: "Explain home exercise programme for frozen shoulder.",
      patientDetails: "Mr Clarke, 58, adhesive capsulitis",
      yourTasks: ["Assess understanding", "Teach pendulum exercises", "Pain management advice", "Check adherence plan"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Exercises too painful", "Travels to UK monthly"],
      patientKnowledge: "Diagnosed last week",
    },
    coaching: {
      iceQuestions: ["What have you tried so far?", "When is pain worst?"],
      structure: ["Assess", "Teach", "Pace", "Check"],
      phrasesToAvoid: ["Push through pain"],
      usefulPhrases: ["Gentle movement within acceptable pain helps recovery."],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Clarke, show me how far you can lift the arm now.", annotation: "Assessment" },
      { speaker: "patient", line: "Only to here — it's agony past ninety degrees." },
      { speaker: "candidate", line: "We'll start pendulum exercises below that point.", annotation: "Graded plan" },
    ],
  },
  {
    id: "s-accent-ot-001",
    profession: "occupational_therapy",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Auckland home visit",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Occupational Therapist",
    interlocutorRole: "Carer",
    patientAccent: "AU",
    accentContext: "Australian daughter caring for Samoan mother — AU accent, cultural family roles.",
    cardText: {
      overview: "Advise on bathroom safety after mother's stroke.",
      patientDetails: "Daughter Sina cares for mother Malia, 72",
      yourTasks: ["Elicit current routine", "Recommend grab rails", "Discuss family roles respectfully", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Mother refuses rails as 'for old people'", "Sina works full-time"],
      patientKnowledge: "Mother uses walking stick",
    },
    coaching: {
      iceQuestions: ["How do you help your mother shower now?", "What worries you most?"],
      structure: ["Routine", "Recommendations", "Cultural respect", "Check"],
      phrasesToAvoid: ["She must accept rails"],
      usefulPhrases: ["How might we present this as maintaining her independence?"],
      weakTags: ["speaking:clinical-comm", "speaking:ice-expectations"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Sina, walk me through how your mother showers at the moment.", annotation: "Information gathering" },
      { speaker: "carer", line: "I hold the door. Mum says rails are embarrassing." },
      { speaker: "candidate", line: "Some families frame rails as preventing falls so she stays independent.", annotation: "Cultural sensitivity" },
    ],
  },
  {
    id: "s-accent-pod-001",
    profession: "podiatry",
    difficulty: 2,
    countryCode: "UK",
    setting: "Birmingham podiatry clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Podiatrist",
    interlocutorRole: "Patient",
    patientAccent: "mixed",
    accentContext: "British-Punjabi patient — South Asian English rhythm.",
    cardText: {
      overview: "Diabetic foot education with patient who removes shoes at home only.",
      patientDetails: "Mr Begum, 60, Type 2 diabetes, peripheral neuropathy",
      yourTasks: ["Assess foot care habits", "Explain daily inspection", "Footwear advice", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Feet feel fine so no need to check", "Wears sandals at mosque"],
      patientKnowledge: "Has diabetes tablets",
    },
    coaching: {
      iceQuestions: ["How do you look after your feet?", "What concerns you?"],
      structure: ["Habits", "Risk", "Daily routine", "Check"],
      phrasesToAvoid: ["You'll lose your foot"],
      usefulPhrases: ["Neuropathy means you might not feel injury — daily checks are essential."],
      weakTags: ["speaking:ice-expectations", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Begum, when do you last looked at the soles of your feet?", annotation: "Assessment" },
      { speaker: "patient", line: "I don't — they feel normal." },
      { speaker: "candidate", line: "With neuropathy, use a mirror each evening to inspect soles.", annotation: "Teaching" },
    ],
  },
  {
    id: "s-accent-opt-001",
    profession: "optometry",
    difficulty: 2,
    countryCode: "AU",
    setting: "Melbourne optometry",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Optometrist",
    interlocutorRole: "Patient",
    patientAccent: "IE",
    accentContext: "Irish backpacker patient on working holiday — Irish accent.",
    cardText: {
      overview: "Explain contact lens hygiene after corneal abrasion.",
      patientDetails: "Ms Ryan, 24, slept in lenses, red eye",
      yourTasks: ["Elicit lens habits", "Explain abrasion care", "When to return", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot afford new lenses", "Needs lenses for job interview"],
      patientKnowledge: "Sleeps in lenses occasionally",
    },
    coaching: {
      iceQuestions: ["How do you usually care for your lenses?", "What concerns you today?"],
      structure: ["Habits", "Explain injury", "Plan", "Check"],
      phrasesToAvoid: ["You were careless"],
      usefulPhrases: ["No lenses until the abrasion heals — usually about one week."],
      weakTags: ["speaking:language", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Tell me your lens routine — cleaning, sleeping, swimming.", annotation: "History" },
      { speaker: "patient", line: "I sleep in them when I'm tired after shifts." },
      { speaker: "candidate", line: "That raises abrasion risk. No lenses for seven days.", annotation: "Clear plan" },
    ],
  },
  {
    id: "s-accent-diet-001",
    profession: "dietetics",
    difficulty: 2,
    countryCode: "US",
    setting: "Houston clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dietitian",
    interlocutorRole: "Patient",
    patientAccent: "mixed",
    accentContext: "Mexican-American patient — bilingual household, clear English.",
    cardText: {
      overview: "Counsel on Type 2 diabetes and traditional diet changes.",
      patientDetails: "Mrs Garcia, 52, newly diagnosed",
      yourTasks: ["Elicit typical meals", "Suggest practical swaps", "Respect cultural foods", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Family will not eat 'diet food'", "Loves tortillas and rice"],
      patientKnowledge: "Knows sugar is bad",
    },
    coaching: {
      iceQuestions: ["What does a typical day of eating look like?", "What worries you about changing diet?"],
      structure: ["Diet history", "Collaborative swaps", "Check"],
      phrasesToAvoid: ["Stop all carbs"],
      usefulPhrases: ["We can adjust portion sizes while keeping cultural dishes."],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Describe breakfast, lunch and dinner yesterday.", annotation: "Open history" },
      { speaker: "patient", line: "Tortillas at every meal — my family won't change." },
      { speaker: "candidate", line: "Let's start with smaller portions and more beans and vegetables.", annotation: "Collaborative plan" },
    ],
  },
  {
    id: "s-accent-rad-001",
    profession: "radiography",
    difficulty: 2,
    countryCode: "CA",
    setting: "Montreal imaging — bilingual city",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Radiographer",
    interlocutorRole: "Patient",
    patientAccent: "CA",
    accentContext: "French-Canadian patient prefers English but occasional French terms — explain MRI in clear English.",
    cardText: {
      overview: "Prepare claustrophobic patient for MRI brain.",
      patientDetails: "Mr Tremblay, 45, severe anxiety in enclosed spaces",
      yourTasks: ["Acknowledge anxiety", "Explain MRI steps", "Discuss panic button", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Panic attack last time", "Worried about results"],
      patientKnowledge: "Had CT before",
    },
    coaching: {
      iceQuestions: ["What happened last time?", "What would help you stay calm?"],
      structure: ["Empathy", "Steps", "Safety", "Check"],
      phrasesToAvoid: ["Just relax"],
      usefulPhrases: ["You hold a panic button and we talk throughout the scan."],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Tremblay, tell me what made the last scan difficult.", annotation: "ICE" },
      { speaker: "patient", line: "I felt trapped. I panicked." },
      { speaker: "candidate", line: "You'll have a buzzer — we stop immediately if you squeeze it.", annotation: "Reassurance + control" },
    ],
  },
  {
    id: "s-accent-sp-001",
    profession: "speech_pathology",
    difficulty: 2,
    countryCode: "UK",
    setting: "London paediatric clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Speech Pathologist",
    interlocutorRole: "Carer",
    patientAccent: "mixed",
    accentContext: "Polish mother, English second language — clear but grammatical errors. Child bilingual.",
    cardText: {
      overview: "Explain speech delay assessment to concerned parent.",
      patientDetails: "Tomasz, 4, limited English at nursery; mother Anna",
      yourTasks: ["Elicit language exposure at home", "Explain bilingual development", "Next assessment steps", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Nursery says he is behind", "Should stop Polish at home"],
      patientKnowledge: "Speaks Polish fluently at home",
    },
    coaching: {
      iceQuestions: ["What languages does Tomasz hear daily?", "What did nursery say?"],
      structure: ["History", "Normalize bilingualism", "Plan", "Check"],
      phrasesToAvoid: ["Only speak English"],
      usefulPhrases: ["Bilingual children may mix languages — this is not necessarily delay."],
      weakTags: ["speaking:ice-expectations", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Anna, what language do you use at home?", annotation: "History" },
      { speaker: "carer", line: "Polish at home, English at nursery. Teacher says he's slow." },
      { speaker: "candidate", line: "Bilingual development takes time — we'll assess both languages.", annotation: "Education" },
    ],
  },
  {
    id: "s-accent-vet-001",
    profession: "veterinary_science",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Auckland vet clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Veterinarian",
    interlocutorRole: "Pet owner",
    patientAccent: "AU",
    accentContext: "Australian tourist with sick dog in NZ — Australian accent.",
    cardText: {
      overview: "Explain parvovirus risk and isolation to travelling dog owner.",
      patientDetails: "Max, 8mo puppy, vomiting; owner Ms Price visiting from Sydney",
      yourTasks: ["Elicit vaccination history", "Explain parvo suspicion", "Isolation and costs", "Check understanding"],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot stay in NZ long", "Vaccination card lost"],
      patientKnowledge: "Puppy had 'some shots' at breeder",
    },
    coaching: {
      iceQuestions: ["What vaccinations has Max had?", "What concerns you most?"],
      structure: ["History", "Explain risk", "Plan", "Check"],
      phrasesToAvoid: ["He'll definitely die"],
      usefulPhrases: ["We'll test and isolate to protect other dogs in the clinic."],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Price, what vaccines did the breeder give Max?", annotation: "History" },
      { speaker: "patient", line: "I'm not sure — we lost the card. We're flying home Friday." },
      { speaker: "candidate", line: "Parvovirus is serious — isolation and fluids may be needed.", annotation: "Clear information" },
    ],
  },
];
