import type { RolePlayCard } from "./types";

export const DENTISTRY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-dent-001",
    profession: "dentistry",
    difficulty: 2,
    countryCode: "UK",
    setting: "Dental surgery — treatment room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dentist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain root canal treatment to an anxious patient with irreversible pulpitis.",
      patientDetails: "Ms Okonkwo, 34, severe pain UL6, radiograph shows periapical changes",
      yourTasks: [
        "Acknowledge pain and anxiety",
        "Explain treatment in lay terms",
        "Discuss alternatives and what to expect",
        "Check understanding and consent for language purposes",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Terrified of dental pain", "Had bad experience as a child"],
      patientKnowledge: "Knows tooth needs treatment, thinks extraction is only option",
    },
    coaching: {
      iceQuestions: ["How is the pain affecting you?", "What concerns you about treatment?"],
      structure: ["Empathy", "Explain RCT", "Alternatives", "Check understanding"],
      phrasesToAvoid: ["It won't hurt at all", "Just relax"],
      usefulPhrases: ["We'll use local anaesthetic so you stay comfortable.", "Root canal saves your natural tooth."],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Okonkwo, I can see you're in pain. Tell me how long it's been bothering you.", annotation: "Relationship building" },
      { speaker: "patient", line: "Three days. I'm scared of what you'll do." },
      { speaker: "candidate", line: "A root canal removes infected tissue inside the tooth and seals it — we can save the tooth.", annotation: "Information giving" },
      { speaker: "candidate", line: "What questions do you have before we proceed?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-dent-002",
    profession: "dentistry",
    difficulty: 2,
    countryCode: "AU",
    setting: "Dental practice — hygiene room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dentist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel a patient on improving oral hygiene after periodontal assessment.",
      patientDetails: "Mr Singh, 48, moderate gingivitis, smokes 10/day",
      yourTasks: [
        "Elicit current brushing/flossing habits",
        "Explain gum disease in accessible language",
        "Give practical hygiene advice including smoking",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Too busy to floss", "Thinks bleeding gums are normal"],
      patientKnowledge: "Brushes once daily, never flosses",
    },
    coaching: {
      iceQuestions: ["What does your daily oral care routine look like?", "What concerns you about your gums?"],
      structure: ["Assess habits", "Explain gingivitis", "Practical advice", "Check understanding"],
      phrasesToAvoid: ["You must floss perfectly", "Smoking doesn't matter"],
      usefulPhrases: ["Bleeding when you brush is a sign to improve gum care.", "Even 30 seconds of interdental cleaning helps."],
      weakTags: ["speaking:language", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Singh, walk me through how you look after your teeth each day.", annotation: "Information gathering" },
      { speaker: "patient", line: "Brush in the morning. Sometimes gums bleed — I thought that was normal." },
      { speaker: "candidate", line: "Bleeding suggests inflammation. Let's add interdental cleaning once daily.", annotation: "Information giving" },
      { speaker: "candidate", line: "Can you describe when you'll clean between your teeth?", annotation: "Check understanding" },
    ],
  },
];

export const PHYSIOTHERAPY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-phys-001",
    profession: "physiotherapy",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Physiotherapy clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physiotherapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain a home exercise programme for subacute low back pain.",
      patientDetails: "Mr Walsh, 38, office worker, 3 weeks lumbar pain without red flags",
      yourTasks: [
        "Elicit concerns about exercise and work",
        "Explain rationale for graded movement",
        "Teach 2–3 key exercises",
        "Check understanding and adherence plan",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears exercise will worsen pain", "Needs to return to desk job"],
      patientKnowledge: "Has been resting completely, taking ibuprofen",
    },
    coaching: {
      iceQuestions: ["What do you think caused the pain?", "What worries you about exercising?"],
      structure: ["ICE", "Explain approach", "Demonstrate exercises", "Check understanding"],
      phrasesToAvoid: ["No pain no gain", "Just push through it"],
      usefulPhrases: ["Gentle movement helps recovery — we'll start small.", "Let's set a realistic desk-break schedule."],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Walsh, what do you understand about why your back is sore?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Too much sitting. I'm scared moving will make it worse." },
      { speaker: "candidate", line: "We'll start with pelvic tilts — 10 reps, twice daily. I'll show you now.", annotation: "Information giving" },
      { speaker: "candidate", line: "When will you do these at home?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-phys-002",
    profession: "physiotherapy",
    difficulty: 2,
    countryCode: "CA",
    setting: "Hospital ward",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physiotherapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Mobilise an elderly patient anxious about walking after hip replacement.",
      patientDetails: "Mrs Dubois, 78, day 2 post total hip arthroplasty",
      yourTasks: [
        "Acknowledge fear of falling",
        "Explain precautions (hip precautions if applicable)",
        "Guide first steps with walker",
        "Check confidence and understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Terrified of dislocation", "Daughter said she should stay in bed"],
      patientKnowledge: "Knows she had hip surgery, unclear on weight-bearing",
    },
    coaching: {
      iceQuestions: ["How are you feeling about getting up?", "What have you heard about moving after surgery?"],
      structure: ["Empathy", "Explain safety", "Mobilise", "Check understanding"],
      phrasesToAvoid: ["You'll be fine", "Don't be afraid"],
      usefulPhrases: ["We'll go slowly with the walker — I'll stay beside you.", "Early walking reduces complications."],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Dubois, I understand you're nervous. What concerns you most about walking?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "My hip popping out. My daughter said I should stay in bed." },
      { speaker: "candidate", line: "We'll use the walker and follow your surgeon's precautions. Ready to try standing?", annotation: "Structured plan" },
      { speaker: "candidate", line: "Tell me what you'll do if you feel unsteady.", annotation: "Check understanding" },
    ],
  },
];

export const OCCUPATIONAL_THERAPY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-ot-001",
    profession: "occupational_therapy",
    difficulty: 2,
    countryCode: "UK",
    setting: "Patient's home — kitchen",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Occupational Therapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Advise on kitchen safety and energy conservation after stroke.",
      patientDetails: "Mr Hughes, 67, right-sided weakness, lives with spouse",
      yourTasks: [
        "Assess current kitchen routines and concerns",
        "Suggest practical modifications",
        "Teach pacing strategies",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Wants independence", "Frustrated by slow progress"],
      patientKnowledge: "Can make tea but drops items occasionally",
    },
    coaching: {
      iceQuestions: ["What activities are most important to you?", "What frustrates you in the kitchen?"],
      structure: ["Priorities", "Safety tips", "Pacing", "Check understanding"],
      phrasesToAvoid: ["You can't do that anymore"],
      usefulPhrases: ["Let's set up items between waist and shoulder height.", "Break tasks into smaller steps with rests."],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Hughes, what kitchen tasks matter most to you right now?", annotation: "Patient perspective" },
      { speaker: "patient", line: "Making breakfast without my wife helping." },
      { speaker: "candidate", line: "We'll move frequently used items to the counter — no reaching high.", annotation: "Information giving" },
      { speaker: "candidate", line: "How will you pace yourself when making breakfast?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-ot-002",
    profession: "occupational_therapy",
    difficulty: 2,
    countryCode: "AU",
    setting: "Rehabilitation unit",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Occupational Therapist",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Train a daughter to assist with safe transfers for her mother.",
      patientDetails: "Mrs Lee, 82, mobility decline; daughter is primary carer",
      yourTasks: [
        "Elicit carer's concerns and current technique",
        "Demonstrate safe transfer steps",
        "Discuss carer strain and resources",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Back pain from lifting", "Afraid of dropping mother"],
      patientKnowledge: "Has been pulling mother up by arms",
    },
    coaching: {
      iceQuestions: ["How have you been helping your mother move?", "What worries you most?"],
      structure: ["Assess technique", "Teach transfer", "Carer wellbeing", "Check understanding"],
      phrasesToAvoid: ["Just use your strength"],
      usefulPhrases: ["We'll use a pivot transfer — no lifting under the arms.", "It's okay to ask for equipment advice."],
      weakTags: ["speaking:language", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Tell me how you've been helping your mother stand up.", annotation: "Information gathering" },
      { speaker: "carer", line: "I pull her up by the arms. My back hurts." },
      { speaker: "candidate", line: "Let's try a pivot — count of three, she pushes from chair arms.", annotation: "Teaching" },
      { speaker: "candidate", line: "Can you talk me through the steps?", annotation: "Check understanding" },
    ],
  },
];

export const PODIATRY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-pod-001",
    profession: "podiatry",
    difficulty: 2,
    countryCode: "IE",
    setting: "Podiatry clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Podiatrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Educate a diabetic patient on daily foot inspection.",
      patientDetails: "Mr Byrne, 61, Type 2 diabetes, peripheral neuropathy",
      yourTasks: [
        "Assess current foot care habits",
        "Explain neuropathy and ulcer risk",
        "Teach daily inspection routine",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot see soles of feet easily", "Thinks numbness means no problem"],
      patientKnowledge: "Washes feet in shower, never inspects between toes",
    },
    coaching: {
      iceQuestions: ["How do you look after your feet at the moment?", "What concerns you about your feet?"],
      structure: ["Assess habits", "Explain risk", "Teach inspection", "Check understanding"],
      phrasesToAvoid: ["You'll definitely lose your foot"],
      usefulPhrases: ["Numbness means you might not feel injury — daily checks are essential.", "Use a mirror or ask someone to help see the soles."],
      weakTags: ["speaking:ice-expectations", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Byrne, walk me through how you care for your feet daily.", annotation: "Information gathering" },
      { speaker: "patient", line: "Wash in the shower. They're numb so I don't worry." },
      { speaker: "candidate", line: "Because of neuropathy, check soles and between toes each evening.", annotation: "Information giving" },
      { speaker: "candidate", line: "What will you do if you see a cut or blister?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-pod-002",
    profession: "podiatry",
    difficulty: 2,
    countryCode: "UK",
    setting: "Community podiatry",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Podiatrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Advise on footwear for plantar fasciitis.",
      patientDetails: "Ms Khan, 45, heel pain worse on first steps",
      yourTasks: [
        "Elicit activity and footwear habits",
        "Explain condition simply",
        "Recommend footwear and stretching",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Wants quick fix", "Wears flat ballet pumps to work"],
      patientKnowledge: "Has tried heel pads from pharmacy with minimal relief",
    },
    coaching: {
      iceQuestions: ["What shoes do you wear most days?", "What do you expect from treatment?"],
      structure: ["History", "Explain plantar fasciitis", "Footwear advice", "Check understanding"],
      phrasesToAvoid: ["Just buy expensive shoes"],
      usefulPhrases: ["Supportive shoes with a slight heel reduce morning pain.", "Stretching the calf twice daily helps."],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Khan, what footwear do you use for work?", annotation: "Information gathering" },
      { speaker: "patient", line: "Flat pumps. I need something that fixes this quickly." },
      { speaker: "candidate", line: "Plantar fasciitis improves with supportive shoes and calf stretches — let me explain.", annotation: "Information giving" },
      { speaker: "candidate", line: "What changes will you try this week?", annotation: "Check understanding" },
    ],
  },
];

export const OPTOMETRY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-opt-001",
    profession: "optometry",
    difficulty: 2,
    countryCode: "AU",
    setting: "Optometry practice",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Optometrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain early cataract findings and what monitoring involves.",
      patientDetails: "Mrs Tan, 68, mild nuclear sclerotic cataract — vision 6/9",
      yourTasks: [
        "Elicit concerns about vision and driving",
        "Explain cataract in lay terms",
        "Discuss monitoring and when surgery may be considered",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Afraid of going blind", "Needs to drive for work"],
      patientKnowledge: "Noticed glare at night, unclear what cataract means",
    },
    coaching: {
      iceQuestions: ["What changes have you noticed?", "What worries you about your vision?"],
      structure: ["ICE", "Explain cataract", "Monitoring plan", "Check understanding"],
      phrasesToAvoid: ["You need surgery now"],
      usefulPhrases: ["Cataract is clouding of the lens — usually gradual.", "We'll review yearly and discuss surgery when vision affects daily life."],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Tan, what changes have you noticed with your vision?", annotation: "Open question" },
      { speaker: "patient", line: "Glare when driving at night. Am I going blind?" },
      { speaker: "candidate", line: "You have early cataract — clouding of the lens. It's usually slow.", annotation: "Information giving" },
      { speaker: "candidate", line: "When would you contact us before your next review?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-opt-002",
    profession: "optometry",
    difficulty: 2,
    countryCode: "US",
    setting: "Optometry clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Optometrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel on contact lens hygiene after mild keratitis.",
      patientDetails: "Mr Garcia, 24, soft lens wearer, red eye after swimming in lenses",
      yourTasks: [
        "Elicit lens wear and hygiene habits",
        "Explain infection risk",
        "Give clear lens care instructions",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Wants to keep wearing lenses for sport", "Reuses solution to save money"],
      patientKnowledge: "Sleeps in lenses occasionally, swam in them once",
    },
    coaching: {
      iceQuestions: ["How do you usually care for your lenses?", "What concerns you about stopping lenses?"],
      structure: ["Assess habits", "Explain risk", "Hygiene rules", "Check understanding"],
      phrasesToAvoid: ["You'll damage your eyes forever"],
      usefulPhrases: ["Never swim or sleep in lenses unless specifically approved.", "Fresh solution every day — no topping up."],
      weakTags: ["speaking:language", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Talk me through your lens routine — cleaning, storage, how long you wear them.", annotation: "Information gathering" },
      { speaker: "patient", line: "I sleep in them sometimes. I swam in them last week." },
      { speaker: "candidate", line: "Water and sleep increase infection risk. No lenses for one week.", annotation: "Information giving" },
      { speaker: "candidate", line: "What will you do differently when you restart?", annotation: "Check understanding" },
    ],
  },
];

export const DIETETICS_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-diet-001",
    profession: "dietetics",
    difficulty: 2,
    countryCode: "CA",
    setting: "Outpatient clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dietitian",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Diet counselling for newly diagnosed coeliac disease.",
      patientDetails: "Ms Roy, 29, positive coeliac serology, awaiting biopsy",
      yourTasks: [
        "Elicit understanding and concerns about gluten-free diet",
        "Explain coeliac and gluten in accessible language",
        "Give practical shopping and eating-out advice",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Worried about cost and social eating", "Thinks 'a little gluten' is fine"],
      patientKnowledge: "Heard 'no bread' but unclear about sauces and cross-contamination",
    },
    coaching: {
      iceQuestions: ["What do you know about coeliac disease?", "What concerns you about changing your diet?"],
      structure: ["ICE", "Explain condition", "Practical tips", "Check understanding"],
      phrasesToAvoid: ["A little gluten won't hurt"],
      usefulPhrases: ["Even small amounts of gluten can damage the intestine.", "Look for certified gluten-free labels."],
      weakTags: ["speaking:ice-expectations", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Roy, what do you understand about why we're changing your diet?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "No bread. But surely a little won't matter?" },
      { speaker: "candidate", line: "Gluten triggers an immune reaction — strict avoidance is needed.", annotation: "Information giving" },
      { speaker: "candidate", line: "How will you check labels when shopping?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-diet-002",
    profession: "dietetics",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Hospital ward",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dietitian",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain renal diet modifications for CKD stage 4.",
      patientDetails: "Mr Patel, 58, eGFR 22, hyperkalaemia history",
      yourTasks: [
        "Assess current diet and knowledge",
        "Explain potassium and fluid restrictions simply",
        "Suggest practical meal adjustments",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Finds diet boring", "Family brings fruit baskets"],
      patientKnowledge: "Knows kidneys are 'weak', eats bananas daily",
    },
    coaching: {
      iceQuestions: ["What do you usually eat in a day?", "What concerns you about the diet changes?"],
      structure: ["Diet history", "Explain restrictions", "Practical swaps", "Check understanding"],
      phrasesToAvoid: ["You can never eat fruit again"],
      usefulPhrases: ["High-potassium fruits like bananas need limiting.", "Let's find alternatives you enjoy."],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Patel, describe what you ate yesterday.", annotation: "Information gathering" },
      { speaker: "patient", line: "Banana at breakfast. My family brings fruit — it's boring without it." },
      { speaker: "candidate", line: "With lower kidney function, potassium builds up — we'll limit bananas and swap to lower-potassium options.", annotation: "Information giving" },
      { speaker: "candidate", line: "What fruit will you choose instead?", annotation: "Check understanding" },
    ],
  },
];

export const RADIOGRAPHY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-rad-001",
    profession: "radiography",
    difficulty: 2,
    countryCode: "UK",
    setting: "Imaging department — CT room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Radiographer",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain CT abdomen with contrast to an anxious patient.",
      patientDetails: "Mrs Okafor, 55, suspected abdominal mass — fasting required",
      yourTasks: [
        "Acknowledge anxiety",
        "Explain procedure steps and contrast",
        "Discuss aftercare and when to seek help",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Claustrophobic", "Worried about contrast allergy"],
      patientKnowledge: "Had X-ray before, never CT",
    },
    coaching: {
      iceQuestions: ["Have you had a CT scan before?", "What concerns you about today's scan?"],
      structure: ["Empathy", "Procedure explanation", "Contrast info", "Check understanding"],
      phrasesToAvoid: ["Just lie still", "It'll be over quickly — don't worry"],
      usefulPhrases: ["You'll hear buzzing — I'll talk to you throughout.", "We'll check allergy history before contrast."],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Okafor, I see you're nervous. What worries you most about the scan?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Small spaces. And the injection." },
      { speaker: "candidate", line: "The scanner is open at both ends. Contrast helps show blood vessels — we'll monitor you.", annotation: "Information giving" },
      { speaker: "candidate", line: "What will you tell staff if you feel unwell after?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-rad-002",
    profession: "radiography",
    difficulty: 2,
    countryCode: "AU",
    setting: "Mammography suite",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Radiographer",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Prepare a patient for first mammogram who is embarrassed and worried.",
      patientDetails: "Ms Fletcher, 50, screening recall — never had mammogram",
      yourTasks: [
        "Elicit concerns and prior experience",
        "Explain procedure and positioning",
        "Discuss discomfort and privacy",
        "Check consent to proceed for language practice",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Embarrassed about undressing", "Friend said it was very painful"],
      patientKnowledge: "Knows it's for breast screening, unclear how long it takes",
    },
    coaching: {
      iceQuestions: ["What have you heard about mammograms?", "What concerns you today?"],
      structure: ["Empathy", "Explain steps", "Privacy reassurance", "Check understanding"],
      phrasesToAvoid: ["It's nothing to be embarrassed about"],
      usefulPhrases: ["You'll undress from the waist up — a gown is provided.", "Compression lasts only a few seconds per image."],
      weakTags: ["speaking:language", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Fletcher, have you had a mammogram before?", annotation: "Information gathering" },
      { speaker: "patient", line: "No. I'm embarrassed and my friend said it hurts." },
      { speaker: "candidate", line: "I'll explain each step — you control the pace. Compression is brief.", annotation: "Information giving" },
      { speaker: "candidate", line: "What would you like me to do if you need a pause?", annotation: "Check understanding" },
    ],
  },
];

export const SPEECH_PATHOLOGY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-sp-001",
    profession: "speech_pathology",
    difficulty: 2,
    countryCode: "AU",
    setting: "Community clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Speech Pathologist",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Explain dysphagia management and safe feeding to parent of child with cerebral palsy.",
      patientDetails: "Leo, 6, modified textures — mother attends session",
      yourTasks: [
        "Elicit carer's concerns about mealtimes",
        "Explain aspiration risk in accessible language",
        "Demonstrate safe feeding position",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Child refuses thickened fluids", "Feels judged by family"],
      patientKnowledge: "Knows child coughs with thin fluids, unclear why thickness matters",
    },
    coaching: {
      iceQuestions: ["What happens at mealtimes at home?", "What concerns you most about Leo's swallowing?"],
      structure: ["Mealtime history", "Explain risk", "Positioning demo", "Check understanding"],
      phrasesToAvoid: ["You're feeding him wrong"],
      usefulPhrases: ["Coughing with thin fluids suggests aspiration risk.", "Upright position with chin tuck helps safer swallows."],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Tell me what mealtimes look like at home — what goes well and what's hard?", annotation: "Information gathering" },
      { speaker: "carer", line: "He coughs with water. He hates the thickener." },
      { speaker: "candidate", line: "Thickened fluids slow the flow — reducing cough and chest risk.", annotation: "Information giving" },
      { speaker: "candidate", line: "Show me how you'll position Leo for a drink.", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-sp-002",
    profession: "speech_pathology",
    difficulty: 2,
    countryCode: "UK",
    setting: "Rehabilitation unit",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Speech Pathologist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain communication strategies after mild aphasia post-stroke.",
      patientDetails: "Mr Ellis, 62, word-finding difficulty, frustrated",
      yourTasks: [
        "Acknowledge frustration",
        "Explain aphasia and recovery expectations",
        "Teach one compensatory strategy",
        "Check understanding and agree practice plan",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Feels stupid", "Wants to return to work immediately"],
      patientKnowledge: "Knows words 'get stuck', unsure if permanent",
    },
    coaching: {
      iceQuestions: ["How has communication been since the stroke?", "What concerns you most?"],
      structure: ["Empathy", "Explain aphasia", "Strategy teaching", "Check understanding"],
      phrasesToAvoid: ["Your intelligence is affected"],
      usefulPhrases: ["Aphasia affects language, not intelligence.", "Using gestures or writing key words can help."],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Ellis, I can see this is frustrating. Tell me what happens when you speak.", annotation: "Patient perspective" },
      { speaker: "patient", line: "Words stuck. I feel stupid." },
      { speaker: "candidate", line: "Aphasia is a language difficulty — not thinking. Let's try writing the first letter to cue words.", annotation: "Information giving" },
      { speaker: "candidate", line: "When will you practise this at home?", annotation: "Check understanding" },
    ],
  },
];

export const VETERINARY_ROLE_CARDS: RolePlayCard[] = [
  {
    id: "s-vet-001",
    profession: "veterinary_science",
    difficulty: 2,
    countryCode: "AU",
    setting: "Small animal practice — consult room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Veterinarian",
    interlocutorRole: "Pet owner",
    cardText: {
      overview: "Explain post-operative care for a dog after cruciate repair.",
      patientDetails: "Bella, 4yo Labrador — owner is Ms Price",
      yourTasks: [
        "Elicit owner's concerns about recovery",
        "Explain rest and leash exercise restrictions",
        "Discuss pain signs and when to return",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Dog will be miserable without park runs", "Cost of follow-up"],
      patientKnowledge: "Knows surgery was on the knee, unclear on exercise limits",
    },
    coaching: {
      iceQuestions: ["What do you understand about Bella's surgery?", "What worries you about the next few weeks?"],
      structure: ["ICE", "Rest plan", "Warning signs", "Check understanding"],
      phrasesToAvoid: ["She'll be fine — just walk her"],
      usefulPhrases: ["Strict leash walks only for six weeks.", "Contact us if she won't bear weight or the wound opens."],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Price, what do you understand about Bella's knee surgery?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Cruciate repair. She loves the park — she'll be miserable indoors." },
      { speaker: "candidate", line: "Leash walks only — no off-lead for six weeks to protect the repair.", annotation: "Information giving" },
      { speaker: "candidate", line: "What signs would make you call the clinic?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-vet-002",
    profession: "veterinary_science",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Veterinary clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Veterinarian",
    interlocutorRole: "Pet owner",
    cardText: {
      overview: "Discuss diabetes management for a newly diagnosed cat.",
      patientDetails: "Milo, 12yo cat — owner is Mr Tan",
      yourTasks: [
        "Elicit owner's concerns about injections",
        "Explain diabetes and insulin routine",
        "Teach glucose monitoring signs at home",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot give injections", "Cat hides and bites"],
      patientKnowledge: "Knows cat drinks more, unclear about insulin timing",
    },
    coaching: {
      iceQuestions: ["What concerns you about treating Milo at home?", "What do you know about feline diabetes?"],
      structure: ["ICE", "Explain condition", "Injection teaching", "Check understanding"],
      phrasesToAvoid: ["It's easy — anyone can do it"],
      usefulPhrases: ["We'll practise injection technique with saline first.", "Watch for lethargy or wobbliness — low glucose signs."],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Tan, what worries you most about Milo's diabetes treatment?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Giving injections. He bites when scared." },
      { speaker: "candidate", line: "We'll use a quiet spot and reward after insulin. Let me demonstrate angle and site.", annotation: "Information giving" },
      { speaker: "candidate", line: "When would you call us about Milo's behaviour or appetite?", annotation: "Check understanding" },
    ],
  },
];

export const ALLIED_HEALTH_SPEAKING_CARDS: RolePlayCard[] = [
  ...DENTISTRY_ROLE_CARDS,
  ...PHYSIOTHERAPY_ROLE_CARDS,
  ...OCCUPATIONAL_THERAPY_ROLE_CARDS,
  ...PODIATRY_ROLE_CARDS,
  ...OPTOMETRY_ROLE_CARDS,
  ...DIETETICS_ROLE_CARDS,
  ...RADIOGRAPHY_ROLE_CARDS,
  ...SPEECH_PATHOLOGY_ROLE_CARDS,
  ...VETERINARY_ROLE_CARDS,
];
