import type { RolePlayCard } from "./types";

export const COUNTRY_WAVE2_SPEAKING: RolePlayCard[] = [
  // medicine — IE, NZ, CA
  {
    id: "s-med-ie-w2",
    profession: "medicine",
    difficulty: 2,
    countryCode: "IE",
    setting: "GP consultation room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "General Practitioner",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain why a bone density scan is recommended after a low-trauma wrist fracture.",
      patientDetails: "Mrs Byrne, 67, post-menopausal, fracture after tripping on kerb",
      yourTasks: [
        "Elicit ideas, concerns and expectations",
        "Explain osteoporosis screening rationale",
        "Discuss calcium, vitamin D and lifestyle measures",
        "Agree follow-up and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears medication side effects", "Sister had jaw problems on bisphosphonates"],
      patientKnowledge: "Knows bones get weaker with age, unsure about scans",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about why we are talking today?",
        "What worries you most about bone health?",
        "What would you like to get from this visit?",
      ],
      structure: ["ICE", "Explain DEXA rationale", "Lifestyle advice", "Follow-up plan", "Check understanding"],
      phrasesToAvoid: ["You're bound to break more bones", "Just take the tablets"],
      usefulPhrases: [
        "A low-trauma fracture can be a sign we should check bone density.",
        "We can discuss options step by step — not everyone needs medication immediately.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Byrne, thanks for coming in. What do you understand about why I wanted to see you?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "The hospital said my wrist broke too easily. I'm worried my bones are crumbling." },
      { speaker: "candidate", line: "What concerns you most about having a bone density scan?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "That you'll put me on tablets like my sister — she had jaw pain." },
      { speaker: "candidate", line: "A scan helps us see whether treatment is needed. We may start with calcium, vitamin D, and exercise.", annotation: "Information giving" },
      { speaker: "candidate", line: "I'll arrange the scan and review the result in two weeks. What questions do you have?", annotation: "Agree plan + check" },
    ],
  },
  {
    id: "s-med-nz-w2",
    profession: "medicine",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Outpatient clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physician",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel a patient with mild hypertension about starting lifestyle changes before medication.",
      patientDetails: "Mr Williams, 54, BP 148/92 on two readings, no target organ damage",
      yourTasks: [
        "Explore current diet, alcohol and activity",
        "Explain cardiovascular risk in plain language",
        "Agree realistic lifestyle targets",
        "Arrange review and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Does not want lifelong tablets", "Father died of stroke at 60"],
      patientKnowledge: "Knows BP was high at screening, drinks 4 beers most nights",
    },
    coaching: {
      iceQuestions: [
        "What do you already know about your blood pressure result?",
        "What concerns you about treatment?",
        "What changes feel realistic for you?",
      ],
      structure: ["ICE", "Risk explanation", "Lifestyle negotiation", "Follow-up", "Check understanding"],
      phrasesToAvoid: ["You must stop drinking completely", "Your BP is fine"],
      usefulPhrases: [
        "Many people prefer to try lifestyle changes first when readings are mildly raised.",
        "Even reducing alcohol by a few drinks can lower your risk.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Williams, your blood pressure was a little high. What do you know about that?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "The nurse mentioned hypertension. I don't want pills for life." },
      { speaker: "candidate", line: "What worries you most — medication or something else?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "My dad had a stroke young. I have four beers most nights." },
      { speaker: "candidate", line: "Let's try three months of salt reduction, walking, and cutting back alcohol, then recheck.", annotation: "Shared decision" },
      { speaker: "candidate", line: "Can you tell me one change you'll start this week?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-med-ca-w2",
    profession: "medicine",
    difficulty: 2,
    countryCode: "CA",
    setting: "Primary care clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Family Physician",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Discuss positive fecal immunochemical test result and need for colonoscopy.",
      patientDetails: "Ms Tremblay, 58, FIT positive, no rectal bleeding, family hx of polyps",
      yourTasks: [
        "Acknowledge anxiety about cancer",
        "Explain why colonoscopy is recommended",
        "Describe preparation at a high level",
        "Address barriers and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Terrified of colon cancer", "Worried about procedure discomfort and time off work"],
      patientKnowledge: "Completed home stool test, no symptoms",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about your test result?",
        "What concerns you most about the next step?",
        "What would help you feel ready to proceed?",
      ],
      structure: ["Empathy", "Explain FIT and colonoscopy", "Logistics", "Check understanding"],
      phrasesToAvoid: ["You definitely have cancer", "It's no big deal"],
      usefulPhrases: [
        "A positive FIT does not mean cancer — it means we need a clearer look.",
        "We use sedation so most people find the procedure manageable.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Tremblay, your stool test was positive. What have you heard about that?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "I googled it and I'm scared it's cancer." },
      { speaker: "candidate", line: "What worries you most about a colonoscopy?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "The prep, being off work, and what they might find." },
      { speaker: "candidate", line: "The test looks for polyps we can remove before they become cancer.", annotation: "Information giving" },
      { speaker: "candidate", line: "I'll refer you this week. What questions do you have about time off or the prep?", annotation: "Check understanding" },
    ],
  },
  // nursing — US, NZ, CA
  {
    id: "s-nurs-us-w2",
    profession: "nursing",
    difficulty: 2,
    countryCode: "US",
    setting: "Medical-surgical ward",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Registered Nurse",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Teach a patient how to use a new inhaler spacer after an asthma exacerbation admission.",
      patientDetails: "Mr Johnson, 62, discharged tomorrow on fluticasone/salmeterol MDI with spacer",
      yourTasks: [
        "Assess current inhaler technique and understanding",
        "Demonstrate correct spacer use",
        "Explain when to use rescue inhaler",
        "Check understanding and address concerns",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Thinks spacer is for children only", "Worried about steroid side effects"],
      patientKnowledge: "Used rescue inhaler for years, never had a spacer",
    },
    coaching: {
      iceQuestions: [
        "How do you usually take your inhalers at home?",
        "What concerns you about using this new device?",
        "What would help you feel confident before discharge?",
      ],
      structure: ["Assess knowledge", "Demonstrate technique", "Rescue vs preventer", "Check understanding"],
      phrasesToAvoid: ["Just shake and puff", "Spacers are optional"],
      usefulPhrases: [
        "The spacer helps more medicine reach your lungs.",
        "Show me how you would use it — we'll practice together.",
      ],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Johnson, before you go home, can you show me how you use your inhaler?", annotation: "Assess technique" },
      { speaker: "patient", line: "I shake it and breathe in. Do I really need that plastic tube?" },
      { speaker: "candidate", line: "What concerns you about the spacer or the new inhaler?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Steroids make you gain weight. The tube looks childish." },
      { speaker: "candidate", line: "Let me show you — one slow breath in through the spacer after pressing once.", annotation: "Demonstration" },
      { speaker: "candidate", line: "Use the blue rescue inhaler for sudden breathlessness. Can you talk me through both?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-nurs-nz-w2",
    profession: "nursing",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Postnatal ward",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Registered Nurse",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Support a new mother with breastfeeding latch difficulties on day two postpartum.",
      patientDetails: "Ms Williams, 28, first baby, nipple pain score 7/10, infant feeding every hour",
      yourTasks: [
        "Elicit feeding history and concerns",
        "Observe latch and suggest positioning changes",
        "Explain normal newborn feeding patterns",
        "Offer follow-up resources and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears baby is not getting enough milk", "Mother-in-law pushing formula"],
      patientKnowledge: "Attended antenatal class, cracked nipples since last night",
    },
    coaching: {
      iceQuestions: [
        "How has feeding been going since birth?",
        "What worries you most right now?",
        "What support do you have at home?",
      ],
      structure: ["ICE", "Observe latch", "Reassurance + technique", "Plan follow-up"],
      phrasesToAvoid: ["Just use formula", "Pain is normal — push through"],
      usefulPhrases: [
        "Frequent feeding is common on day two while milk is coming in.",
        "Let's adjust positioning to bring the baby closer — chin to breast first.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "How has breastfeeding been since yesterday?", annotation: "Open question" },
      { speaker: "patient", line: "It hurts badly and he feeds constantly. I think he's starving." },
      { speaker: "candidate", line: "What concerns you most about continuing?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "My mother-in-law says I should bottle-feed. My nipples are cracked." },
      { speaker: "candidate", line: "Let's try side-lying position and ensure a wide latch — lips flanged outward.", annotation: "Teaching" },
      { speaker: "candidate", line: "I'll arrange lactation follow-up tomorrow. What signs of good intake will you watch for?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-nurs-ca-w2",
    profession: "nursing",
    difficulty: 2,
    countryCode: "CA",
    setting: "Emergency department",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Registered Nurse",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Prepare a patient for wound suturing under local anaesthetic after a scalp laceration.",
      patientDetails: "Mr Tremblay, 19, 4 cm scalp cut from hockey injury, tetanus up to date",
      yourTasks: [
        "Explain procedure steps and sensations",
        "Address pain and cosmetic concerns",
        "Confirm allergy status and aftercare",
        "Check understanding and consent readiness",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Afraid of needles", "Worried about hair being shaved and scarring"],
      patientKnowledge: "Never had stitches before, coach told him to come to ED",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about what will happen next?",
        "What worries you most about the stitches?",
        "Have you had local anaesthetic before?",
      ],
      structure: ["Explain procedure", "Address fears", "Aftercare", "Check understanding"],
      phrasesToAvoid: ["It won't hurt at all", "Don't look"],
      usefulPhrases: [
        "You'll feel pressure during suturing but the local injection numbs the area first.",
        "We only clip hair minimally at the wound edge.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Tremblay, the doctor will suture your scalp. What do you know about that?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Needles freak me out. Will they shave half my head?" },
      { speaker: "candidate", line: "What concerns you most — pain, scarring, or something else?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Pain when they inject. And a big scar." },
      { speaker: "candidate", line: "I'll stay with you. You'll feel a sting briefly, then pressure only.", annotation: "Reassurance" },
      { speaker: "candidate", line: "Keep the wound dry 48 hours, then gentle wash. Any questions before we start?", annotation: "Check understanding" },
    ],
  },
  // pharmacy — US, IE, NZ, CA
  {
    id: "s-pharm-us-w2",
    profession: "pharmacy",
    difficulty: 2,
    countryCode: "US",
    setting: "Community pharmacy consultation room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Pharmacist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel a patient newly prescribed metformin for type 2 diabetes.",
      patientDetails: "Mrs Smith, 55, metformin 500mg BD, first diabetes medication",
      yourTasks: [
        "Elicit understanding and concerns about metformin",
        "Explain common gastrointestinal side effects and timing with meals",
        "Discuss sick-day rules and when to seek help",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Friend had kidney failure on diabetes pills", "Nausea with most medicines"],
      patientKnowledge: "Knows diet needs to change, never taken metformin",
    },
    coaching: {
      iceQuestions: [
        "What do you know about metformin?",
        "What concerns you about starting it?",
        "What questions do you want answered today?",
      ],
      structure: ["ICE", "Dosing with food", "Side effects", "Sick-day advice", "Check understanding"],
      phrasesToAvoid: ["Just take it", "Side effects are rare"],
      usefulPhrases: [
        "Taking it with meals often reduces stomach upset.",
        "If you vomit repeatedly or become dehydrated, contact your doctor.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Smith, I'm the pharmacist. What do you know about metformin?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "It lowers sugar. My friend said it ruined her kidneys." },
      { speaker: "candidate", line: "What worries you most about starting this medicine?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Nausea — most pills upset my stomach." },
      { speaker: "candidate", line: "Take it with breakfast and dinner. Mild nausea often settles in a week.", annotation: "Information giving" },
      { speaker: "candidate", line: "If you're unwell and not eating, call your doctor before taking doses. Any other questions?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-pharm-ie-w2",
    profession: "pharmacy",
    difficulty: 2,
    countryCode: "IE",
    setting: "Community pharmacy counter",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Pharmacist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Advise a patient requesting emergency contraception and discuss ongoing contraceptive options.",
      patientDetails: "Ms O'Brien, 24, condom failure yesterday, no regular contraception",
      yourTasks: [
        "Elicit timeline and medical history sensitively",
        "Explain levonorgestrel options and time window",
        "Discuss future contraception and STI screening",
        "Check understanding and privacy",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Embarrassed being seen by neighbours", "Worried pill will make her sick"],
      patientKnowledge: "Knows 'morning-after pill' exists, unsure of time limit",
    },
    coaching: {
      iceQuestions: [
        "How can I help you today?",
        "When did the condom break?",
        "What concerns you about taking emergency contraception?",
      ],
      structure: ["Sensitive greeting", "Timeline", "Options", "Future planning", "Check understanding"],
      phrasesToAvoid: ["You should have been more careful", "Everyone will know"],
      usefulPhrases: [
        "This is confidential. Levonorgestrel is most effective within 72 hours.",
        "We can talk about longer-term options when you're ready.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "How can I help you today, Ms O'Brien?", annotation: "Non-judgmental opening" },
      { speaker: "patient", line: "I need the morning-after pill. The condom broke last night." },
      { speaker: "candidate", line: "You're still within 72 hours. Any medicines or allergies I should know?", annotation: "History" },
      { speaker: "patient", line: "No. I'm worried I'll vomit and people in town will gossip." },
      { speaker: "candidate", line: "This consult is private. Take with food; a little nausea can happen.", annotation: "Reassurance + advice" },
      { speaker: "candidate", line: "Consider STI screening and regular contraception. What questions do you have?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-pharm-nz-w2",
    profession: "pharmacy",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Community pharmacy",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Pharmacist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Review inhaler technique for a patient with poorly controlled asthma using a dry powder device.",
      patientDetails: "Mr Williams, 35, budesonide/formoterol Turbuhaler, still using rescue inhaler daily",
      yourTasks: [
        "Assess current technique and adherence",
        "Demonstrate correct Turbuhaler use",
        "Explain preventer versus reliever roles",
        "Recommend GP review if symptoms persist",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Does not feel asthma is serious", "Uses blue inhaler before sport only"],
      patientKnowledge: "Rinses mouth sometimes, unsure if clicking means dose received",
    },
    coaching: {
      iceQuestions: [
        "Walk me through how you use your inhalers each day.",
        "What do you think the brown inhaler is for?",
        "What would success look like for you?",
      ],
      structure: ["Assess use", "Correct technique", "Preventer importance", "Safety net"],
      phrasesToAvoid: ["Your asthma isn't bad", "Just use the blue one"],
      usefulPhrases: [
        "The preventer reduces inflammation — the blue one is for sudden symptoms.",
        "Listen for the click and feel the powder — let's practice together.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Williams, show me how you use your brown inhaler.", annotation: "Technique check" },
      { speaker: "patient", line: "I twist and breathe. I mostly use the blue one before rugby." },
      { speaker: "candidate", line: "What do you think the brown inhaler does?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Not sure. I don't feel wheezy much." },
      { speaker: "candidate", line: "Use the brown one every morning and night even when well.", annotation: "Information giving" },
      { speaker: "candidate", line: "If you're using blue more than twice a week, see your GP. Can you demonstrate the twist again?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-pharm-ca-w2",
    profession: "pharmacy",
    difficulty: 2,
    countryCode: "CA",
    setting: "Community pharmacy",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Pharmacist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel a patient picking up isotretinoin under the pregnancy prevention programme.",
      patientDetails: "Ms Tremblay, 22, moderate acne, first isotretinoin prescription",
      yourTasks: [
        "Confirm pregnancy test requirements and contraception",
        "Explain teratogenic risk and common side effects",
        "Discuss alcohol, mood symptoms and lip care",
        "Check understanding and documentation",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Worried about depression rumours online", "Does not want parents to know about contraception"],
      patientKnowledge: "Signed programme forms, uses condoms inconsistently",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about this medication?",
        "What concerns you after reading about it online?",
        "What contraception are you using?",
      ],
      structure: ["Confirm programme rules", "Teratogenic counselling", "Side effects", "Check understanding"],
      phrasesToAvoid: ["It's perfectly safe", "Don't worry about pregnancy"],
      usefulPhrases: [
        "This medicine must not be taken in pregnancy — two forms of contraception are required.",
        "Report mood changes, severe headache, or vision changes promptly.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Tremblay, before you start isotretinoin, what do you know about the programme?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Monthly pregnancy tests. People online say it causes depression." },
      { speaker: "candidate", line: "What contraception are you using?", annotation: "Safety screening" },
      { speaker: "patient", line: "Condoms mostly. My parents can't know I'm on birth control pills." },
      { speaker: "candidate", line: "You need two reliable methods. Dry lips and sun sensitivity are common.", annotation: "Counselling" },
      { speaker: "candidate", line: "Contact us or your doctor if mood changes. Any questions about the test schedule?", annotation: "Check understanding" },
    ],
  },
  // dentistry — US, IE
  {
    id: "s-dent-us-w2",
    profession: "dentistry",
    difficulty: 2,
    countryCode: "US",
    setting: "Dental surgery",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dentist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain need for root canal treatment on a symptomatic molar with irreversible pulpitis.",
      patientDetails: "Mr Smith, 40, severe cold sensitivity UR6, no swelling",
      yourTasks: [
        "Elicit pain history and expectations",
        "Explain diagnosis and treatment options",
        "Discuss prognosis, cost and appointment plan",
        "Check understanding and obtain informed consent",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Had painful extraction as child", "Wants extraction instead to save money"],
      patientKnowledge: "Knows tooth is sensitive, thinks filling will fix it",
    },
    coaching: {
      iceQuestions: [
        "Tell me about the pain — when did it start?",
        "What do you think might be causing it?",
        "What would you like us to achieve today?",
      ],
      structure: ["History", "Diagnosis", "Options", "Consent check"],
      phrasesToAvoid: ["It will definitely hurt", "Just pull it out"],
      usefulPhrases: [
        "The nerve inside the tooth is inflamed — a root canal can save the tooth.",
        "Extraction is an option, but replacing the tooth has longer-term costs.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Smith, describe the pain you've been having.", annotation: "Open history" },
      { speaker: "patient", line: "Cold water makes me jump. I just want it pulled — cheaper." },
      { speaker: "candidate", line: "What concerns you about a root canal?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "I had a bad extraction as a kid. I thought a filling would fix it." },
      { speaker: "candidate", line: "The pulp is irreversibly inflamed. Root canal removes the nerve and seals the tooth.", annotation: "Information giving" },
      { speaker: "candidate", line: "We'll use local anaesthetic. Do you want to proceed or discuss extraction further?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-dent-ie-w2",
    profession: "dentistry",
    difficulty: 2,
    countryCode: "IE",
    setting: "Dental practice",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dentist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Discuss management of dental erosion linked to frequent energy drink consumption.",
      patientDetails: "Mr O'Brien, 29, sensitive front teeth, visible enamel thinning",
      yourTasks: [
        "Explore dietary habits non-judgmentally",
        "Explain erosion mechanism and prevention",
        "Recommend fluoride and behavioural changes",
        "Agree review plan and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Embarrassed about drinks at work", "Worried teeth are permanently ruined"],
      patientKnowledge: "Drinks 2–3 energy drinks daily for night shifts",
    },
    coaching: {
      iceQuestions: [
        "What do you drink during a typical shift?",
        "What concerns you about your teeth?",
        "What changes feel realistic?",
      ],
      structure: ["Diet history", "Explain erosion", "Prevention plan", "Check understanding"],
      phrasesToAvoid: ["You ruined your teeth", "Just stop drinking them"],
      usefulPhrases: [
        "Acidic drinks soften enamel — sipping frequently increases damage.",
        "Using a straw and rinsing with water afterwards can help.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr O'Brien, tell me about drinks you have during work.", annotation: "Non-judgmental history" },
      { speaker: "patient", line: "Two or three energy drinks on night shift. My front teeth feel thin." },
      { speaker: "candidate", line: "What worries you most about the appearance or sensitivity?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "They look dull. I thought I was just brushing too hard." },
      { speaker: "candidate", line: "Frequent acid exposure wears enamel. High-fluoride toothpaste and limiting sipping will help.", annotation: "Information giving" },
      { speaker: "candidate", line: "Review in three months. What one change will you try this week?", annotation: "Check understanding" },
    ],
  },
  // physiotherapy — US, IE
  {
    id: "s-phys-us-w2",
    profession: "physiotherapy",
    difficulty: 2,
    countryCode: "US",
    setting: "Outpatient physiotherapy clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physiotherapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain graded exposure for fear-avoidance in chronic whiplash-associated neck pain.",
      patientDetails: "Ms Smith, 38, MVA 3 months ago, avoids driving, NPRS 5/10",
      yourTasks: [
        "Elicit beliefs about movement and injury",
        "Explain hurt versus harm",
        "Agree small graded activity goals",
        "Check understanding and motivation",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears permanent spinal damage", "Attorney advised not to exercise"],
      patientKnowledge: "MRI showed mild disc bulge, wears soft collar intermittently",
    },
    coaching: {
      iceQuestions: [
        "What do you believe is causing your ongoing pain?",
        "What activities are you avoiding?",
        "What would you like to return to?",
      ],
      structure: ["ICE", "Reassurance", "Graded plan", "Check understanding"],
      phrasesToAvoid: ["No pain no gain", "It's all in your head"],
      usefulPhrases: [
        "Hurt does not always mean harm — gentle movement helps recovery.",
        "We'll increase driving time gradually, not all at once.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Smith, what do you think is keeping your neck pain going?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "The disc bulge. I'm scared driving will make it worse." },
      { speaker: "candidate", line: "What have you stopped doing since the accident?", annotation: "Functional assessment" },
      { speaker: "patient", line: "Driving more than ten minutes. My lawyer said don't gym." },
      { speaker: "candidate", line: "We'll start with five-minute drives and neck mobility exercises.", annotation: "Graded plan" },
      { speaker: "candidate", line: "Can you summarise your first goal before next session?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-phys-ie-w2",
    profession: "physiotherapy",
    difficulty: 2,
    countryCode: "IE",
    setting: "Hospital outpatient department",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physiotherapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Teach crutch walking partial weight-bearing after tibial plateau fracture.",
      patientDetails: "Mr O'Brien, 55, ORIF 4 weeks ago, permitted 50% weight-bearing",
      yourTasks: [
        "Confirm weight-bearing status and safety",
        "Demonstrate crutch gait pattern",
        "Explain home hazards and stair technique",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears crutches will damage repaired leg", "House has narrow stairs"],
      patientKnowledge: "Was non-weight-bearing 4 weeks, eager to return to farming",
    },
    coaching: {
      iceQuestions: [
        "What have you been told about putting weight on the leg?",
        "What worries you about using crutches at home?",
        "What tasks do you need to manage on the farm?",
      ],
      structure: ["Confirm status", "Demonstrate gait", "Home safety", "Check understanding"],
      phrasesToAvoid: ["Just hop along", "You'll be fine on stairs"],
      usefulPhrases: [
        "Place crutches first, then step with the sore leg to half weight.",
        "For stairs, up with the good leg, down with the sore leg.",
      ],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr O'Brien, what weight-bearing instructions did the surgeon give?", annotation: "Confirm status" },
      { speaker: "patient", line: "Half weight now. I'm afraid I'll break the plate." },
      { speaker: "candidate", line: "What concerns you about crutches on the farm?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Narrow stairs and muddy yard." },
      { speaker: "candidate", line: "Crutches move first, then the operated leg takes fifty percent.", annotation: "Demonstration" },
      { speaker: "candidate", line: "Show me how you'd climb one step. Any questions before you practice?", annotation: "Check understanding" },
    ],
  },
  // occupational therapy — US, IE
  {
    id: "s-ot-us-w2",
    profession: "occupational_therapy",
    difficulty: 2,
    countryCode: "US",
    setting: "Home visit",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Occupational Therapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Assess and advise on energy conservation for a patient with rheumatoid arthritis flare.",
      patientDetails: "Mrs Smith, 58, RA flare, struggles with morning self-care and meal prep",
      yourTasks: [
        "Explore daily routine and priority tasks",
        "Suggest pacing and joint protection strategies",
        "Recommend adaptive equipment if appropriate",
        "Agree realistic goals and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Feels like a burden to family", "Fears losing independence permanently"],
      patientKnowledge: "Uses jar in microwave to open lids, exhausted by noon",
    },
    coaching: {
      iceQuestions: [
        "Walk me through your morning — what is hardest?",
        "What matters most to you to keep doing yourself?",
        "What support do you have at home?",
      ],
      structure: ["Routine assessment", "Pacing strategies", "Equipment", "Goal setting"],
      phrasesToAvoid: ["Just rest all day", "Your family should do everything"],
      usefulPhrases: [
        "Alternate heavy and light tasks with seated breaks.",
        "A rocker knife and electric can opener can reduce grip force.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Smith, tell me about your morning routine and what's difficult.", annotation: "Open assessment" },
      { speaker: "patient", line: "Dressing and cooking exhaust me. My hands are swollen." },
      { speaker: "candidate", line: "What daily task matters most to keep doing yourself?", annotation: "ICE — Expectations" },
      { speaker: "patient", line: "Making breakfast. I don't want my husband doing everything." },
      { speaker: "candidate", line: "Prep items the night before and sit to chop vegetables.", annotation: "Strategy" },
      { speaker: "candidate", line: "Try a rocker knife this week. What will you change first?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-ot-ie-w2",
    profession: "occupational_therapy",
    difficulty: 2,
    countryCode: "IE",
    setting: "Rehabilitation unit",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Occupational Therapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Support cognitive strategies for a patient returning home after mild traumatic brain injury.",
      patientDetails: "Mr O'Brien, 32, post-concussion, memory lapses, wants to resume office work",
      yourTasks: [
        "Elicit cognitive difficulties and work demands",
        "Introduce compensatory strategies and pacing",
        "Discuss gradual return-to-work plan",
        "Check understanding and safety",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Employer may think he is malingering", "Forgets conversations with partner"],
      patientKnowledge: "Uses phone notes inconsistently, headaches by afternoon",
    },
    coaching: {
      iceQuestions: [
        "What tasks feel harder since the injury?",
        "What worries you about going back to work?",
        "What strategies have you tried so far?",
      ],
      structure: ["Assess difficulties", "Strategy teaching", "RTW plan", "Check understanding"],
      phrasesToAvoid: ["Push through headaches", "You're fine now"],
      usefulPhrases: [
        "External memory aids — calendars and alarms — reduce load on attention.",
        "A phased return with shorter hours prevents setback.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr O'Brien, what daily tasks feel harder since the concussion?", annotation: "Open question" },
      { speaker: "patient", line: "I forget meetings and my partner says I repeat myself." },
      { speaker: "candidate", line: "What concerns you about returning to the office?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "My boss thinks I'm skiving. Headaches hit by lunch." },
      { speaker: "candidate", line: "Use one calendar with alarms for every appointment.", annotation: "Strategy" },
      { speaker: "candidate", line: "Start with half days next week. How will you set reminders each morning?", annotation: "Check understanding" },
    ],
  },
  // podiatry — US
  {
    id: "s-pod-us-w2",
    profession: "podiatry",
    difficulty: 2,
    countryCode: "US",
    setting: "Podiatry clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Podiatrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain management of a painful ingrown toenail and partial nail procedure options.",
      patientDetails: "Mr Smith, 17, hallux ingrown nail, mild infection, basketball season",
      yourTasks: [
        "Elicit footwear and trimming habits",
        "Explain cause and treatment options",
        "Discuss aftercare and sport timing",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Afraid procedure will stop him playing playoffs", "Parent wants antibiotics only"],
      patientKnowledge: "Cuts nails curved, wears tight basketball shoes",
    },
    coaching: {
      iceQuestions: [
        "How long has the toe been sore?",
        "How do you usually trim your nails?",
        "What are your concerns about treatment?",
      ],
      structure: ["History", "Explain options", "Aftercare", "Check understanding"],
      phrasesToAvoid: ["Just cut it yourself", "Antibiotics alone will fix it"],
      usefulPhrases: [
        "Cutting nails straight across reduces recurrence.",
        "A partial nail edge removal is quick and usually heals in two weeks.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Smith, tell me when the toe started hurting.", annotation: "History" },
      { speaker: "patient", line: "Two weeks. Playoffs are next month — I can't miss games." },
      { speaker: "candidate", line: "How do you cut your toenails?", annotation: "Cause assessment" },
      { speaker: "patient", line: "Round at the sides. Dad says just give antibiotics." },
      { speaker: "candidate", line: "Antibiotics help infection but the edge may need partial removal.", annotation: "Information giving" },
      { speaker: "candidate", line: "Straight cuts and wider shoes afterward. Questions about recovery time?", annotation: "Check understanding" },
    ],
  },
  // optometry — IE, NZ
  {
    id: "s-opt-ie-w2",
    profession: "optometry",
    difficulty: 2,
    countryCode: "IE",
    setting: "Optometry practice",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Optometrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Discuss floaters and flashes and when urgent retinal review is needed.",
      patientDetails: "Mr O'Brien, 52, new floaters one week, occasional temporal flashes",
      yourTasks: [
        "Elicit symptom onset and characteristics",
        "Explain possible posterior vitreous detachment versus retinal tear",
        "Give clear safety-net advice",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Brother lost vision from detachment", "Worried about missing work"],
      patientKnowledge: "Noticed cobweb floaters, no curtain over vision",
    },
    coaching: {
      iceQuestions: [
        "When did you first notice the floaters?",
        "What worries you most about these symptoms?",
        "Have you had any vision loss or curtain effect?",
      ],
      structure: ["Symptom history", "Explain differentials", "Red flags", "Check understanding"],
      phrasesToAvoid: ["It's definitely nothing", "Ignore flashes"],
      usefulPhrases: [
        "New floaters with flashes need careful examination today.",
        "Come back immediately if you see a curtain or sudden vision loss.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr O'Brien, when did the floaters start?", annotation: "History" },
      { speaker: "patient", line: "About a week. My brother had a detached retina." },
      { speaker: "candidate", line: "Any flashes, curtain, or shadow in vision?", annotation: "Red flag screen" },
      { speaker: "patient", line: "Flashes at the side sometimes. No curtain." },
      { speaker: "candidate", line: "I'll dilate and examine the retina today to exclude a tear.", annotation: "Plan" },
      { speaker: "candidate", line: "If a dark curtain appears, attend emergency immediately. Any questions?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-opt-nz-w2",
    profession: "optometry",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Community optometry",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Optometrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Advise a teenager on myopia control options including orthokeratology and outdoor time.",
      patientDetails: "Ms Williams, 14, myopia −3.50D progressing, spends 6h daily on screens",
      yourTasks: [
        "Explore visual habits and parental concerns",
        "Explain myopia progression and control options",
        "Discuss outdoor time and break strategies",
        "Agree follow-up and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Does not want glasses in school photos", "Parent worried about contact lens infection"],
      patientKnowledge: "Prescription increased last year, uses tablet for homework",
    },
    coaching: {
      iceQuestions: [
        "What do you know about your prescription changing?",
        "What concerns you about contact lenses or other options?",
        "How much outdoor time do you get?",
      ],
      structure: ["Habits", "Explain progression", "Options", "Check understanding"],
      phrasesToAvoid: ["Screens are ruining your eyes", "Glasses will fix everything"],
      usefulPhrases: [
        "More outdoor light is linked to slower myopia progression.",
        "Orthokeratology lenses are worn overnight — we can discuss risks and hygiene.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Your prescription has increased again. What do you know about that?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "I'm more short-sighted. I hate thick glasses in photos." },
      { speaker: "candidate", line: "What concerns does your family have about contact lenses?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Mum worries about infections. I'm on screens all evening." },
      { speaker: "candidate", line: "Two hours outdoors daily and regular breaks help slow progression.", annotation: "Advice" },
      { speaker: "candidate", line: "We can discuss ortho-k or multifocal contacts at the next visit. Questions?", annotation: "Check understanding" },
    ],
  },
  // dietetics — US, IE
  {
    id: "s-diet-us-w2",
    profession: "dietetics",
    difficulty: 2,
    countryCode: "US",
    setting: "Outpatient dietetics clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dietitian",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel a patient with hyperlipidaemia on a Mediterranean-style eating pattern.",
      patientDetails: "Mr Smith, 50, LDL 4.2 mmol/L, BMI 28, eats fast food most lunches",
      yourTasks: [
        "Assess current eating pattern and readiness to change",
        "Explain heart-healthy fats and fibre goals",
        "Agree practical lunch swaps",
        "Check understanding and follow-up",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Thinks all fats are bad", "Work cafeteria limited options"],
      patientKnowledge: "Doctor mentioned cholesterol, wife cooks healthy dinners",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about your cholesterol result?",
        "What makes changing lunch habits difficult?",
        "What small change feels doable this week?",
      ],
      structure: ["Assess intake", "Explain pattern", "Practical swaps", "Check understanding"],
      phrasesToAvoid: ["Never eat fat again", "Just eat salad"],
      usefulPhrases: [
        "Olive oil, nuts, and fish can improve LDL when replacing saturated fats.",
        "Let's plan two lunches you can pack for work.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Smith, what do you know about your cholesterol?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "It's high. I thought I should cut all fat." },
      { speaker: "candidate", line: "What do you usually eat at lunch?", annotation: "Diet history" },
      { speaker: "patient", line: "Burger or fries near the site. Cafeteria salads look sad." },
      { speaker: "candidate", line: "Swap some saturated fat for olive oil, nuts, and grilled fish.", annotation: "Information giving" },
      { speaker: "candidate", line: "Try packed chicken wrap twice this week. What will you shop for?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-diet-ie-w2",
    profession: "dietetics",
    difficulty: 2,
    countryCode: "IE",
    setting: "Hospital outpatient",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dietitian",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Teach carbohydrate counting basics for a patient starting insulin pump therapy.",
      patientDetails: "Ms O'Brien, 26, type 1 diabetes, starting pump next week",
      yourTasks: [
        "Assess current carb estimation skills",
        "Explain carb ratios and correction factors simply",
        "Practice one meal example together",
        "Check understanding and safety",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Overwhelmed by maths", "Fears hypos at work"],
      patientKnowledge: "Uses fixed insulin doses, guesses portion sizes",
    },
    coaching: {
      iceQuestions: [
        "How do you currently decide insulin doses?",
        "What worries you about counting carbs?",
        "What would help you feel confident with the pump?",
      ],
      structure: ["Assess skills", "Teach ratio", "Worked example", "Check understanding"],
      phrasesToAvoid: ["It's easy maths", "You'll never have hypos"],
      usefulPhrases: [
        "One unit per ten grams of carb is your starting ratio — we'll adjust.",
        "Keep hypo treatment with you when doses change.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms O'Brien, how do you choose insulin doses now?", annotation: "Assess baseline" },
      { speaker: "patient", line: "Fixed units. I guess carbs — maths panics me." },
      { speaker: "candidate", line: "What concerns you about hypos when the pump starts?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Dropping low during retail shifts." },
      { speaker: "candidate", line: "If a sandwich is 40g carb and ratio is 1:10, you'd take four units.", annotation: "Worked example" },
      { speaker: "candidate", line: "Keep glucose tabs on you. Can you calculate lunch if I say 50g carb?", annotation: "Check understanding" },
    ],
  },
  // radiography — US, CA
  {
    id: "s-rad-us-w2",
    profession: "radiography",
    difficulty: 2,
    countryCode: "US",
    setting: "Imaging department",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Radiographer",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Prepare an anxious claustrophobic patient for MRI lumbar spine.",
      patientDetails: "Mrs Smith, 48, chronic back pain, never had MRI, mild claustrophobia",
      yourTasks: [
        "Explain procedure duration and sensations",
        "Address claustrophobia and coping options",
        "Confirm safety screening for metal",
        "Check understanding and consent",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Panic attack inside scanner", "Metal hip pin from youth unsure if safe"],
      patientKnowledge: "Heard MRI is loud and enclosed, wants diagnosis before surgery",
    },
    coaching: {
      iceQuestions: [
        "What do you know about the MRI scan today?",
        "What worries you most about the procedure?",
        "Have you ever had problems in enclosed spaces?",
      ],
      structure: ["Explain MRI", "Address anxiety", "Safety screen", "Check understanding"],
      phrasesToAvoid: ["Just lie still — it's quick", "There's nothing to worry about"],
      usefulPhrases: [
        "The table slides into a tunnel — you can squeeze an alarm bulb anytime.",
        "We can play music and use a mirror in some machines.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Smith, have you had an MRI before?", annotation: "Baseline" },
      { speaker: "patient", line: "No. I'm claustrophobic — I panic in lifts." },
      { speaker: "candidate", line: "What worries you most about today?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Being trapped. I had a hip pin years ago — is that safe?" },
      { speaker: "candidate", line: "We'll complete a metal checklist. You can stop the scan anytime with the buzzer.", annotation: "Safety + reassurance" },
      { speaker: "candidate", line: "Scan takes twenty minutes with knocking noises. Questions before we go in?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-rad-ca-w2",
    profession: "radiography",
    difficulty: 2,
    countryCode: "CA",
    setting: "Mammography suite",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Mammographer",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain first screening mammogram procedure to an anxious patient with family history of breast cancer.",
      patientDetails: "Ms Tremblay, 50, first mammogram, mother had breast cancer at 55",
      yourTasks: [
        "Acknowledge anxiety and family history",
        "Explain compression and step-by-step process",
        "Describe when results are available",
        "Check understanding and consent",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Terrified of finding cancer", "Heard compression is extremely painful"],
      patientKnowledge: "Received screening letter, unsure why at 50",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about why you're here today?",
        "What concerns you most about the mammogram?",
        "What support do you have if results need follow-up?",
      ],
      structure: ["Empathy", "Explain procedure", "Results timeline", "Check understanding"],
      phrasesToAvoid: ["It won't hurt", "You're definitely fine"],
      usefulPhrases: [
        "Compression lasts seconds to get a clear image.",
        "Most results return within two weeks — we'll explain next steps if recall is needed.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Tremblay, this is your first screening mammogram. What do you know about it?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "My mother had breast cancer. I'm scared we'll find something." },
      { speaker: "candidate", line: "What worries you most about the test itself?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "People say the squeeze is unbearable." },
      { speaker: "candidate", line: "I'll compress briefly for each image — tell me if pain is too much.", annotation: "Procedure explanation" },
      { speaker: "candidate", line: "Results usually arrive in two weeks. Ready to proceed?", annotation: "Check understanding" },
    ],
  },
  // speech pathology — US
  {
    id: "s-sp-us-w2",
    profession: "speech_pathology",
    difficulty: 2,
    countryCode: "US",
    setting: "Outpatient speech clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Speech-Language Pathologist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel an adult after mild stroke on word-finding difficulty (anomia) and communication strategies.",
      patientDetails: "Mr Smith, 63, stroke 6 weeks ago, frustrated with 'tip of tongue' pauses",
      yourTasks: [
        "Acknowledge frustration and impact on confidence",
        "Explain anomia and expected recovery pattern",
        "Teach one compensatory strategy",
        "Agree home practice and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Colleagues think he is confused", "Fears second stroke if he talks too much"],
      patientKnowledge: "Speech clearer than first week, avoids phone calls",
    },
    coaching: {
      iceQuestions: [
        "Tell me how communication has been since the stroke.",
        "What situations are hardest?",
        "What would improving speech help you do?",
      ],
      structure: ["Empathy", "Explain anomia", "Strategy teaching", "Home plan"],
      phrasesToAvoid: ["Just think harder", "Your intelligence is gone"],
      usefulPhrases: [
        "Word-finding often improves with practice — pauses don't mean confusion.",
        "Describe the word or use a gesture while searching.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Smith, how has talking been since your stroke?", annotation: "Open question" },
      { speaker: "patient", line: "I know the word but it won't come out. I avoid phone calls." },
      { speaker: "candidate", line: "What worries you when words don't come?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Coworkers think I'm slow. I'm scared talking triggers another stroke." },
      { speaker: "candidate", line: "Describe the item or use a gesture — for 'watch', point to your wrist.", annotation: "Strategy" },
      { speaker: "candidate", line: "Practice ten minutes daily with your wife. What strategy will you try first?", annotation: "Check understanding" },
    ],
  },
  // veterinary science — US, IE
  {
    id: "s-vet-us-w2",
    profession: "veterinary_science",
    difficulty: 2,
    countryCode: "US",
    setting: "Small animal clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Veterinarian",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Discuss diagnosis and home care for feline lower urinary tract disease in a male cat.",
      patientDetails: "Whiskers, 4y male DSH, straining to urinate, indoor cat, overweight",
      yourTasks: [
        "Explain likely FLUTD and rule-out urgency",
        "Discuss litter box, diet and water intake changes",
        "Give emergency signs of obstruction",
        "Check understanding with owner",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot afford hospitalization", "Previous cat blocked and needed surgery"],
      patientKnowledge: "Noticed frequent litter visits today, some blood in urine",
    },
    coaching: {
      iceQuestions: [
        "What changes have you noticed in Whiskers' urination?",
        "What concerns you most today?",
        "What did happen with your previous cat?",
      ],
      structure: ["History", "Explain FLUTD", "Home plan", "Emergency signs"],
      phrasesToAvoid: ["He's fine — go home", "Obstruction is rare"],
      usefulPhrases: [
        "Male cats can obstruct — straining with no urine is an emergency.",
        "Wet food and extra water bowls reduce recurrence risk.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Tell me what you've noticed with Whiskers' litter tray today.", annotation: "History" },
      { speaker: "carer", line: "He's going in and out. I saw a little blood. My last cat blocked." },
      { speaker: "candidate", line: "What worries you most right now?", annotation: "ICE — Concerns" },
      { speaker: "carer", line: "Cost of hospital stay. I can't afford surgery again." },
      { speaker: "candidate", line: "Today he is passing urine. Wet food and fountains help prevent crystals.", annotation: "Plan" },
      { speaker: "candidate", line: "If he strains and produces nothing, come immediately. Any questions?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-vet-ie-w2",
    profession: "veterinary_science",
    difficulty: 2,
    countryCode: "IE",
    setting: "Farm call-out",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Veterinarian",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Advise a farmer on mastitis management and milk withdrawal after treating a dairy cow.",
      patientDetails: "Cow Tag 247, 5y Holstein, swollen quarter, milk clots, still in lactation",
      yourTasks: [
        "Explain likely mastitis and treatment plan",
        "Discuss milk withdrawal periods and records",
        "Review milking hygiene and biosecurity",
        "Check understanding with farmer",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot afford to dump milk all week", "Worried about bulk tank contamination"],
      patientKnowledge: "Noticed clots this morning, cow off feed slightly",
    },
    coaching: {
      iceQuestions: [
        "When did you first notice the udder change?",
        "What concerns you about treatment and milk?",
        "How do you usually record withdrawals?",
      ],
      structure: ["Assessment", "Treatment plan", "Withdrawal rules", "Prevention"],
      phrasesToAvoid: ["Just keep milking into the tank", "One dose fixes it"],
      usefulPhrases: [
        "Antibiotic milk must not enter the bulk tank until withdrawal ends.",
        "Strip cups and teat dip reduce spread to other cows.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "When did you notice the swollen quarter?", annotation: "History" },
      { speaker: "carer", line: "This morning — clots in milk. She ate less." },
      { speaker: "candidate", line: "What worries you about treating her?", annotation: "ICE — Concerns" },
      { speaker: "carer", line: "Dumping milk for days. I can't contaminate the tank." },
      { speaker: "candidate", line: "Intramammary antibiotics with seventy-two hour milk withdrawal.", annotation: "Treatment" },
      { speaker: "candidate", line: "Mark the cow and record dates. Questions about hygiene or withholding?", annotation: "Check understanding" },
    ],
  },
];
