import type { RolePlayCard } from "./types";

export const COUNTRY_WAVE3_SPEAKING: RolePlayCard[] = [
  // medicine — AU
  {
    id: "s-med-au-w3",
    profession: "medicine",
    difficulty: 2,
    countryCode: "AU",
    setting: "GP consultation room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "General Practitioner",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel a patient on warfarin after a new atrial fibrillation diagnosis and explain INR monitoring.",
      patientDetails: "Mr Nguyen, 71, new AF, CHA₂DS₂-VASc 3, started warfarin last week",
      yourTasks: [
        "Elicit ideas, concerns and expectations about anticoagulation",
        "Explain INR testing and target range",
        "Discuss bleeding precautions and interactions",
        "Agree follow-up and check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears brain bleed", "Neighbour fell on warfarin and bruised badly"],
      patientKnowledge: "Knows tablet is for 'thin blood', eats grapefruit and green salads daily",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about why you are taking warfarin?",
        "What worries you most about this medication?",
        "What would help you feel confident managing it?",
      ],
      structure: ["ICE", "Explain INR", "Safety advice", "Follow-up", "Check understanding"],
      phrasesToAvoid: ["You'll definitely bleed", "Stop your vegetables"],
      usefulPhrases: [
        "INR checks tell us if your dose is in the safe range.",
        "Keep vitamin K intake steady — don't suddenly eat lots more or less green veg.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Nguyen, what do you understand about the warfarin you started?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "It thins my blood for the irregular heartbeat. I'm scared of a brain bleed." },
      { speaker: "candidate", line: "What concerns you most day to day?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "My neighbour bruised terribly. I eat salads and grapefruit every morning." },
      { speaker: "candidate", line: "We'll check INR regularly — usually two to three for your target.", annotation: "Information giving" },
      { speaker: "candidate", line: "Report unusual bruising or bleeding. Keep greens steady, not absent. Questions?", annotation: "Safety + check" },
    ],
  },
  // nursing — UK
  {
    id: "s-nurs-uk-w3",
    profession: "nursing",
    difficulty: 2,
    countryCode: "UK",
    setting: "Cardiology ward — bedside",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Registered Nurse",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Teach heart failure self-management before discharge — daily weights and fluid limits.",
      patientDetails: "Mrs Patel, 68, new HF diagnosis, ejection fraction 35%, mild ankle oedema",
      yourTasks: [
        "Assess current understanding of heart failure",
        "Explain daily weight monitoring and fluid restriction",
        "Discuss when to seek urgent help",
        "Check understanding and confidence",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Lives alone", "Thinks fluid limit means no water at all"],
      patientKnowledge: "Knows heart is 'weak', drinks 3L tea daily, no scales at home",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about your heart failure?",
        "What concerns you about managing this at home?",
        "Who can support you after discharge?",
      ],
      structure: ["Assess knowledge", "Weight plan", "Fluid advice", "Red flags", "Check understanding"],
      phrasesToAvoid: ["Just drink less", "You'll be readmitted"],
      usefulPhrases: [
        "Weigh yourself every morning — report a gain of two kilos in three days.",
        "Fluid restriction means a daily limit, not stopping water entirely.",
      ],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Patel, what do you know about why you were admitted?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "My heart isn't pumping well. I live alone — I'm scared at home." },
      { speaker: "candidate", line: "What worries you most about fluids and swelling?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "I drink lots of tea. Does fluid limit mean no water?" },
      { speaker: "candidate", line: "We'll aim for 1.5 litres daily including tea. Weigh each morning.", annotation: "Teaching" },
      { speaker: "candidate", line: "Call us if weight jumps two kilos in three days. Can you repeat the plan?", annotation: "Check understanding" },
    ],
  },
  // dentistry — NZ, CA
  {
    id: "s-dent-nz-w3",
    profession: "dentistry",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Dental surgery",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dentist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel a young adult on surgical removal of an impacted lower wisdom tooth.",
      patientDetails: "Ms Williams, 22, symptomatic LL8 impaction, recurrent pericoronitis",
      yourTasks: [
        "Elicit pain history and expectations",
        "Explain surgical extraction and anaesthesia",
        "Discuss post-op swelling and aftercare",
        "Check understanding and consent",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Terrified of nerve damage", "Needs to work retail shifts in three days"],
      patientKnowledge: "Gum flares behind back tooth, friend had dry socket",
    },
    coaching: {
      iceQuestions: [
        "Tell me about the episodes of pain behind your back tooth.",
        "What concerns you about having it removed?",
        "What do you need to plan for after surgery?",
      ],
      structure: ["History", "Explain procedure", "Aftercare", "Check understanding"],
      phrasesToAvoid: ["You'll be numb forever", "It's a simple pull"],
      usefulPhrases: [
        "Because the tooth is impacted, we make a small flap and section the tooth.",
        "Swelling peaks at 48 hours — soft diet and salt rinses help healing.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Williams, describe the pain you've had behind your lower back tooth.", annotation: "History" },
      { speaker: "patient", line: "It flares every few weeks. I'm scared of permanent lip numbness." },
      { speaker: "candidate", line: "What do you need to arrange for work after surgery?", annotation: "ICE — Expectations" },
      { speaker: "patient", line: "Retail shifts in three days. My friend had dry socket." },
      { speaker: "candidate", line: "We'll use local anaesthetic and may section the tooth. Nerve injury is uncommon.", annotation: "Information giving" },
      { speaker: "candidate", line: "Plan two rest days, soft food, no smoking. Questions before we book?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-dent-ca-w3",
    profession: "dentistry",
    difficulty: 2,
    countryCode: "CA",
    setting: "Dental hygiene room",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dentist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain periodontal disease and need for scaling and root planing.",
      patientDetails: "Mr Tremblay, 52, generalized 5mm pockets, bleeding on probing, former smoker",
      yourTasks: [
        "Elicit oral hygiene habits and concerns",
        "Explain periodontitis in lay terms",
        "Describe deep cleaning appointments and maintenance",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Thinks deep cleaning is cosmetic only", "Quit smoking two years ago, embarrassed"],
      patientKnowledge: "Gums bleed when flossing, brushes once daily, no prior perio treatment",
    },
    coaching: {
      iceQuestions: [
        "What do you notice when you brush or floss?",
        "What do you understand about gum disease?",
        "What would success look like for you?",
      ],
      structure: ["Assess habits", "Explain periodontitis", "Treatment plan", "Check understanding"],
      phrasesToAvoid: ["Your gums are hopeless", "Flossing doesn't matter"],
      usefulPhrases: [
        "Pockets mean bacteria sit below the gum line — scaling reaches those areas.",
        "Quitting smoking helped — maintenance visits every three months protect bone.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Tremblay, what happens when you floss your back teeth?", annotation: "Information gathering" },
      { speaker: "patient", line: "Bleeding. I quit smoking two years ago — I thought that fixed it." },
      { speaker: "candidate", line: "What do you think deep cleaning achieves?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Just polish stains? I'm embarrassed it's this bad." },
      { speaker: "candidate", line: "Periodontitis damages supporting bone. Root planing removes bacteria below the gum.", annotation: "Information giving" },
      { speaker: "candidate", line: "Two longer visits, then three-month maintenance. What will you change daily?", annotation: "Check understanding" },
    ],
  },
  // physiotherapy — UK, AU
  {
    id: "s-phys-uk-w3",
    profession: "physiotherapy",
    difficulty: 2,
    countryCode: "UK",
    setting: "Musculoskeletal clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physiotherapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain exercise-based management for rotator cuff-related shoulder pain.",
      patientDetails: "Mr Hughes, 49, painter, painful arc, no red flags, ultrasound tendinopathy",
      yourTasks: [
        "Elicit functional limitations and beliefs about movement",
        "Explain tendinopathy and graded loading",
        "Teach two home exercises",
        "Check understanding and adherence plan",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears tearing tendon if he lifts", "Needs overhead work in two weeks"],
      patientKnowledge: "Resting arm in sling self-prescribed, takes ibuprofen daily",
    },
    coaching: {
      iceQuestions: [
        "What do you think is causing the shoulder pain?",
        "What activities are you avoiding?",
        "What work tasks must you return to?",
      ],
      structure: ["ICE", "Explain tendinopathy", "Exercise prescription", "Check understanding"],
      phrasesToAvoid: ["No pain no gain", "Stop all overhead work forever"],
      usefulPhrases: [
        "Tendons adapt to gradual load — complete rest often prolongs pain.",
        "We'll start below painful arc with scapular setting and isometrics.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Hughes, what do you believe is wrong with your shoulder?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Torn tendon. I've kept it in a sling — lifting will shred it." },
      { speaker: "candidate", line: "What work tasks are hardest right now?", annotation: "Functional assessment" },
      { speaker: "patient", line: "Overhead painting in two weeks. Ibuprofen daily." },
      { speaker: "candidate", line: "Tendinopathy responds to graded loading. Try scapular squeezes ten reps, twice daily.", annotation: "Information giving" },
      { speaker: "candidate", line: "When will you practise these? Any questions about pain during exercise?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-phys-au-w3",
    profession: "physiotherapy",
    difficulty: 2,
    countryCode: "AU",
    setting: "Sports physiotherapy clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Physiotherapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Discuss return-to-sport criteria after ACL reconstruction at twelve weeks.",
      patientDetails: "Mr Tan, 24, ACLR hamstring graft 12 weeks ago, wants to resume football",
      yourTasks: [
        "Elicit goals and previous rehab adherence",
        "Explain graft healing timeline and criteria-based progression",
        "Outline next-phase strengthening and agility",
        "Check understanding and agree goals",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Teammates returning sooner", "Fears re-injury on cutting movements"],
      patientKnowledge: "Walking well, occasional knee stiffness, skipped last two physio sessions",
    },
    coaching: {
      iceQuestions: [
        "What is your goal for football this season?",
        "What concerns you about returning?",
        "How has home exercise been going?",
      ],
      structure: ["Goals", "Explain timeline", "Criteria testing", "Check understanding"],
      phrasesToAvoid: ["You're ready now", "Never play again"],
      usefulPhrases: [
        "Return to sport follows strength and hop tests, not just weeks on calendar.",
        "Twelve weeks is early for cutting — we'll build single-leg control first.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Tan, what are you hoping to achieve with football this year?", annotation: "ICE — Expectations" },
      { speaker: "patient", line: "Under-eighteens in six weeks. Mates returned at three months." },
      { speaker: "candidate", line: "What worries you about cutting and tackling?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Re-tearing it. I missed two physio sessions — knee stiff mornings." },
      { speaker: "candidate", line: "Graft remodelling continues — we test hop symmetry before agility.", annotation: "Information giving" },
      { speaker: "candidate", line: "Next phase adds single-leg squats and jog-straight lines. Agree on weekly homework?", annotation: "Check understanding" },
    ],
  },
  // occupational therapy — NZ, CA
  {
    id: "s-ot-nz-w3",
    profession: "occupational_therapy",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Community rehabilitation",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Occupational Therapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Advise on return-to-driving after mild stroke — safety assessment and gradual resumption.",
      patientDetails: "Mr Walsh, 58, stroke 8 weeks ago, mild left neglect, wants to drive to farm",
      yourTasks: [
        "Explore driving needs and current community mobility",
        "Explain on-road assessment requirements",
        "Discuss interim transport options",
        "Check understanding and safety",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Loss of independence on remote property", "Embarrassed to ask wife for lifts"],
      patientKnowledge: "Driving short local trips, sometimes drifts lane, unaware of formal assessment",
    },
    coaching: {
      iceQuestions: [
        "What driving do you need to do each week?",
        "What has changed when you drive since the stroke?",
        "What support is available if you pause driving?",
      ],
      structure: ["Assess driving", "Explain assessment", "Alternatives", "Check understanding"],
      phrasesToAvoid: ["You're fine to drive", "You'll never drive again"],
      usefulPhrases: [
        "A formal on-road assessment checks reaction, vision and attention.",
        "Rural trips can wait until assessment — let's plan farm errands meanwhile.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Walsh, what driving do you need for the farm and family?", annotation: "Patient perspective" },
      { speaker: "patient", line: "Daily feed runs. I drift lanes sometimes — I don't want my wife driving me." },
      { speaker: "candidate", line: "What have you noticed since the stroke when behind the wheel?", annotation: "Safety screen" },
      { speaker: "patient", line: "Slower reactions. I didn't know I needed an official test." },
      { speaker: "candidate", line: "An occupational therapy on-road assessment is required before full return.", annotation: "Information giving" },
      { speaker: "candidate", line: "Pause long rural trips until then. Who can cover feed runs this week?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-ot-ca-w3",
    profession: "occupational_therapy",
    difficulty: 2,
    countryCode: "CA",
    setting: "Home visit — bathroom",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Occupational Therapist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Recommend bathroom safety modifications for an older adult with osteoporosis.",
      patientDetails: "Mrs Dubois, 79, osteoporosis, recent bathroom slip, lives alone",
      yourTasks: [
        "Assess current bathroom setup and falls history",
        "Suggest grab bars, lighting and non-slip measures",
        "Discuss fear of falling and pacing",
        "Check understanding and agree changes",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Does not want institutional-looking rails", "Fixed income limits renovations"],
      patientKnowledge: "Slipped stepping out of tub, uses towel bar for balance, night trips without light",
    },
    coaching: {
      iceQuestions: [
        "Walk me through your bathroom routine — what happened when you slipped?",
        "What changes feel acceptable in your home?",
        "What worries you about falling again?",
      ],
      structure: ["Falls history", "Environmental mods", "Behaviour tips", "Check understanding"],
      phrasesToAvoid: ["You need a full renovation", "Just be careful"],
      usefulPhrases: [
        "Proper grab bars bolt to studs — towel bars are not safe to lean on.",
        "A rubber mat and night-light are low-cost changes with big impact.",
      ],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Dubois, tell me what happened when you slipped in the bathroom.", annotation: "Falls history" },
      { speaker: "patient", line: "Stepping over the tub edge. I grab the towel rail — it wobbles." },
      { speaker: "candidate", line: "What concerns you about adding safety equipment?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Ugly hospital bars. I can't afford big renovations." },
      { speaker: "candidate", line: "We can add a matte grab bar by the tub and a non-slip mat.", annotation: "Recommendations" },
      { speaker: "candidate", line: "Use a night-light for toilet trips. Which change will you arrange first?", annotation: "Check understanding" },
    ],
  },
  // podiatry — AU, NZ, CA
  {
    id: "s-pod-au-w3",
    profession: "podiatry",
    difficulty: 2,
    countryCode: "AU",
    setting: "Podiatry clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Podiatrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Discuss treatment options for a painful plantar verruca in a school-age child.",
      patientDetails: "Liam, 10, plantar wart 3 months, painful with sport, mother attends",
      yourTasks: [
        "Elicit duration, pain and prior home treatments",
        "Explain verruca versus corn and treatment options",
        "Discuss expectations and self-care between visits",
        "Check understanding with parent and child",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Mother wants immediate cure before carnival", "Child afraid of acid burns"],
      patientKnowledge: "Tried duct tape two weeks, plays barefoot at beach",
    },
    coaching: {
      iceQuestions: [
        "How long has the sore spot been bothering Liam?",
        "What treatments have you tried at home?",
        "What are your concerns about clinic treatment?",
      ],
      structure: ["History", "Explain verruca", "Options", "Check understanding"],
      phrasesToAvoid: ["It will vanish in one visit", "Warts mean poor hygiene"],
      usefulPhrases: [
        "Verrucae often need several sessions — salicylic acid or cryotherapy are common options.",
        "Cover at the pool to reduce spread and protect the area.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "How long has the painful spot been on Liam's foot?", annotation: "History" },
      { speaker: "patient", line: "Three months. School carnival is next month — we need it gone." },
      { speaker: "candidate", line: "What home treatments have you tried?", annotation: "Prior treatment" },
      { speaker: "patient", line: "Duct tape. He's scared acid will burn like his mate said." },
      { speaker: "candidate", line: "It's a verruca — a virus in the skin. We may use salicylic acid with regular paring.", annotation: "Information giving" },
      { speaker: "candidate", line: "Several visits are normal. Cover it at the beach. Questions about aftercare?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-pod-nz-w3",
    profession: "podiatry",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Sports podiatry clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Podiatrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Manage a metatarsal stress fracture in a recreational runner — load modification plan.",
      patientDetails: "Ms Williams, 34, second metatarsal stress fracture, increased half-marathon training",
      yourTasks: [
        "Explore training load and footwear",
        "Explain bone healing and activity modification",
        "Recommend immobilisation and return-to-run criteria",
        "Check understanding",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Race entry non-refundable", "Fears losing fitness completely"],
      patientKnowledge: "Sharp forefoot pain four weeks, ran through it until limping",
    },
    coaching: {
      iceQuestions: [
        "Describe your training before the pain started.",
        "What worries you about resting?",
        "What footwear do you use for running?",
      ],
      structure: ["Training history", "Explain fracture", "Modified activity", "Check understanding"],
      phrasesToAvoid: ["Just run through it", "You'll never race again"],
      usefulPhrases: [
        "Stress fractures need reduced load — a boot protects healing bone.",
        "Return to running is gradual when pain-free walking and hop tests pass.",
      ],
      weakTags: ["speaking:structure", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Tell me how your training changed before the foot pain.", annotation: "Training history" },
      { speaker: "patient", line: "Jumped mileage for a half-marathon. I kept running until I limped." },
      { speaker: "candidate", line: "What concerns you about taking time off?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Non-refundable entry next month. I'll lose all fitness." },
      { speaker: "candidate", line: "A stress fracture needs a boot and no impact for several weeks.", annotation: "Information giving" },
      { speaker: "candidate", line: "Cross-train cycling if pain-free. When will you start upper-body sessions?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-pod-ca-w3",
    profession: "podiatry",
    difficulty: 2,
    countryCode: "CA",
    setting: "High-risk foot clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Podiatrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain Charcot foot management in diabetes — offloading and monitoring.",
      patientDetails: "Mr Tremblay, 63, type 2 diabetes, warm swollen midfoot, reduced sensation",
      yourTasks: [
        "Elicit symptom onset and current footwear",
        "Explain Charcot neuroarthropathy and urgency",
        "Discuss total contact cast or boot offloading",
        "Check understanding and follow-up",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Thought it was gout and took anti-inflammatories", "Cannot miss warehouse shifts"],
      patientKnowledge: "Foot red and swollen two weeks, walks in steel-toe boots daily",
    },
    coaching: {
      iceQuestions: [
        "When did you notice the foot swelling and warmth?",
        "What do you think caused it?",
        "What work footwear do you use?",
      ],
      structure: ["History", "Explain Charcot", "Offloading plan", "Check understanding"],
      phrasesToAvoid: ["Just wear wider shoes", "It's only a sprain"],
      usefulPhrases: [
        "Charcot foot can collapse the arch — immediate offloading protects the joint.",
        "Steel-toe boots will worsen damage — you'll need a cast boot and limited weight-bearing.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:ice-expectations"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Tremblay, when did your foot become swollen and warm?", annotation: "History" },
      { speaker: "patient", line: "Two weeks. I thought gout — took ibuprofen. I can't miss warehouse shifts." },
      { speaker: "candidate", line: "What shoes do you wear at work?", annotation: "Footwear assessment" },
      { speaker: "patient", line: "Steel-toe boots twelve hours. Numb toes sometimes." },
      { speaker: "candidate", line: "This may be Charcot foot — walking on it risks collapse. You need a cast boot now.", annotation: "Information giving" },
      { speaker: "candidate", line: "Stop steel-toe boots until review. What will you tell your supervisor?", annotation: "Check understanding" },
    ],
  },
  // optometry — UK, CA
  {
    id: "s-opt-uk-w3",
    profession: "optometry",
    difficulty: 2,
    countryCode: "UK",
    setting: "Optometry practice",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Optometrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain new primary open-angle glaucoma diagnosis and lifelong drop therapy.",
      patientDetails: "Mrs Okonkwo, 64, elevated IOP 28mmHg, early visual field loss",
      yourTasks: [
        "Elicit concerns about vision and treatment",
        "Explain glaucoma as optic nerve damage",
        "Demonstrate drop instillation and adherence",
        "Check understanding and follow-up",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears going blind like aunt", "Worries drops sting and makeup runs"],
      patientKnowledge: "No symptoms, thinks glasses prescription alone caused referral",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about today's test results?",
        "What worries you about using eye drops long term?",
        "What would help you remember daily drops?",
      ],
      structure: ["ICE", "Explain glaucoma", "Drop technique", "Check understanding"],
      phrasesToAvoid: ["You're already blind", "Surgery is inevitable now"],
      usefulPhrases: [
        "Glaucoma is often silent — drops lower pressure to protect the optic nerve.",
        "Punctal occlusion after drops reduces stinging and systemic absorption.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Okonkwo, what do you understand about your eye pressure result?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Something about glaucoma. My aunt went blind — I see fine." },
      { speaker: "candidate", line: "What concerns you about daily drops?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Stinging and ruining makeup. I thought I just needed new glasses." },
      { speaker: "candidate", line: "Open-angle glaucoma damages the nerve slowly — drops protect vision.", annotation: "Information giving" },
      { speaker: "candidate", line: "I'll show instillation and lid closure. How will you remember every evening?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-opt-ca-w3",
    profession: "optometry",
    difficulty: 2,
    countryCode: "CA",
    setting: "Optometry clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Optometrist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Counsel on dry age-related macular degeneration and Amsler grid self-monitoring.",
      patientDetails: "Mr Garcia, 74, dry AMD both eyes, mild distortion reading",
      yourTasks: [
        "Elicit visual symptoms and impact on reading",
        "Explain dry AMD progression and monitoring",
        "Teach Amsler grid use and red flags",
        "Discuss lighting and low-vision aids",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Terrified of wet AMD injections", "Lives alone, drives locally"],
      patientKnowledge: "Notices wavy lines sometimes, stopped evening reading, no grid use",
    },
    coaching: {
      iceQuestions: [
        "What changes have you noticed when reading?",
        "What worries you about macular degeneration?",
        "Who could help you check the grid at home?",
      ],
      structure: ["Symptoms", "Explain AMD", "Amsler teaching", "Check understanding"],
      phrasesToAvoid: ["You'll definitely need injections", "Nothing can be done"],
      usefulPhrases: [
        "Dry AMD is monitored — report new distortion promptly for wet change.",
        "Cover one eye, check the grid weekly — wavy lines need urgent review.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr Garcia, what changes have you noticed when reading?", annotation: "Open question" },
      { speaker: "patient", line: "Lines look wavy sometimes. I'm scared of those eye injections." },
      { speaker: "candidate", line: "What do you understand about dry macular degeneration?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Central blur. I still drive short trips — I live alone." },
      { speaker: "candidate", line: "Dry AMD needs monitoring. Use the Amsler grid weekly — one eye at a time.", annotation: "Teaching" },
      { speaker: "candidate", line: "New distortion or blank patches need same-week review. Show me how you'll check it.", annotation: "Check understanding" },
    ],
  },
  // dietetics — UK, AU
  {
    id: "s-diet-uk-w3",
    profession: "dietetics",
    difficulty: 2,
    countryCode: "UK",
    setting: "Gastroenterology outpatient",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dietitian",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Introduce a low FODMAP approach for irritable bowel syndrome with bloating.",
      patientDetails: "Ms Khan, 31, IBS-D, bloating after onions and wheat, no alarm features",
      yourTasks: [
        "Assess symptom pattern and current diet",
        "Explain FODMAP mechanism in accessible language",
        "Outline elimination and reintroduction phases",
        "Check understanding and agree first steps",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears overly restrictive diet", "Eats vegetarian curries most nights"],
      patientKnowledge: "Self-diagnosed gluten issue, avoids bread but uses garlic/onion heavily",
    },
    coaching: {
      iceQuestions: [
        "Describe a typical day of eating and when symptoms flare.",
        "What have you already tried to manage bloating?",
        "What concerns you about a structured elimination diet?",
      ],
      structure: ["Symptom-linked history", "Explain FODMAP", "Phased plan", "Check understanding"],
      phrasesToAvoid: ["It's just anxiety", "Never eat wheat again"],
      usefulPhrases: [
        "FODMAPs are fermentable carbs — a short elimination can identify triggers.",
        "Reintroduction prevents unnecessary long-term restrictions.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Ms Khan, walk me through yesterday's meals and when bloating started.", annotation: "Diet history" },
      { speaker: "patient", line: "Vegetable curry with onion and garlic — bloating by evening." },
      { speaker: "candidate", line: "What concerns you about trying low FODMAP?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Too restrictive. I thought wheat was the only problem." },
      { speaker: "candidate", line: "We'll trial four weeks avoiding high-FODMAP triggers, then reintroduce systematically.", annotation: "Information giving" },
      { speaker: "candidate", line: "Swap onion for garlic-infused oil this week. What will you change first?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-diet-au-w3",
    profession: "dietetics",
    difficulty: 2,
    countryCode: "AU",
    setting: "Antenatal clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Dietitian",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Teach meal timing and carbohydrate distribution for gestational diabetes.",
      patientDetails: "Mrs Tan, 33, 28 weeks pregnant, GDM on glucometer, fasting 5.8 mmol/L",
      yourTasks: [
        "Assess current eating pattern and cultural foods",
        "Explain post-meal glucose targets",
        "Suggest balanced meals and snack timing",
        "Check understanding and agree monitoring plan",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Family says sweet rice is needed for baby", "Works night shifts three days weekly"],
      patientKnowledge: "Avoids sugar drinks, large white rice dinners, irregular breakfast",
    },
    coaching: {
      iceQuestions: [
        "What do you usually eat across a day including night shifts?",
        "What have you heard about diet during pregnancy diabetes?",
        "What changes feel realistic with your roster?",
      ],
      structure: ["Diet history", "Explain GDM targets", "Practical swaps", "Check understanding"],
      phrasesToAvoid: ["Cut all carbs", "One slip harms the baby"],
      usefulPhrases: [
        "Spreading carbohydrate across meals prevents spikes.",
        "Pair rice with protein and vegetables — portion size matters.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mrs Tan, describe what you ate yesterday including night shift.", annotation: "Diet history" },
      { speaker: "patient", line: "Skipped breakfast, big rice plate at dinner. Mum says sweet rice helps the baby." },
      { speaker: "candidate", line: "What do you know about your glucose readings?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Fasting a bit high. I avoid soft drink but love white rice." },
      { speaker: "candidate", line: "Aim for steady carbs — half-cup rice with protein and veg at meals.", annotation: "Information giving" },
      { speaker: "candidate", line: "Check two hours after largest meal. What will you pack for night shift?", annotation: "Check understanding" },
    ],
  },
  // radiography — IE, NZ
  {
    id: "s-rad-ie-w3",
    profession: "radiography",
    difficulty: 2,
    countryCode: "IE",
    setting: "Fluoroscopy suite",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Radiographer",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Prepare a patient for barium swallow study to investigate dysphagia.",
      patientDetails: "Mr O'Brien, 60, progressive solids dysphagia, no acute obstruction",
      yourTasks: [
        "Explain procedure steps and barium taste",
        "Discuss fasting and medication timing",
        "Address aspiration concerns",
        "Check understanding and consent",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Gags easily", "Worried barium causes constipation for days"],
      patientKnowledge: "Fasting since midnight, takes morning thyroxine usually with breakfast",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about today's swallow test?",
        "What worries you about drinking the barium?",
        "When did you last eat or drink?",
      ],
      structure: ["Explain study", "Preparation", "During test", "Check understanding"],
      phrasesToAvoid: ["Just gulp it down", "You won't feel anything"],
      usefulPhrases: [
        "You'll drink thin and thick barium while we take X-ray video.",
        "Plenty of fluids afterward help clear barium — stool may pale briefly.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Mr O'Brien, what do you know about today's barium swallow?", annotation: "ICE — Ideas" },
      { speaker: "patient", line: "Camera of swallowing. I gag easily — will I choke?" },
      { speaker: "candidate", line: "What concerns you about afterward?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Constipation. I usually take thyroxine with breakfast — I fasted since midnight." },
      { speaker: "candidate", line: "You'll sip barium in different thicknesses while we image. Fluids after help clearance.", annotation: "Information giving" },
      { speaker: "candidate", line: "Take thyroxine after the study with water. Ready to start?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-rad-nz-w3",
    profession: "radiography",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Ultrasound department",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Sonographer",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Explain obstetric anatomy ultrasound at 20 weeks to an anxious expectant parent.",
      patientDetails: "Ms Williams, 32, 20-week singleton pregnancy, partner attends",
      yourTasks: [
        "Explain purpose of morphology scan",
        "Discuss what can and cannot be detected",
        "Describe duration, gel and comfort",
        "Check understanding and consent",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Friend's scan missed heart problem", "Worried about radiation harm"],
      patientKnowledge: "Thinks scan is only for gender reveal, full bladder myth from forum",
    },
    coaching: {
      iceQuestions: [
        "What do you understand about today's ultrasound?",
        "What concerns you about the scan?",
        "What would you like to know by the end?",
      ],
      structure: ["Explain purpose", "Limitations", "Procedure", "Check understanding"],
      phrasesToAvoid: ["We'll guarantee a healthy baby", "Ultrasound uses radiation"],
      usefulPhrases: [
        "We assess growth, organs and placenta — not every condition is visible.",
        "Ultrasound uses sound waves, not radiation. Gel warms on skin.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "What do you understand about this twenty-week scan?", annotation: "ICE — Ideas" },
      { speaker: "carer", line: "Gender reveal party tonight. Friend's scan missed a heart defect." },
      { speaker: "candidate", line: "What worries you about safety or findings?", annotation: "ICE — Concerns" },
      { speaker: "carer", line: "Radiation harm. Forums said I need a bursting bladder." },
      { speaker: "candidate", line: "This morphology scan checks anatomy and growth — sound waves only, no radiation.", annotation: "Information giving" },
      { speaker: "candidate", line: "Some conditions may need follow-up tests. Questions before we begin?", annotation: "Check understanding" },
    ],
  },
  // speech pathology — IE, NZ, CA
  {
    id: "s-sp-ie-w3",
    profession: "speech_pathology",
    difficulty: 2,
    countryCode: "IE",
    setting: "Community paediatric clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Speech Pathologist",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Counsel parents on developmental stuttering in a preschool child.",
      patientDetails: "Noah, 4, stuttered onset 3 months, repeats syllables, otherwise typical development",
      yourTasks: [
        "Elicit onset and family concerns",
        "Explain common developmental stuttering",
        "Teach supportive home communication strategies",
        "Check understanding and agree review",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Grandmother says child is nervous", "Parents interrupt to finish sentences"],
      patientKnowledge: "Started after new sibling, no other speech delay",
    },
    coaching: {
      iceQuestions: [
        "When did you first notice Noah's speech changes?",
        "What happens at home when he stutters?",
        "What worries the family most?",
      ],
      structure: ["Onset history", "Explain stuttering", "Home strategies", "Check understanding"],
      phrasesToAvoid: ["He's anxious", "Slow down and think"],
      usefulPhrases: [
        "Many preschoolers stutter temporarily — calm listening reduces pressure.",
        "Give extra time, don't finish words, keep eye contact.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:clinical-comm"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "When did Noah's stutter start and what does it sound like?", annotation: "History" },
      { speaker: "carer", line: "Three months, since his sister was born. He repeats sounds." },
      { speaker: "candidate", line: "What happens when he stutters at home?", annotation: "Environment" },
      { speaker: "carer", line: "We finish his sentences. Granny says he's nervous." },
      { speaker: "candidate", line: "Developmental stuttering is common — pause and listen without interrupting.", annotation: "Information giving" },
      { speaker: "candidate", line: "Review in six weeks. Show me how you'll respond when he repeats a word.", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-sp-nz-w3",
    profession: "speech_pathology",
    difficulty: 2,
    countryCode: "NZ",
    setting: "Voice clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Speech Pathologist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Explain vocal hygiene and therapy plan for a teacher with vocal nodules.",
      patientDetails: "Ms Williams, 38, hoarse voice, bilateral nodules on stroboscopy, classroom teacher",
      yourTasks: [
        "Explore voice use and hydration habits",
        "Explain nodules and voice rest principles",
        "Teach easy onset and amplification strategies",
        "Check understanding and agree practice",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot take time off teaching", "Whispers to 'rest' voice"],
      patientKnowledge: "Drinks coffee all day, shouts over noisy class, whispers between lessons",
    },
    coaching: {
      iceQuestions: [
        "Describe a typical teaching day for your voice.",
        "What have you tried when hoarse?",
        "What worries you about therapy?",
      ],
      structure: ["Voice habits", "Explain nodules", "Strategies", "Check understanding"],
      phrasesToAvoid: ["Just stop talking", "Whispering is better"],
      usefulPhrases: [
        "Whispering strains more than soft conversational voice.",
        "A classroom microphone reduces forceful projection.",
      ],
      weakTags: ["speaking:structure", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Walk me through how you use your voice on a school day.", annotation: "Voice history" },
      { speaker: "patient", line: "Shout over year nines. Coffee only — water rarely." },
      { speaker: "candidate", line: "What do you do when hoarse between classes?", annotation: "Current strategies" },
      { speaker: "patient", line: "Whisper. I can't take leave — report season." },
      { speaker: "candidate", line: "Nodules need reduced strain — use a mic and easy onset, not whispering.", annotation: "Information giving" },
      { speaker: "candidate", line: "Sip water hourly. Practise gentle onset on 'hello'. When will you trial the mic?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-sp-ca-w3",
    profession: "speech_pathology",
    difficulty: 2,
    countryCode: "CA",
    setting: "ICU step-down unit",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Speech-Language Pathologist",
    interlocutorRole: "Patient",
    cardText: {
      overview: "Introduce a speaking valve on tracheostomy for a patient weaning ventilation.",
      patientDetails: "Mr Tremblay, 55, tracheostomy 10 days, alert, weak voice with finger occlusion",
      yourTasks: [
        "Assess communication frustration and cuff status",
        "Explain speaking valve function and safety",
        "Trial valve with monitoring plan",
        "Check understanding and emergency steps",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Fears suffocation", "Family visits limited due to weak whisper"],
      patientKnowledge: "Communicates by writing, unclear why cuff must be deflated for valve",
    },
    coaching: {
      iceQuestions: [
        "How have you been communicating with staff and family?",
        "What concerns you about trying the speaking valve?",
        "What do you understand about your tracheostomy cuff?",
      ],
      structure: ["Communication assessment", "Explain valve", "Safety trial", "Check understanding"],
      phrasesToAvoid: ["You can't breathe with a valve", "Just try it"],
      usefulPhrases: [
        "The valve redirects air through vocal cords — cuff must be down for airflow.",
        "We monitor oxygen and remove the valve if breathing work increases.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:ice-expectations"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "How have you been getting your message across this week?", annotation: "Communication assessment" },
      { speaker: "patient", line: "Writing notes. Family can't hear my whisper." },
      { speaker: "candidate", line: "What worries you about a speaking valve?", annotation: "ICE — Concerns" },
      { speaker: "patient", line: "Suffocating. I don't know why the cuff matters." },
      { speaker: "candidate", line: "With cuff deflated, the valve sends air up to your voice box.", annotation: "Information giving" },
      { speaker: "candidate", line: "We trial five minutes with monitoring. Signal if dizzy or short of breath.", annotation: "Check understanding" },
    ],
  },
  // veterinary science — UK, CA
  {
    id: "s-vet-uk-w3",
    profession: "veterinary_science",
    difficulty: 2,
    countryCode: "UK",
    setting: "Exotic pet practice",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Veterinarian",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Explain rabbit gastrointestinal stasis home care and emergency warning signs.",
      patientDetails: "Clover, 3yo dwarf rabbit, reduced appetite 24h, small dry droppings",
      yourTasks: [
        "Elicit diet and housing history",
        "Explain GI stasis and pain",
        "Discuss syringe feeding, hydration and motility drugs",
        "Check understanding and red flags",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Cannot afford hospitalization", "Thought skipping hay was fine with pellets"],
      patientKnowledge: "Mostly pellets, little hay, hutch indoors, not eating since yesterday",
    },
    coaching: {
      iceQuestions: [
        "What has Clover eaten in the last twenty-four hours?",
        "What changes have you noticed in droppings?",
        "What concerns you about treatment at home?",
      ],
      structure: ["History", "Explain stasis", "Home care", "Emergency signs"],
      phrasesToAvoid: ["Rabbits just stop eating sometimes", "Pellets are enough"],
      usefulPhrases: [
        "GI stasis is painful — unlimited hay and hydration are critical.",
        "No droppings for twelve hours or bloating needs emergency review.",
      ],
      weakTags: ["speaking:ice-expectations", "speaking:structure"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Tell me Clover's diet and what she's eaten since yesterday.", annotation: "History" },
      { speaker: "carer", line: "Mostly pellets, little hay. Nothing since yesterday — droppings are tiny." },
      { speaker: "candidate", line: "What worries you about managing this at home?", annotation: "ICE — Concerns" },
      { speaker: "carer", line: "Can't afford inpatient care. I thought pellets were enough." },
      { speaker: "candidate", line: "GI stasis needs pain relief, fluids and hay — we'll syringe feed if needed.", annotation: "Information giving" },
      { speaker: "candidate", line: "If no droppings by morning or belly blows up, come straight back. Questions?", annotation: "Check understanding" },
    ],
  },
  {
    id: "s-vet-ca-w3",
    profession: "veterinary_science",
    difficulty: 2,
    countryCode: "CA",
    setting: "Small animal clinic",
    durationMinutes: 5,
    prepMinutes: 3,
    candidateRole: "Veterinarian",
    interlocutorRole: "Carer",
    cardText: {
      overview: "Discuss Lyme disease prevention and tick removal for an outdoor dog.",
      patientDetails: "Scout, 5yo Labrador, hiking in tick area, owner found engorged tick yesterday",
      yourTasks: [
        "Review tick exposure and prior prevention",
        "Explain Lyme transmission and regional risk",
        "Demonstrate tick removal and discuss preventives",
        "Check understanding and monitoring plan",
      ],
    },
    hiddenFromCandidate: {
      patientConcerns: ["Burned tick with lighter before visit", "Avoids chemicals on children and pets"],
      patientKnowledge: "No vet preventives, dog tired today but eating, removed partial tick",
    },
    coaching: {
      iceQuestions: [
        "Where does Scout hike and how often do you find ticks?",
        "What did you do when you found yesterday's tick?",
        "What concerns you about preventive products?",
      ],
      structure: ["Exposure history", "Explain Lyme", "Removal + prevention", "Check understanding"],
      phrasesToAvoid: ["Lyme is everywhere instantly", "Burning ticks is fine"],
      usefulPhrases: [
        "Use fine tweezers close to skin — don't twist or burn the tick.",
        "Vaccination and monthly preventives reduce Lyme risk in endemic areas.",
      ],
      weakTags: ["speaking:clinical-comm", "speaking:language"],
    },
    modelDialogue: [
      { speaker: "candidate", line: "Tell me where Scout hikes and what you did with yesterday's tick.", annotation: "History" },
      { speaker: "carer", line: "Forest trails weekly. I burned it with a lighter — head may be left in." },
      { speaker: "candidate", line: "What concerns you about preventives or vaccines?", annotation: "ICE — Concerns" },
      { speaker: "carer", line: "Chemicals near kids. He's tired today but eating." },
      { speaker: "candidate", line: "Lyme spreads after prolonged attachment — we'll discuss testing and preventives.", annotation: "Information giving" },
      { speaker: "candidate", line: "Future removal with tweezers straight up. Watch for lameness or fever. Questions?", annotation: "Check understanding" },
    ],
  },
];
